//go:build !noasm && arm64
// Code generated by gocc v0.16.3-rev-6adf1e2 -- DO NOT EDIT.
//
// Source file         : range_neon.c
// Clang version       : Apple clang version 17.0.0 (clang-1700.6.3.2)
// Target architecture : arm64
// Compiler options    : [none]

#include "textflag.h"

DATA LCPI0_0<>+0x00(SB)/8, $0x0000000000000000
DATA LCPI0_0<>+0x08(SB)/8, $0x0302010100000000
GLOBL LCPI0_0<>(SB), (RODATA|NOPTR), $16

DATA LCPI0_1<>+0x00(SB)/8, $0x0000000000000000
DATA LCPI0_1<>+0x08(SB)/8, $0x0808080800000000
GLOBL LCPI0_1<>(SB), (RODATA|NOPTR), $16

DATA LCPI0_2<>+0x00(SB)/8, $0x809080a080808000
DATA LCPI0_2<>+0x08(SB)/8, $0xffffffffffffffc2
GLOBL LCPI0_2<>(SB), (RODATA|NOPTR), $16

DATA LCPI0_3<>+0x00(SB)/8, $0x8fbf9fbfbfbfbf7f
DATA LCPI0_3<>+0x08(SB)/8, $0x00000000000000f4
GLOBL LCPI0_3<>(SB), (RODATA|NOPTR), $16

DATA _range_adjust_tbl<>+0x00(SB)/8, $0x0000000000000302
DATA _range_adjust_tbl<>+0x08(SB)/8, $0x0000000000000400
DATA _range_adjust_tbl<>+0x10(SB)/8, $0x0000000000000000
DATA _range_adjust_tbl<>+0x18(SB)/8, $0x0000000000030000
GLOBL _range_adjust_tbl<>(SB), (RODATA|NOPTR), $32

TEXT ·utf8_valid_range(SB), NOSPLIT, $0-17
	MOVD src+0(FP), R0
	MOVD src_len+8(FP), R1
	NOP                               // (skipped)                            // stp	x29, x30, [sp, #-16]!
	CMP  $17, R1                      // <--                                  // cmp	x1, #17
	NOP                               // (skipped)                            // mov	x29, sp
	BLT  LBB0_15                      // <--                                  // b.lt	.LBB0_15
	MOVD $_range_adjust_tbl<>(SB), R8 // <--                                  // adrp	x8, _range_adjust_tbl
	NOP                               // (skipped)                            // add	x8, x8, :lo12:_range_adjust_tbl
	WORD $0x6f00e400                  // VMOVI $0, V0.D2                      // movi	v0.2d, #0000000000000000
	WORD $0x4c408101                  // VLD2 (R8), [V1.B16, V2.B16]          // ld2	{ v1.16b, v2.16b }, [x8]
	MOVD $LCPI0_0<>(SB), R9           // <--                                  // adrp	x9, .LCPI0_0
	WORD $0x4f00e423                  // VMOVI $1, V3.B16                     // movi	v3.16b, #1
	WORD $0x4f00e445                  // VMOVI $2, V5.B16                     // movi	v5.16b, #2
	WORD $0x4f01e406                  // VMOVI $32, V6.B16                    // movi	v6.16b, #32
	WORD $0x6f00e407                  // VMOVI $0, V7.D2                      // movi	v7.2d, #0000000000000000
	WORD $0x6f00e411                  // VMOVI $0, V17.D2                     // movi	v17.2d, #0000000000000000
	WORD $0x6f00e410                  // VMOVI $0, V16.D2                     // movi	v16.2d, #0000000000000000
	WORD $0x3dc00124                  // FMOVQ (R9), F4                       // ldr	q4, [x9, :lo12:.LCPI0_0]
	MOVD $LCPI0_1<>(SB), R8           // <--                                  // adrp	x8, .LCPI0_1
	MOVD $LCPI0_2<>(SB), R9           // <--                                  // adrp	x9, .LCPI0_2
	MOVD $LCPI0_3<>(SB), R10          // <--                                  // adrp	x10, .LCPI0_3
	WORD $0x3dc00112                  // FMOVQ (R8), F18                      // ldr	q18, [x8, :lo12:.LCPI0_1]
	WORD $0x3dc00133                  // FMOVQ (R9), F19                      // ldr	q19, [x9, :lo12:.LCPI0_2]
	WORD $0x3dc00154                  // FMOVQ (R10), F20                     // ldr	q20, [x10, :lo12:.LCPI0_3]
	SUB  $16, R0, R8                  // <--                                  // sub	x8, x0, #16
	JMP  LBB0_3                       // <--                                  // b	.LBB0_3

LBB0_2:
	ADD $16, R1, R9 // <--                                  // add	x9, x1, #16
	ADD $16, R8, R8 // <--                                  // add	x8, x8, #16
	CMP $31, R9     // <--                                  // cmp	x9, #31
	BLS LBB0_7      // <--                                  // b.ls	.LBB0_7

LBB0_3:
	VMOV  V16.B16, V21.B16                   // <--                                  // mov	v21.16b, v16.16b
	WORD  $0x3dc00510                        // FMOVQ 16(R8), F16                    // ldr	q16, [x8, #16]
	VMOV  V17.B16, V23.B16                   // <--                                  // mov	v23.16b, v17.16b
	SUB   $16, R1, R1                        // <--                                  // sub	x1, x1, #16
	WORD  $0x6f0c0616                        // VUSHR $4, V16.B16, V22.B16           // ushr	v22.16b, v16.16b, #4
	TST   $112, R1                           // <--                                  // tst	x1, #0x70
	VEXT  $15, V16.B16, V21.B16, V21.B16     // <--                                  // ext	v21.16b, v21.16b, v16.16b, #15
	VTBL  V22.B16, [V4.B16], V17.B16         // <--                                  // tbl	v17.16b, { v4.16b }, v22.16b
	VTBL  V22.B16, [V18.B16], V22.B16        // <--                                  // tbl	v22.16b, { v18.16b }, v22.16b
	VADD  V6.B16, V21.B16, V21.B16           // <--                                  // add	v21.16b, v21.16b, v6.16b
	VEXT  $14, V17.B16, V23.B16, V24.B16     // <--                                  // ext	v24.16b, v23.16b, v17.16b, #14
	VEXT  $15, V17.B16, V23.B16, V25.B16     // <--                                  // ext	v25.16b, v23.16b, v17.16b, #15
	VEXT  $13, V17.B16, V23.B16, V23.B16     // <--                                  // ext	v23.16b, v23.16b, v17.16b, #13
	VTBL  V21.B16, [V1.B16, V2.B16], V21.B16 // <--                                  // tbl	v21.16b, { v1.16b, v2.16b }, v21.16b
	WORD  $0x6e232f18                        // VUQSUB V3.B16, V24.B16, V24.B16      // uqsub	v24.16b, v24.16b, v3.16b
	VORR  V22.B16, V25.B16, V22.B16          // <--                                  // orr	v22.16b, v25.16b, v22.16b
	WORD  $0x6e252ef7                        // VUQSUB V5.B16, V23.B16, V23.B16      // uqsub	v23.16b, v23.16b, v5.16b
	VORR  V24.B16, V22.B16, V22.B16          // <--                                  // orr	v22.16b, v22.16b, v24.16b
	VORR  V23.B16, V22.B16, V22.B16          // <--                                  // orr	v22.16b, v22.16b, v23.16b
	VADD  V21.B16, V22.B16, V21.B16          // <--                                  // add	v21.16b, v22.16b, v21.16b
	VTBL  V21.B16, [V19.B16], V22.B16        // <--                                  // tbl	v22.16b, { v19.16b }, v21.16b
	VTBL  V21.B16, [V20.B16], V21.B16        // <--                                  // tbl	v21.16b, { v20.16b }, v21.16b
	WORD  $0x6e3036d6                        // VCMHI V16.B16, V22.B16, V22.B16      // cmhi	v22.16b, v22.16b, v16.16b
	WORD  $0x6e353615                        // VCMHI V21.B16, V16.B16, V21.B16      // cmhi	v21.16b, v16.16b, v21.16b
	VORR  V22.B16, V7.B16, V7.B16            // <--                                  // orr	v7.16b, v7.16b, v22.16b
	VORR  V21.B16, V0.B16, V0.B16            // <--                                  // orr	v0.16b, v0.16b, v21.16b
	BNE   LBB0_2                             // <--                                  // b.ne	.LBB0_2
	VORR  V7.B16, V0.B16, V21.B16            // <--                                  // orr	v21.16b, v0.16b, v7.16b
	WORD  $0x6eb0aab5                        // VUMAXV V21.S4, V21                   // umaxv	s21, v21.4s
	FMOVS F21, R9                            // <--                                  // fmov	w9, s21
	CBZW  R9, LBB0_2                         // <--                                  // cbz	w9, .LBB0_2
	MOVW  ZR, R8                             // <--                                  // mov	w8, wzr

LBB0_6:
	MOVW R8, R0         // <--                                  // mov	w0, w8
	NOP                 // (skipped)                            // ldp	x29, x30, [sp], #16
	MOVB R0, ret+16(FP) // <--
	RET                 // <--                                  // ret

LBB0_7:
	VORR  V7.B16, V0.B16, V0.B16 // <--                                  // orr	v0.16b, v0.16b, v7.16b
	WORD  $0x6eb0a800            // VUMAXV V0.S4, V0                     // umaxv	s0, v0.4s
	FMOVS F0, R9                 // <--                                  // fmov	w9, s0
	CBZW  R9, LBB0_9             // <--                                  // cbz	w9, .LBB0_9

LBB0_8:
	MOVW ZR, R8         // <--                                  // mov	w8, wzr
	MOVW R8, R0         // <--                                  // mov	w0, w8
	NOP                 // (skipped)                            // ldp	x29, x30, [sp], #16
	MOVB R0, ret+16(FP) // <--
	RET                 // <--                                  // ret

LBB0_9:
	VMOV V16.S[3], R9     // <--                                  // mov	w9, v16.s[3]
	MOVW $3221225471, R10 // <--                                  // mov	w10, #-1073741825
	CMPW R10, R9          // <--                                  // cmp	w9, w10
	BLE  LBB0_11          // <--                                  // b.le	.LBB0_11
	MOVW $1, R9           // <--                                  // mov	w9, #1
	JMP  LBB0_14          // <--                                  // b	.LBB0_14

LBB0_11:
	CMPW R9<<8, R10 // <--                                  // cmp	w10, w9, lsl #8
	BGE  LBB0_13    // <--                                  // b.ge	.LBB0_13
	MOVW $2, R9     // <--                                  // mov	w9, #2
	JMP  LBB0_14    // <--                                  // b	.LBB0_14

LBB0_13:
	MOVW $4294950911, R10 // <--                                  // mov	w10, #-16385
	CMPW R9.SXTH, R10     // <--                                  // cmp	w10, w9, sxth
	MOVW $3, R9           // <--                                  // mov	w9, #3
	CSEL LT, R9, ZR, R9   // <--                                  // csel	x9, x9, xzr, lt

LBB0_14:
	SUB R9, R8, R8  // <--                                  // sub	x8, x8, x9
	ADD R1, R9, R1  // <--                                  // add	x1, x9, x1
	ADD $16, R8, R0 // <--                                  // add	x0, x8, #16

LBB0_15:
	CBZW R1, LBB0_36     // <--                                  // cbz	w1, .LBB0_36
	MOVW $4294967232, R9 // <--                                  // mov	w9, #-64
	MOVW $224, R10       // <--                                  // mov	w10, #224
	MOVW $160, R11       // <--                                  // mov	w11, #160
	MOVW $240, R12       // <--                                  // mov	w12, #240
	JMP  LBB0_19         // <--                                  // b	.LBB0_19

LBB0_17:
	MOVW $1, R14 // <--                                  // mov	w14, #1

LBB0_18:
	ADD   R14.UXTW, R0, R0 // <--                                  // add	x0, x0, w14, uxtw
	SUBSW R14, R1, R1      // <--                                  // subs	w1, w1, w14
	BEQ   LBB0_36          // <--                                  // b.eq	.LBB0_36

LBB0_19:
	WORD $0x39c00008      // MOVBW (R0), R8                       // ldrsb	w8, [x0]
	TBZ  $31, R8, LBB0_17 // <--                                  // tbz	w8, #31, .LBB0_17
	CMPW $2, R1           // <--                                  // cmp	w1, #2
	ANDW $255, R8, R8     // <--                                  // and	w8, w8, #0xff
	BLT  LBB0_24          // <--                                  // b.lt	.LBB0_24
	SUBW $194, R8, R13    // <--                                  // sub	w13, w8, #194
	CMPW $29, R13         // <--                                  // cmp	w13, #29
	BHI  LBB0_24          // <--                                  // b.hi	.LBB0_24
	WORD $0x39c0040d      // MOVBW 1(R0), R13                     // ldrsb	w13, [x0, #1]
	CMNW $64, R13         // <--                                  // cmn	w13, #64
	BGE  LBB0_24          // <--                                  // b.ge	.LBB0_24
	MOVW $2, R14          // <--                                  // mov	w14, #2
	JMP  LBB0_18          // <--                                  // b	.LBB0_18

LBB0_24:
	CMPW  $2, R1           // <--                                  // cmp	w1, #2
	BLE   LBB0_8           // <--                                  // b.le	.LBB0_8
	WORD  $0x3940080d      // MOVBU 2(R0), R13                     // ldrb	w13, [x0, #2]
	WORD  $0x39c0040e      // MOVBW 1(R0), R14                     // ldrsb	w14, [x0, #1]
	SXTBW R13, R13         // <--                                  // sxtb	w13, w13
	CMNW  $64, R14         // <--                                  // cmn	w14, #64
	CCMPW LT, R13, R9, $0  // <--                                  // ccmp	w13, w9, #0, lt
	ANDW  $255, R14, R13   // <--                                  // and	w13, w14, #0xff
	CSETW LT, R15          // <--                                  // cset	w15, lt
	CMPW  $1, R15          // <--                                  // cmp	w15, #1
	BNE   LBB0_30          // <--                                  // b.ne	.LBB0_30
	CMPW  $159, R13        // <--                                  // cmp	w13, #159
	MOVW  $3, R14          // <--                                  // mov	w14, #3
	CCMPW HI, R8, R10, $0  // <--                                  // ccmp	w8, w10, #0, hi
	BEQ   LBB0_18          // <--                                  // b.eq	.LBB0_18
	SUBW  $225, R8, R16    // <--                                  // sub	w16, w8, #225
	CMPW  $12, R16         // <--                                  // cmp	w16, #12
	BCC   LBB0_18          // <--                                  // b.lo	.LBB0_18
	CMPW  $237, R8         // <--                                  // cmp	w8, #237
	ANDW  $254, R8, R14    // <--                                  // and	w14, w8, #0xfe
	CCMPW EQ, R13, R11, $2 // <--                                  // ccmp	w13, w11, #2, eq
	CSETW LO, R16          // <--                                  // cset	w16, lo
	CMPW  $238, R14        // <--                                  // cmp	w14, #238
	MOVW  $3, R14          // <--                                  // mov	w14, #3
	BEQ   LBB0_18          // <--                                  // b.eq	.LBB0_18
	TBNZ  $0, R16, LBB0_18 // <--                                  // tbnz	w16, #0, .LBB0_18

LBB0_30:
	CMPW  $3, R1           // <--                                  // cmp	w1, #3
	BEQ   LBB0_8           // <--                                  // b.eq	.LBB0_8
	WORD  $0x39400c0e      // MOVBU 3(R0), R14                     // ldrb	w14, [x0, #3]
	SXTBW R14, R14         // <--                                  // sxtb	w14, w14
	CMNW  $64, R14         // <--                                  // cmn	w14, #64
	CSELW GE, ZR, R15, R14 // <--                                  // csel	w14, wzr, w15, ge
	CMPW  $1, R14          // <--                                  // cmp	w14, #1
	BNE   LBB0_8           // <--                                  // b.ne	.LBB0_8
	CMPW  $143, R13        // <--                                  // cmp	w13, #143
	MOVW  $4, R14          // <--                                  // mov	w14, #4
	CCMPW HI, R8, R12, $0  // <--                                  // ccmp	w8, w12, #0, hi
	BEQ   LBB0_18          // <--                                  // b.eq	.LBB0_18
	SUBW  $241, R8, R15    // <--                                  // sub	w15, w8, #241
	CMPW  $3, R15          // <--                                  // cmp	w15, #3
	BCC   LBB0_18          // <--                                  // b.lo	.LBB0_18
	CMPW  $244, R8         // <--                                  // cmp	w8, #244
	MOVW  ZR, R8           // <--                                  // mov	w8, wzr
	BNE   LBB0_6           // <--                                  // b.ne	.LBB0_6
	CMPW  $143, R13        // <--                                  // cmp	w13, #143
	BLS   LBB0_18          // <--                                  // b.ls	.LBB0_18
	JMP   LBB0_6           // <--                                  // b	.LBB0_6

LBB0_36:
	MOVW $1, R8         // <--                                  // mov	w8, #1
	MOVW R8, R0         // <--                                  // mov	w0, w8
	NOP                 // (skipped)                            // ldp	x29, x30, [sp], #16
	MOVB R0, ret+16(FP) // <--
	RET                 // <--                                  // ret
