//go:build !noasm && amd64
// Code generated by gocc v0.16.3-rev-6adf1e2 -- DO NOT EDIT.
//
// Source file         : range_avx2.c
// Clang version       : Apple clang version 17.0.0 (clang-1700.6.3.2)
// Target architecture : amd64
// Compiler options    : -mavx2 -mfma

#include "textflag.h"

DATA LCPI0_0<>+0x00(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCPI0_0<>+0x08(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCPI0_0<>+0x10(SB)/8, $0x0f0f0f0f0f0f0f0f
DATA LCPI0_0<>+0x18(SB)/8, $0x0f0f0f0f0f0f0f0f
GLOBL LCPI0_0<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_1<>+0x00(SB)/8, $0x0000000000000000
DATA LCPI0_1<>+0x08(SB)/8, $0x0302010100000000
DATA LCPI0_1<>+0x10(SB)/8, $0x0000000000000000
DATA LCPI0_1<>+0x18(SB)/8, $0x0302010100000000
GLOBL LCPI0_1<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_2<>+0x00(SB)/8, $0x0000000000000000
DATA LCPI0_2<>+0x08(SB)/8, $0x0808080800000000
DATA LCPI0_2<>+0x10(SB)/8, $0x0000000000000000
DATA LCPI0_2<>+0x18(SB)/8, $0x0808080800000000
GLOBL LCPI0_2<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_3<>+0x00(SB)/8, $0x0101010101010101
DATA LCPI0_3<>+0x08(SB)/8, $0x0101010101010101
DATA LCPI0_3<>+0x10(SB)/8, $0x0101010101010101
DATA LCPI0_3<>+0x18(SB)/8, $0x0101010101010101
GLOBL LCPI0_3<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_4<>+0x00(SB)/8, $0x0202020202020202
DATA LCPI0_4<>+0x08(SB)/8, $0x0202020202020202
DATA LCPI0_4<>+0x10(SB)/8, $0x0202020202020202
DATA LCPI0_4<>+0x18(SB)/8, $0x0202020202020202
GLOBL LCPI0_4<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_5<>+0x00(SB)/8, $0x1111111111111111
DATA LCPI0_5<>+0x08(SB)/8, $0x1111111111111111
DATA LCPI0_5<>+0x10(SB)/8, $0x1111111111111111
DATA LCPI0_5<>+0x18(SB)/8, $0x1111111111111111
GLOBL LCPI0_5<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_6<>+0x00(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA LCPI0_6<>+0x08(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA LCPI0_6<>+0x10(SB)/8, $0xf0f0f0f0f0f0f0f0
DATA LCPI0_6<>+0x18(SB)/8, $0xf0f0f0f0f0f0f0f0
GLOBL LCPI0_6<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_7<>+0x00(SB)/8, $0x0000000000000200
DATA LCPI0_7<>+0x08(SB)/8, $0x0003000000000000
DATA LCPI0_7<>+0x10(SB)/8, $0x0000000000000200
DATA LCPI0_7<>+0x18(SB)/8, $0x0003000000000000
GLOBL LCPI0_7<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_8<>+0x00(SB)/8, $0x7070707070707070
DATA LCPI0_8<>+0x08(SB)/8, $0x7070707070707070
DATA LCPI0_8<>+0x10(SB)/8, $0x7070707070707070
DATA LCPI0_8<>+0x18(SB)/8, $0x7070707070707070
GLOBL LCPI0_8<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_9<>+0x00(SB)/8, $0x0000040000000300
DATA LCPI0_9<>+0x08(SB)/8, $0x0000000000000000
DATA LCPI0_9<>+0x10(SB)/8, $0x0000040000000300
DATA LCPI0_9<>+0x18(SB)/8, $0x0000000000000000
GLOBL LCPI0_9<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_10<>+0x00(SB)/8, $0x809080a080808000
DATA LCPI0_10<>+0x08(SB)/8, $0x7f7f7f7f7f7f7fc2
DATA LCPI0_10<>+0x10(SB)/8, $0x809080a080808000
DATA LCPI0_10<>+0x18(SB)/8, $0x7f7f7f7f7f7f7fc2
GLOBL LCPI0_10<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_11<>+0x00(SB)/8, $0x8fbf9fbfbfbfbf7f
DATA LCPI0_11<>+0x08(SB)/8, $0x80808080808080f4
DATA LCPI0_11<>+0x10(SB)/8, $0x8fbf9fbfbfbfbf7f
DATA LCPI0_11<>+0x18(SB)/8, $0x80808080808080f4
GLOBL LCPI0_11<>(SB), (RODATA|NOPTR), $32

DATA LCPI0_12<>+0x00(SB)/1, $0x02
GLOBL LCPI0_12<>(SB), (RODATA|NOPTR), $1

DATA LCPI0_13<>+0x00(SB)/1, $0x11
GLOBL LCPI0_13<>(SB), (RODATA|NOPTR), $1

DATA LCPI0_14<>+0x00(SB)/1, $0xf0
GLOBL LCPI0_14<>(SB), (RODATA|NOPTR), $1

DATA LCPI0_16<>+0x00(SB)/1, $0x70
GLOBL LCPI0_16<>(SB), (RODATA|NOPTR), $1

DATA LCPI0_15<>+0x00(SB)/8, $0x0000000000000200
DATA LCPI0_15<>+0x08(SB)/8, $0x0003000000000000
GLOBL LCPI0_15<>(SB), (RODATA|NOPTR), $16

DATA LCPI0_17<>+0x00(SB)/8, $0x0000040000000300
DATA LCPI0_17<>+0x08(SB)/8, $0x0000000000000000
GLOBL LCPI0_17<>(SB), (RODATA|NOPTR), $16

DATA LCPI0_18<>+0x00(SB)/8, $0x809080a080808000
DATA LCPI0_18<>+0x08(SB)/8, $0x7f7f7f7f7f7f7fc2
GLOBL LCPI0_18<>(SB), (RODATA|NOPTR), $16

DATA LCPI0_19<>+0x00(SB)/8, $0x8fbf9fbfbfbfbf7f
DATA LCPI0_19<>+0x08(SB)/8, $0x80808080808080f4
GLOBL LCPI0_19<>(SB), (RODATA|NOPTR), $16

DATA LCPI0_20<>+0x00(SB)/8, $0x0000000000000000
DATA LCPI0_20<>+0x08(SB)/8, $0x0302010100000000
GLOBL LCPI0_20<>(SB), (RODATA|NOPTR), $16

DATA LCPI0_21<>+0x00(SB)/8, $0x0000000000000000
DATA LCPI0_21<>+0x08(SB)/8, $0x0808080800000000
GLOBL LCPI0_21<>(SB), (RODATA|NOPTR), $16

TEXT ·utf8_valid_range_avx2(SB), NOSPLIT, $0-17
	MOVQ           src+0(FP), DI
	MOVQ           src_len+8(FP), SI
	NOP                                    // (skipped)                            // push	rbp
	NOP                                    // (skipped)                            // mov	rbp, rsp
	NOP                                    // (skipped)                            // and	rsp, -8
	CMPQ           SI, $0x20               // <--                                  // cmp	rsi, 32
	JL             LBB0_1                  // <--                                  // jl	.LBB0_1
	LONG           $0xffefc1c5             // VPXOR X7, X7, X7                     // vpxor	xmm7, xmm7, xmm7
	LONG           $0xc0eff9c5             // VPXOR X0, X0, X0                     // vpxor	xmm0, xmm0, xmm0
	VPBROADCASTB   LCPI0_12<>(SB), Y5      // <--                                  // vpbroadcastb	ymm5, byte ptr [rip + .LCPI0_12]
	VPBROADCASTB   LCPI0_13<>(SB), Y6      // <--                                  // vpbroadcastb	ymm6, byte ptr [rip + .LCPI0_13]
	VPBROADCASTB   LCPI0_14<>(SB), Y8      // <--                                  // vpbroadcastb	ymm8, byte ptr [rip + .LCPI0_14]
	VBROADCASTI128 LCPI0_15<>(SB), Y9      // <--                                  // vbroadcasti128	ymm9, xmmword ptr [rip + .LCPI0_15]
	VPBROADCASTB   LCPI0_16<>(SB), Y10     // <--                                  // vpbroadcastb	ymm10, byte ptr [rip + .LCPI0_16]
	VBROADCASTI128 LCPI0_17<>(SB), Y11     // <--                                  // vbroadcasti128	ymm11, xmmword ptr [rip + .LCPI0_17]
	VBROADCASTI128 LCPI0_18<>(SB), Y12     // <--                                  // vbroadcasti128	ymm12, xmmword ptr [rip + .LCPI0_18]
	VBROADCASTI128 LCPI0_19<>(SB), Y13     // <--                                  // vbroadcasti128	ymm13, xmmword ptr [rip + .LCPI0_19]
	LONG           $0xef0941c4; BYTE $0xf6 // VPXOR X14, X14, X14                  // vpxor	xmm14, xmm14, xmm14
	LONG           $0xef0141c4; BYTE $0xff // VPXOR X15, X15, X15                  // vpxor	xmm15, xmm15, xmm15
	JMP            LBB0_4                  // <--                                  // jmp	.LBB0_4

LBB0_3:
	ADDQ $0x20, DI    // <--                                  // add	rdi, 32
	LEAQ 0x20(SI), AX // <--                                  // lea	rax, [rsi + 32]
	CMPQ AX, $0x3f    // <--                                  // cmp	rax, 63
	JBE  LBB0_8       // <--                                  // jbe	.LBB0_8

LBB0_4:
	LONG           $0xcf6ffdc5               // VMOVDQA Y7, Y1                       // vmovdqa	ymm1, ymm7
	LONG           $0xd06ffdc5               // VMOVDQA Y0, Y2                       // vmovdqa	ymm2, ymm0
	LONG           $0x076ffec5               // VMOVDQU 0(DI), Y0                    // vmovdqu	ymm0, ymmword ptr [rdi]
	LONG           $0xd071c5c5; BYTE $0x04   // VPSRLW $0x4, Y0, Y7                  // vpsrlw	ymm7, ymm0, 4
	VPAND          LCPI0_0<>(SB), Y7, Y3     // <--                                  // vpand	ymm3, ymm7, ymmword ptr [rip + .LCPI0_0]
	VBROADCASTI128 LCPI0_20<>(SB), Y4        // <--                                  // vbroadcasti128	ymm4, xmmword ptr [rip + .LCPI0_20]
	LONG           $0x005de2c4; BYTE $0xfb   // VPSHUFB Y3, Y4, Y7                   // vpshufb	ymm7, ymm4, ymm3
	VBROADCASTI128 LCPI0_21<>(SB), Y4        // <--                                  // vbroadcasti128	ymm4, xmmword ptr [rip + .LCPI0_21]
	LONG           $0x005de2c4; BYTE $0xdb   // VPSHUFB Y3, Y4, Y3                   // vpshufb	ymm3, ymm4, ymm3
	LONG           $0x4675e3c4; WORD $0x21cf // VPERM2I128 $0x21, Y7, Y1, Y1         // vperm2i128	ymm1, ymm1, ymm7, 33
	LONG           $0x0f45e3c4; WORD $0x0fe1 // VPALIGNR $0xf, Y1, Y7, Y4            // vpalignr	ymm4, ymm7, ymm1, 15
	LONG           $0xdbebddc5               // VPOR Y3, Y4, Y3                      // vpor	ymm3, ymm4, ymm3
	LONG           $0x0f45e3c4; WORD $0x0ee1 // VPALIGNR $0xe, Y1, Y7, Y4            // vpalignr	ymm4, ymm7, ymm1, 14
	VPSUBUSB       LCPI0_3<>(SB), Y4, Y4     // <--                                  // vpsubusb	ymm4, ymm4, ymmword ptr [rip + .LCPI0_3]
	LONG           $0xdcebe5c5               // VPOR Y4, Y3, Y3                      // vpor	ymm3, ymm3, ymm4
	LONG           $0x0f45e3c4; WORD $0x0dc9 // VPALIGNR $0xd, Y1, Y7, Y1            // vpalignr	ymm1, ymm7, ymm1, 13
	LONG           $0xcdd8f5c5               // VPSUBUSB Y5, Y1, Y1                  // vpsubusb	ymm1, ymm1, ymm5
	LONG           $0xc9ebe5c5               // VPOR Y1, Y3, Y1                      // vpor	ymm1, ymm3, ymm1
	LONG           $0x466de3c4; WORD $0x21d0 // VPERM2I128 $0x21, Y0, Y2, Y2         // vperm2i128	ymm2, ymm2, ymm0, 33
	LONG           $0x0f7de3c4; WORD $0x0fd2 // VPALIGNR $0xf, Y2, Y0, Y2            // vpalignr	ymm2, ymm0, ymm2, 15
	LONG           $0xd6fcedc5               // VPADDB Y6, Y2, Y2                    // vpaddb	ymm2, ymm2, ymm6
	LONG           $0xd86dc1c4; BYTE $0xd8   // VPSUBUSB Y8, Y2, Y3                  // vpsubusb	ymm3, ymm2, ymm8
	LONG           $0x0035e2c4; BYTE $0xdb   // VPSHUFB Y3, Y9, Y3                   // vpshufb	ymm3, ymm9, ymm3
	LONG           $0xd2dcadc5               // VPADDUSB Y2, Y10, Y2                 // vpaddusb	ymm2, ymm10, ymm2
	LONG           $0x0025e2c4; BYTE $0xd2   // VPSHUFB Y2, Y11, Y2                  // vpshufb	ymm2, ymm11, ymm2
	LONG           $0xd3fcedc5               // VPADDB Y3, Y2, Y2                    // vpaddb	ymm2, ymm2, ymm3
	LONG           $0xc9fcedc5               // VPADDB Y1, Y2, Y1                    // vpaddb	ymm1, ymm2, ymm1
	LONG           $0x001de2c4; BYTE $0xd1   // VPSHUFB Y1, Y12, Y2                  // vpshufb	ymm2, ymm12, ymm1
	LONG           $0xd064edc5               // VPCMPGTB Y0, Y2, Y2                  // vpcmpgtb	ymm2, ymm2, ymm0
	LONG           $0xf2eb0dc5               // VPOR Y2, Y14, Y14                    // vpor	ymm14, ymm14, ymm2
	LONG           $0x0015e2c4; BYTE $0xc9   // VPSHUFB Y1, Y13, Y1                  // vpshufb	ymm1, ymm13, ymm1
	LONG           $0xc964fdc5               // VPCMPGTB Y1, Y0, Y1                  // vpcmpgtb	ymm1, ymm0, ymm1
	LONG           $0xf9eb05c5               // VPOR Y1, Y15, Y15                    // vpor	ymm15, ymm15, ymm1
	ADDQ           $-0x20, SI                // <--                                  // add	rsi, -32
	LONG           $0xe0c6f640               // TESTL $0xe0, SI                      // test	sil, -32
	JNE            LBB0_3                    // <--                                  // jne	.LBB0_3
	LONG           $0xeb05c1c4; BYTE $0xce   // VPOR Y14, Y15, Y1                    // vpor	ymm1, ymm15, ymm14
	LONG           $0x177de2c4; BYTE $0xc9   // VPTEST Y1, Y1                        // vptest	ymm1, ymm1
	JE             LBB0_3                    // <--                                  // je	.LBB0_3
	XORL           AX, AX                    // <--                                  // xor	eax, eax

LBB0_7:
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVB AX, ret+16(FP) // <--
	RET                 // <--                                  // ret

LBB0_1:
	WORD $0xf685 // TESTL SI, SI                         // test	esi, esi
	JNE  LBB0_15 // <--                                  // jne	.LBB0_15
	JMP  LBB0_13 // <--                                  // jmp	.LBB0_13

LBB0_8:
	LONG $0xeb0dc1c4; BYTE $0xcf   // VPOR Y15, Y14, Y1                    // vpor	ymm1, ymm14, ymm15
	LONG $0x177de2c4; BYTE $0xc9   // VPTEST Y1, Y1                        // vptest	ymm1, ymm1
	JNE  LBB0_29                   // <--                                  // jne	.LBB0_29
	LONG $0x397de3c4; WORD $0x01c0 // VEXTRACTI128 $0x1, Y0, X0            // vextracti128	xmm0, ymm0, 1
	LONG $0x1679e3c4; WORD $0x03c1 // VPEXTRD $0x3, X0, CX                 // vpextrd	ecx, xmm0, 3
	LONG $0x000001b8; BYTE $0x00   // MOVL $0x1, AX                        // mov	eax, 1
	CMPL CX, $-0x40000001          // <--                                  // cmp	ecx, -1073741825
	JG   LBB0_12                   // <--                                  // jg	.LBB0_12
	WORD $0xca89                   // MOVL CX, DX                          // mov	edx, ecx
	WORD $0xe2c1; BYTE $0x08       // SHLL $0x8, DX                        // shl	edx, 8
	LONG $0x000002b8; BYTE $0x00   // MOVL $0x2, AX                        // mov	eax, 2
	CMPL DX, $-0x40000001          // <--                                  // cmp	edx, -1073741825
	JG   LBB0_12                   // <--                                  // jg	.LBB0_12
	WORD $0xbf0f; BYTE $0xc1       // MOVSX CX, AX                         // movsx	eax, cx
	XORL CX, CX                    // <--                                  // xor	ecx, ecx
	CMPL AX, $-0x4000              // <--                                  // cmp	eax, -16384
	WORD $0x9d0f; BYTE $0xc1       // SETGE CL                             // setge	cl
	LEAQ 0(CX)(CX*2), AX           // <--                                  // lea	rax, [rcx + 2*rcx]

LBB0_12:
	SUBQ AX, DI  // <--                                  // sub	rdi, rax
	ADDQ AX, SI  // <--                                  // add	rsi, rax
	WORD $0xf685 // TESTL SI, SI                         // test	esi, esi
	JNE  LBB0_15 // <--                                  // jne	.LBB0_15

LBB0_13:
	WORD $0x01b0        // MOVL $0x1, AL                        // mov	al, 1
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVB AX, ret+16(FP) // <--
	RET                 // <--                                  // ret

LBB0_14:
	WORD $0x8944; BYTE $0xc0 // MOVL R8, AX                          // mov	eax, r8d
	ADDQ AX, DI              // <--                                  // add	rdi, rax
	WORD $0x2944; BYTE $0xc6 // SUBL R8, SI                          // sub	esi, r8d
	JE   LBB0_13             // <--                                  // je	.LBB0_13

LBB0_15:
	WORD $0xb60f; BYTE $0x0f       // MOVZX 0(DI), CX                      // movzx	ecx, byte ptr [rdi]
	LONG $0x0001b841; WORD $0x0000 // MOVL $0x1, R8                        // mov	r8d, 1
	WORD $0xc984                   // TESTL CL, CL                         // test	cl, cl
	JNS  LBB0_14                   // <--                                  // jns	.LBB0_14
	CMPL SI, $0x2                  // <--                                  // cmp	esi, 2
	JL   LBB0_19                   // <--                                  // jl	.LBB0_19
	WORD $0x418d; BYTE $0x3e       // LEAL 0x3e(CX), AX                    // lea	eax, [rcx + 62]
	WORD $0x1d3c                   // CMPL AL, $0x1d                       // cmp	al, 29
	JA   LBB0_19                   // <--                                  // ja	.LBB0_19
	LONG $0x0002b841; WORD $0x0000 // MOVL $0x2, R8                        // mov	r8d, 2
	CMPB 0x1(DI), $0xc0            // <--                                  // cmp	byte ptr [rdi + 1], -64
	JL   LBB0_14                   // <--                                  // jl	.LBB0_14

LBB0_19:
	CMPL SI, $0x3                  // <--                                  // cmp	esi, 3
	JL   LBB0_29                   // <--                                  // jl	.LBB0_29
	LONG $0x0157b60f               // MOVZX 0x1(DI), DX                    // movzx	edx, byte ptr [rdi + 1]
	WORD $0xfa80; BYTE $0xc0       // CMPL DL, $0xc0                       // cmp	dl, -64
	LONG $0xc09c0f41               // SETL R8                              // setl	r8b
	CMPB 0x2(DI), $0xc0            // <--                                  // cmp	byte ptr [rdi + 2], -64
	WORD $0x9c0f; BYTE $0xc0       // SETL AL                              // setl	al
	WORD $0x2044; BYTE $0xc0       // ANDL R8, AL                          // and	al, r8b
	WORD $0x013c                   // CMPL AL, $0x1                        // cmp	al, 1
	JNE  LBB0_24                   // <--                                  // jne	.LBB0_24
	WORD $0xf980; BYTE $0xe0       // CMPL CL, $0xe0                       // cmp	cl, -32
	LONG $0xc0940f41               // SETE R8                              // sete	r8b
	WORD $0xfa80; BYTE $0xa0       // CMPL DL, $0xa0                       // cmp	dl, -96
	LONG $0xc1930f41               // SETAE R9                             // setae	r9b
	WORD $0x2045; BYTE $0xc1       // ANDL R8, R9                          // and	r9b, r8b
	LONG $0x1f418d44               // LEAL 0x1f(CX), R8                    // lea	r8d, [rcx + 31]
	CMPB R8, $0xc                  // <--                                  // cmp	r8b, 12
	LONG $0xc0920f41               // SETB R8                              // setb	r8b
	WORD $0x0845; BYTE $0xc8       // ORL R9, R8                           // or	r8b, r9b
	LONG $0x0003b841; WORD $0x0000 // MOVL $0x3, R8                        // mov	r8d, 3
	JNE  LBB0_14                   // <--                                  // jne	.LBB0_14
	WORD $0xf980; BYTE $0xed       // CMPL CL, $0xed                       // cmp	cl, -19
	LONG $0xc1940f41               // SETE R9                              // sete	r9b
	WORD $0xfa80; BYTE $0xa0       // CMPL DL, $0xa0                       // cmp	dl, -96
	LONG $0xc2920f41               // SETB R10                             // setb	r10b
	WORD $0x8941; BYTE $0xcb       // MOVL CX, R11                         // mov	r11d, ecx
	ANDB $0xfe, R11                // <--                                  // and	r11b, -2
	CMPB R11, $0xee                // <--                                  // cmp	r11b, -18
	JE   LBB0_14                   // <--                                  // je	.LBB0_14
	WORD $0x2045; BYTE $0xd1       // ANDL R10, R9                         // and	r9b, r10b
	JNE  LBB0_14                   // <--                                  // jne	.LBB0_14

LBB0_24:
	CMPL SI, $0x3                  // <--                                  // cmp	esi, 3
	JE   LBB0_29                   // <--                                  // je	.LBB0_29
	CMPB 0x3(DI), $0xc0            // <--                                  // cmp	byte ptr [rdi + 3], -64
	LONG $0xc09c0f41               // SETL R8                              // setl	r8b
	WORD $0x2044; BYTE $0xc0       // ANDL R8, AL                          // and	al, r8b
	WORD $0x013c                   // CMPL AL, $0x1                        // cmp	al, 1
	JNE  LBB0_29                   // <--                                  // jne	.LBB0_29
	WORD $0xf980; BYTE $0xf0       // CMPL CL, $0xf0                       // cmp	cl, -16
	WORD $0x940f; BYTE $0xc0       // SETE AL                              // sete	al
	WORD $0xfa80; BYTE $0x90       // CMPL DL, $0x90                       // cmp	dl, -112
	LONG $0xc0930f41               // SETAE R8                             // setae	r8b
	WORD $0x2041; BYTE $0xc0       // ANDL AL, R8                          // and	r8b, al
	WORD $0x418d; BYTE $0x0f       // LEAL 0xf(CX), AX                     // lea	eax, [rcx + 15]
	WORD $0x033c                   // CMPL AL, $0x3                        // cmp	al, 3
	WORD $0x920f; BYTE $0xc0       // SETB AL                              // setb	al
	WORD $0x0844; BYTE $0xc0       // ORL R8, AL                           // or	al, r8b
	LONG $0x0004b841; WORD $0x0000 // MOVL $0x4, R8                        // mov	r8d, 4
	JNE  LBB0_14                   // <--                                  // jne	.LBB0_14
	XORL AX, AX                    // <--                                  // xor	eax, eax
	WORD $0xf980; BYTE $0xf4       // CMPL CL, $0xf4                       // cmp	cl, -12
	JNE  LBB0_7                    // <--                                  // jne	.LBB0_7
	WORD $0xfa80; BYTE $0x8f       // CMPL DL, $0x8f                       // cmp	dl, -113
	JBE  LBB0_14                   // <--                                  // jbe	.LBB0_14
	JMP  LBB0_7                    // <--                                  // jmp	.LBB0_7

LBB0_29:
	XORL AX, AX         // <--                                  // xor	eax, eax
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	VZEROUPPER          // <--                                  // vzeroupper
	MOVB AX, ret+16(FP) // <--
	RET                 // <--                                  // ret
