//go:build !noasm && arm64
// Code generated by gocc v0.16.6-0.20260113004826-b04e2010a937-rev-b04e201 -- DO NOT EDIT.
//
// Source file         : ascii_original.c
// Clang version       : Homebrew clang version 21.1.8
// Target architecture : arm64
// Compiler options    : [none]

#include "textflag.h"

DATA uppercasingTable_orig<>+0x00(SB)/8, $0x2020202020202000
DATA uppercasingTable_orig<>+0x08(SB)/8, $0x2020202020202020
DATA uppercasingTable_orig<>+0x10(SB)/8, $0x2020202020202020
DATA uppercasingTable_orig<>+0x18(SB)/8, $0x0000000000202020
GLOBL uppercasingTable_orig<>(SB), (RODATA|NOPTR), $32

TEXT ·IndexFoldOriginal(SB), NOSPLIT, $0-40
	MOVD haystack+0(FP), R0
	MOVD haystack_len+8(FP), R1
	MOVD needle+16(FP), R2
	MOVD needle_len+24(FP), R3
	NOP                         // (skipped)                            // stp	x24, x23, [sp, #-48]!
	CMP  R3, R1                 // <--                                  // cmp	x1, x3
	NOP                         // (skipped)                            // stp	x22, x21, [sp, #16]
	NOP                         // (skipped)                            // stp	x20, x19, [sp, #32]
	BGE  LBB0_3                 // <--                                  // b.ge	.LBB0_3
	MOVD $-1, R8                // <--                                  // mov	x8, #-1

LBB0_2:
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+32(FP) // <--
	RET                 // <--                                  // ret

LBB0_3:
	CMP  $1, R3                           // <--                                  // cmp	x3, #1
	BLT  LBB0_15                          // <--                                  // b.lt	.LBB0_15
	MOVD $uppercasingTable_orig<>(SB), R8 // <--                                  // adrp	x8, uppercasingTable_orig
	NOP                                   // (skipped)                            // add	x8, x8, :lo12:uppercasingTable_orig
	VLD1 (R8), [V0.B16, V1.B16]           // <--                                  // ld1	{ v0.16b, v1.16b }, [x8]
	SUBS R3, R1, R8                       // <--                                  // subs	x8, x1, x3
	BNE  LBB0_16                          // <--                                  // b.ne	.LBB0_16
	CMP  $16, R1                          // <--                                  // cmp	x1, #16
	AND  $15, R1, R8                      // <--                                  // and	x8, x1, #0xf
	BCC  LBB0_9                           // <--                                  // b.lo	.LBB0_9
	WORD $0x4f05e402                      // VMOVI $160, V2.B16                   // movi	v2.16b, #160
	ADD  R1, R0, R9                       // <--                                  // add	x9, x0, x1
	SUB  R8, R9, R9                       // <--                                  // sub	x9, x9, x8

LBB0_7:
	WORD  $0x3cc10403                      // FMOVQ.P 16(R0), F3                   // ldr	q3, [x0], #16
	WORD  $0x3cc10444                      // FMOVQ.P 16(R2), F4                   // ldr	q4, [x2], #16
	VADD  V2.B16, V3.B16, V3.B16           // <--                                  // add	v3.16b, v3.16b, v2.16b
	VADD  V2.B16, V4.B16, V4.B16           // <--                                  // add	v4.16b, v4.16b, v2.16b
	VTBL  V3.B16, [V0.B16, V1.B16], V5.B16 // <--                                  // tbl	v5.16b, { v0.16b, v1.16b }, v3.16b
	VTBL  V4.B16, [V0.B16, V1.B16], V6.B16 // <--                                  // tbl	v6.16b, { v0.16b, v1.16b }, v4.16b
	VSUB  V5.B16, V3.B16, V3.B16           // <--                                  // sub	v3.16b, v3.16b, v5.16b
	VSUB  V6.B16, V4.B16, V4.B16           // <--                                  // sub	v4.16b, v4.16b, v6.16b
	VCMEQ V4.B16, V3.B16, V3.B16           // <--                                  // cmeq	v3.16b, v3.16b, v4.16b
	WORD  $0x0f0c8463                      // VSHRN $4, V3.H8, V3.B8               // shrn	v3.8b, v3.8h, #4
	FMOVD F3, R10                          // <--                                  // fmov	x10, d3
	CMN   $1, R10                          // <--                                  // cmn	x10, #1
	BNE   LBB0_231                         // <--                                  // b.ne	.LBB0_231
	CMP   R9, R0                           // <--                                  // cmp	x0, x9
	BCC   LBB0_7                           // <--                                  // b.lo	.LBB0_7

LBB0_9:
	CMP   $8, R8                         // <--                                  // cmp	x8, #8
	BCC   LBB0_12                        // <--                                  // b.lo	.LBB0_12
	WORD  $0x0f05e402                    // VMOVI $160, V2.B8                    // movi	v2.8b, #160
	WORD  $0xfc408403                    // FMOVD.P 8(R0), F3                    // ldr	d3, [x0], #8
	WORD  $0xfc408444                    // FMOVD.P 8(R2), F4                    // ldr	d4, [x2], #8
	VADD  V2.B8, V3.B8, V3.B8            // <--                                  // add	v3.8b, v3.8b, v2.8b
	VADD  V2.B8, V4.B8, V2.B8            // <--                                  // add	v2.8b, v4.8b, v2.8b
	VTBL  V3.B8, [V0.B16, V1.B16], V4.B8 // <--                                  // tbl	v4.8b, { v0.16b, v1.16b }, v3.8b
	VTBL  V2.B8, [V0.B16, V1.B16], V5.B8 // <--                                  // tbl	v5.8b, { v0.16b, v1.16b }, v2.8b
	VSUB  V4.B8, V3.B8, V3.B8            // <--                                  // sub	v3.8b, v3.8b, v4.8b
	VSUB  V5.B8, V2.B8, V2.B8            // <--                                  // sub	v2.8b, v2.8b, v5.8b
	VCMEQ V2.B8, V3.B8, V2.B8            // <--                                  // cmeq	v2.8b, v3.8b, v2.8b
	FMOVD F2, R8                         // <--                                  // fmov	x8, d2
	CMN   $1, R8                         // <--                                  // cmn	x8, #1
	BNE   LBB0_231                       // <--                                  // b.ne	.LBB0_231
	AND   $7, R1, R8                     // <--                                  // and	x8, x1, #0x7

LBB0_12:
	CBZ  R8, LBB0_2  // <--                                  // cbz	x8, .LBB0_2
	SUBS $4, R8, R11 // <--                                  // subs	x11, x8, #4
	BCC  LBB0_99     // <--                                  // b.lo	.LBB0_99
	WORD $0xb840440a // MOVWU.P 4(R0), R10                   // ldr	w10, [x0], #4
	MOVD R11, R8     // <--                                  // mov	x8, x11
	WORD $0xb8404449 // MOVWU.P 4(R2), R9                    // ldr	w9, [x2], #4
	JMP  LBB0_100    // <--                                  // b	.LBB0_100

LBB0_15:
	MOVD ZR, R8         // <--                                  // mov	x8, xzr
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+32(FP) // <--
	RET                 // <--                                  // ret

LBB0_16:
	CMP   $2, R3          // <--                                  // cmp	x3, #2
	BEQ   LBB0_25         // <--                                  // b.eq	.LBB0_25
	CMP   $1, R3          // <--                                  // cmp	x3, #1
	BNE   LBB0_51         // <--                                  // b.ne	.LBB0_51
	WORD  $0x39400048     // MOVBU (R2), R8                       // ldrb	w8, [x2]
	SUBW  $97, R8, R9     // <--                                  // sub	w9, w8, #97
	SUBW  $32, R8, R10    // <--                                  // sub	w10, w8, #32
	CMPW  $26, R9         // <--                                  // cmp	w9, #26
	MOVD  R0, R9          // <--                                  // mov	x9, x0
	CSELW LO, R10, R8, R8 // <--                                  // csel	w8, w10, w8, lo
	CMP   $16, R1         // <--                                  // cmp	x1, #16
	SUBW  $96, R8, R8     // <--                                  // sub	w8, w8, #96
	VDUP  R8, V2.B16      // <--                                  // dup	v2.16b, w8
	AND   $15, R1, R8     // <--                                  // and	x8, x1, #0xf
	BLT   LBB0_22         // <--                                  // b.lt	.LBB0_22
	WORD  $0x4f05e403     // VMOVI $160, V3.B16                   // movi	v3.16b, #160
	ADD   R1, R0, R9      // <--                                  // add	x9, x0, x1
	MOVD  ZR, R10         // <--                                  // mov	x10, xzr
	SUB   R8, R9, R11     // <--                                  // sub	x11, x9, x8

LBB0_20:
	WORD  $0x3cea6804                      // FMOVQ (R0)(R10), F4                  // ldr	q4, [x0, x10]
	VADD  V3.B16, V4.B16, V4.B16           // <--                                  // add	v4.16b, v4.16b, v3.16b
	VTBL  V4.B16, [V0.B16, V1.B16], V5.B16 // <--                                  // tbl	v5.16b, { v0.16b, v1.16b }, v4.16b
	VSUB  V5.B16, V4.B16, V4.B16           // <--                                  // sub	v4.16b, v4.16b, v5.16b
	VCMEQ V2.B16, V4.B16, V4.B16           // <--                                  // cmeq	v4.16b, v4.16b, v2.16b
	WORD  $0x0f0c8484                      // VSHRN $4, V4.H8, V4.B8               // shrn	v4.8b, v4.8h, #4
	FMOVD F4, R9                           // <--                                  // fmov	x9, d4
	CBNZ  R9, LBB0_173                     // <--                                  // cbnz	x9, .LBB0_173
	ADD   $16, R10, R10                    // <--                                  // add	x10, x10, #16
	ADD   R10, R0, R9                      // <--                                  // add	x9, x0, x10
	CMP   R11, R9                          // <--                                  // cmp	x9, x11
	BCC   LBB0_20                          // <--                                  // b.lo	.LBB0_20

LBB0_22:
	CBZ  R8, LBB0_231 // <--                                  // cbz	x8, .LBB0_231
	SUBS $8, R8, R11  // <--                                  // subs	x11, x8, #8
	BNE  LBB0_175     // <--                                  // b.ne	.LBB0_175
	WORD $0xfd400123  // FMOVD (R9), F3                       // ldr	d3, [x9]
	JMP  LBB0_195     // <--                                  // b	.LBB0_195

LBB0_25:
	ADD  R1, R0, R8                       // <--                                  // add	x8, x0, x1
	SUB  $1, R8, R9                       // <--                                  // sub	x9, x8, #1
	CMP  R9, R0                           // <--                                  // cmp	x0, x9
	BHI  LBB0_231                         // <--                                  // b.hi	.LBB0_231
	WORD $0x4f05e402                      // VMOVI $160, V2.B16                   // movi	v2.16b, #160
	WORD $0x4d40c443                      // VLD1R (R2), [V3.H8]                  // ld1r	{ v3.8h }, [x2]
	WORD $0x6f00e405                      // VMOVI $0, V5.D2                      // movi	v5.2d, #0000000000000000
	LSL  $3, R1, R11                      // <--                                  // lsl	x11, x1, #3
	MOVD ZR, R10                          // <--                                  // mov	x10, xzr
	SUB  $8, R1, R12                      // <--                                  // sub	x12, x1, #8
	MOVD R1, R15                          // <--                                  // mov	x15, x1
	MOVD R0, R13                          // <--                                  // mov	x13, x0
	VADD V2.B16, V3.B16, V4.B16           // <--                                  // add	v4.16b, v3.16b, v2.16b
	WORD $0x4f078603                      // VMOVI $240, V3.H8                    // movi	v3.8h, #240
	VTBL V4.B16, [V0.B16, V1.B16], V6.B16 // <--                                  // tbl	v6.16b, { v0.16b, v1.16b }, v4.16b
	VSUB V6.B16, V4.B16, V4.B16           // <--                                  // sub	v4.16b, v4.16b, v6.16b

LBB0_27:
	SUBS $16, R15, R14 // <--                                  // subs	x14, x15, #16
	ADD  R10, R0, R16  // <--                                  // add	x16, x0, x10
	BLT  LBB0_29       // <--                                  // b.lt	.LBB0_29
	WORD $0x3dc00206   // FMOVQ (R16), F6                      // ldr	q6, [x16]
	JMP  LBB0_49       // <--                                  // b	.LBB0_49

LBB0_29:
	CMP  R10, R12    // <--                                  // cmp	x12, x10
	BNE  LBB0_31     // <--                                  // b.ne	.LBB0_31
	WORD $0xfd400206 // FMOVD (R16), F6                      // ldr	d6, [x16]
	JMP  LBB0_49     // <--                                  // b	.LBB0_49

LBB0_31:
	CMP  $1, R15         // <--                                  // cmp	x15, #1
	BLT  LBB0_35         // <--                                  // b.lt	.LBB0_35
	TBNZ $3, R1, LBB0_36 // <--                                  // tbnz	w1, #3, .LBB0_36
	MOVD R15, R2         // <--                                  // mov	x2, x15
	TBZ  $2, R2, LBB0_37 // <--                                  // tbz	w2, #2, .LBB0_37

LBB0_34:
	WORD $0xb8404611 // MOVWU.P 4(R16), R17                  // ldr	w17, [x16], #4
	SUB  $4, R2, R2  // <--                                  // sub	x2, x2, #4
	JMP  LBB0_38     // <--                                  // b	.LBB0_38

LBB0_35:
	WORD $0x6f00e406 // VMOVI $0, V6.D2                      // movi	v6.2d, #0000000000000000
	JMP  LBB0_49     // <--                                  // b	.LBB0_49

LBB0_36:
	SUB  R10, R1, R17    // <--                                  // sub	x17, x1, x10
	WORD $0xf9400208     // MOVD (R16), R8                       // ldr	x8, [x16]
	ADD  $8, R13, R16    // <--                                  // add	x16, x13, #8
	SUB  $8, R17, R2     // <--                                  // sub	x2, x17, #8
	TBNZ $2, R2, LBB0_34 // <--                                  // tbnz	w2, #2, .LBB0_34

LBB0_37:
	MOVD ZR, R17 // <--                                  // mov	x17, xzr

LBB0_38:
	CMP  $1, R2       // <--                                  // cmp	x2, #1
	BEQ  LBB0_43      // <--                                  // b.eq	.LBB0_43
	CMP  $2, R2       // <--                                  // cmp	x2, #2
	BEQ  LBB0_42      // <--                                  // b.eq	.LBB0_42
	CMP  $3, R2       // <--                                  // cmp	x2, #3
	BNE  LBB0_46      // <--                                  // b.ne	.LBB0_46
	WORD $0x79400202  // MOVHU (R16), R2                      // ldrh	w2, [x16]
	ANDW $32, R11, R3 // <--                                  // and	w3, w11, #0x20
	WORD $0x39400a10  // MOVBU 2(R16), R16                    // ldrb	w16, [x16, #2]
	ORRW $16, R3, R4  // <--                                  // orr	w4, w3, #0x10
	LSL  R3, R2, R2   // <--                                  // lsl	x2, x2, x3
	LSL  R4, R16, R16 // <--                                  // lsl	x16, x16, x4
	ORR  R16, R2, R16 // <--                                  // orr	x16, x2, x16
	JMP  LBB0_45      // <--                                  // b	.LBB0_45

LBB0_42:
	WORD $0x79400210 // MOVHU (R16), R16                     // ldrh	w16, [x16]
	JMP  LBB0_44     // <--                                  // b	.LBB0_44

LBB0_43:
	WORD $0x39400210 // MOVBU (R16), R16                     // ldrb	w16, [x16]

LBB0_44:
	AND $32, R11, R2 // <--                                  // and	x2, x11, #0x20
	LSL R2, R16, R16 // <--                                  // lsl	x16, x16, x2

LBB0_45:
	ORR R17, R16, R17 // <--                                  // orr	x17, x16, x17

LBB0_46:
	CMP  $7, R15      // <--                                  // cmp	x15, #7
	BHI  LBB0_48      // <--                                  // b.hi	.LBB0_48
	WORD $0x6f00e406  // VMOVI $0, V6.D2                      // movi	v6.2d, #0000000000000000
	VMOV R17, V6.D[0] // <--                                  // mov	v6.d[0], x17
	JMP  LBB0_49      // <--                                  // b	.LBB0_49

LBB0_48:
	FMOVD R8, F6       // <--                                  // fmov	d6, x8
	VMOV  R17, V6.D[1] // <--                                  // mov	v6.d[1], x17

LBB0_49:
	VADD  V2.B16, V6.B16, V6.B16           // <--                                  // add	v6.16b, v6.16b, v2.16b
	CMP   $0, R10                          // <--                                  // cmp	x10, #0
	VTBL  V6.B16, [V0.B16, V1.B16], V7.B16 // <--                                  // tbl	v7.16b, { v0.16b, v1.16b }, v6.16b
	VSUB  V7.B16, V6.B16, V6.B16           // <--                                  // sub	v6.16b, v6.16b, v7.16b
	VEXT  $15, V6.B16, V5.B16, V5.B16      // <--                                  // ext	v5.16b, v5.16b, v6.16b, #15
	VCMEQ V4.H8, V6.H8, V7.H8              // <--                                  // cmeq	v7.8h, v6.8h, v4.8h
	VSHL  $8, V7.H8, V7.H8                 // <--                                  // shl	v7.8h, v7.8h, #8
	VCMEQ V4.H8, V5.H8, V5.H8              // <--                                  // cmeq	v5.8h, v5.8h, v4.8h
	VAND  V3.B16, V5.B16, V5.B16           // <--                                  // and	v5.16b, v5.16b, v3.16b
	VORR  V5.B16, V7.B16, V5.B16           // <--                                  // orr	v5.16b, v7.16b, v5.16b
	WORD  $0x0f0c84a5                      // VSHRN $4, V5.H8, V5.B8               // shrn	v5.8b, v5.8h, #4
	FMOVD F5, R8                           // <--                                  // fmov	x8, d5
	AND   $-16, R8, R15                    // <--                                  // and	x15, x8, #0xfffffffffffffff0
	CSEL  EQ, R15, R8, R8                  // <--                                  // csel	x8, x15, x8, eq
	CBNZ  R8, LBB0_174                     // <--                                  // cbnz	x8, .LBB0_174
	ADD   $16, R10, R10                    // <--                                  // add	x10, x10, #16
	VMOV  V6.B16, V5.B16                   // <--                                  // mov	v5.16b, v6.16b
	ADD   $16, R13, R13                    // <--                                  // add	x13, x13, #16
	ADD   R10, R0, R8                      // <--                                  // add	x8, x0, x10
	SUB   $128, R11, R11                   // <--                                  // sub	x11, x11, #128
	MOVD  R14, R15                         // <--                                  // mov	x15, x14
	CMP   R9, R8                           // <--                                  // cmp	x8, x9
	MOVD  $-1, R8                          // <--                                  // mov	x8, #-1
	BLS   LBB0_27                          // <--                                  // b.ls	.LBB0_27
	JMP   LBB0_2                           // <--                                  // b	.LBB0_2

LBB0_51:
	MOVD R2, R9                           // <--                                  // mov	x9, x2
	WORD $0x4f05e406                      // VMOVI $160, V6.B16                   // movi	v6.16b, #160
	SUB  $16, R1, R10                     // <--                                  // sub	x10, x1, #16
	WORD $0x4dc3c522                      // VLD1R (R9)(R3), [V2.H8]              // ld1r	{ v2.8h }, [x9], x3
	SUB  $2, R9, R9                       // <--                                  // sub	x9, x9, #2
	WORD $0x4d40c523                      // VLD1R (R9), [V3.H8]                  // ld1r	{ v3.8h }, [x9]
	AND  $-16, R8, R9                     // <--                                  // and	x9, x8, #0xfffffffffffffff0
	VADD V6.B16, V2.B16, V2.B16           // <--                                  // add	v2.16b, v2.16b, v6.16b
	CMP  R10, R9                          // <--                                  // cmp	x9, x10
	CSEL LO, R9, R10, R9                  // <--                                  // csel	x9, x9, x10, lo
	VADD V6.B16, V3.B16, V3.B16           // <--                                  // add	v3.16b, v3.16b, v6.16b
	VTBL V2.B16, [V0.B16, V1.B16], V4.B16 // <--                                  // tbl	v4.16b, { v0.16b, v1.16b }, v2.16b
	VTBL V3.B16, [V0.B16, V1.B16], V5.B16 // <--                                  // tbl	v5.16b, { v0.16b, v1.16b }, v3.16b
	VSUB V4.B16, V2.B16, V2.B16           // <--                                  // sub	v2.16b, v2.16b, v4.16b
	VSUB V5.B16, V3.B16, V3.B16           // <--                                  // sub	v3.16b, v3.16b, v5.16b
	CBZ  R9, LBB0_104                     // <--                                  // cbz	x9, .LBB0_104
	SUBS $4, R3, R10                      // <--                                  // subs	x10, x3, #4
	WORD $0x6f00e404                      // VMOVI $0, V4.D2                      // movi	v4.2d, #0000000000000000
	WORD $0x4f078607                      // VMOVI $240, V7.H8                    // movi	v7.8h, #240
	CSEL LO, ZR, R10, R10                 // <--                                  // csel	x10, xzr, x10, lo
	WORD $0x0f05e410                      // VMOVI $160, V16.B8                   // movi	v16.8b, #160
	WORD $0x6f00e405                      // VMOVI $0, V5.D2                      // movi	v5.2d, #0000000000000000
	AND  $15, R10, R13                    // <--                                  // and	x13, x10, #0xf
	ADD  R9, R0, R12                      // <--                                  // add	x12, x0, x9
	MOVD ZR, R11                          // <--                                  // mov	x11, xzr
	NEG  R13, R9                          // <--                                  // neg	x9, x13
	ADD  $2, R2, R14                      // <--                                  // add	x14, x2, #2
	AND  $7, R10, R15                     // <--                                  // and	x15, x10, #0x7
	MOVW $15, R16                         // <--                                  // mov	w16, #15
	ADD  R9, R10, R17                     // <--                                  // add	x17, x10, x9
	MOVD R0, R9                           // <--                                  // mov	x9, x0
	JMP  LBB0_54                          // <--                                  // b	.LBB0_54

LBB0_53:
	ADD $16, R9, R9 // <--                                  // add	x9, x9, #16
	CMP R12, R9     // <--                                  // cmp	x9, x12
	BCS LBB0_105    // <--                                  // b.hs	.LBB0_105

LBB0_54:
	ADD   R3, R9, R10                        // <--                                  // add	x10, x9, x3
	WORD  $0x3dc00131                        // FMOVQ (R9), F17                      // ldr	q17, [x9]
	VMOV  V5.B16, V21.B16                    // <--                                  // mov	v21.16b, v5.16b
	WORD  $0x3cdfe152                        // FMOVQ -2(R10), F18                   // ldur	q18, [x10, #-2]
	VMOV  V4.B16, V22.B16                    // <--                                  // mov	v22.16b, v4.16b
	VADD  V6.B16, V17.B16, V17.B16           // <--                                  // add	v17.16b, v17.16b, v6.16b
	VADD  V6.B16, V18.B16, V18.B16           // <--                                  // add	v18.16b, v18.16b, v6.16b
	VTBL  V17.B16, [V0.B16, V1.B16], V19.B16 // <--                                  // tbl	v19.16b, { v0.16b, v1.16b }, v17.16b
	VTBL  V18.B16, [V0.B16, V1.B16], V20.B16 // <--                                  // tbl	v20.16b, { v0.16b, v1.16b }, v18.16b
	VSUB  V19.B16, V17.B16, V5.B16           // <--                                  // sub	v5.16b, v17.16b, v19.16b
	VSUB  V20.B16, V18.B16, V4.B16           // <--                                  // sub	v4.16b, v18.16b, v20.16b
	VEXT  $15, V5.B16, V21.B16, V17.B16      // <--                                  // ext	v17.16b, v21.16b, v5.16b, #15
	VCMEQ V5.H8, V2.H8, V19.H8               // <--                                  // cmeq	v19.8h, v2.8h, v5.8h
	VEXT  $15, V4.B16, V22.B16, V18.B16      // <--                                  // ext	v18.16b, v22.16b, v4.16b, #15
	VCMEQ V4.H8, V3.H8, V20.H8               // <--                                  // cmeq	v20.8h, v3.8h, v4.8h
	VCMEQ V17.H8, V2.H8, V17.H8              // <--                                  // cmeq	v17.8h, v2.8h, v17.8h
	VAND  V20.B16, V19.B16, V19.B16          // <--                                  // and	v19.16b, v19.16b, v20.16b
	VCMEQ V18.H8, V3.H8, V18.H8              // <--                                  // cmeq	v18.8h, v3.8h, v18.8h
	VAND  V18.B16, V17.B16, V17.B16          // <--                                  // and	v17.16b, v17.16b, v18.16b
	VSHL  $8, V19.H8, V18.H8                 // <--                                  // shl	v18.8h, v19.8h, #8
	VAND  V7.B16, V17.B16, V17.B16           // <--                                  // and	v17.16b, v17.16b, v7.16b
	VORR  V18.B16, V17.B16, V17.B16          // <--                                  // orr	v17.16b, v17.16b, v18.16b
	WORD  $0x0f0c8631                        // VSHRN $4, V17.H8, V17.B8             // shrn	v17.8b, v17.8h, #4
	FMOVD F17, R10                           // <--                                  // fmov	x10, d17
	CBZ   R10, LBB0_53                       // <--                                  // cbz	x10, .LBB0_53
	ADD   $2, R9, R4                         // <--                                  // add	x4, x9, #2
	JMP   LBB0_60                            // <--                                  // b	.LBB0_60

LBB0_56:
	WORD $0x79400294       // MOVHU (R20), R20                     // ldrh	w20, [x20]
	WORD $0x79400273       // MOVHU (R19), R19                     // ldrh	w19, [x19]
	ORR  R22<<16, R20, R22 // <--                                  // orr	x22, x20, x22, lsl #16
	ORR  R21<<16, R19, R21 // <--                                  // orr	x21, x19, x21, lsl #16

LBB0_57:
	FMOVD R22, F17                         // <--                                  // fmov	d17, x22
	FMOVD R21, F18                         // <--                                  // fmov	d18, x21
	VADD  V16.B8, V17.B8, V17.B8           // <--                                  // add	v17.8b, v17.8b, v16.8b
	VADD  V16.B8, V18.B8, V18.B8           // <--                                  // add	v18.8b, v18.8b, v16.8b
	VTBL  V17.B8, [V0.B16, V1.B16], V19.B8 // <--                                  // tbl	v19.8b, { v0.16b, v1.16b }, v17.8b
	VTBL  V18.B8, [V0.B16, V1.B16], V20.B8 // <--                                  // tbl	v20.8b, { v0.16b, v1.16b }, v18.8b
	VSUB  V19.B8, V17.B8, V17.B8           // <--                                  // sub	v17.8b, v17.8b, v19.8b
	VSUB  V20.B8, V18.B8, V18.B8           // <--                                  // sub	v18.8b, v18.8b, v20.8b
	VCMEQ V18.B8, V17.B8, V17.B8           // <--                                  // cmeq	v17.8b, v17.8b, v18.8b
	FMOVD F17, R19                         // <--                                  // fmov	x19, d17
	CMN   $1, R19                          // <--                                  // cmn	x19, #1
	BEQ   LBB0_98                          // <--                                  // b.eq	.LBB0_98

LBB0_58:
	ADD $1, R11, R11 // <--                                  // add	x11, x11, #1

LBB0_59:
	AND $60, R6, R6  // <--                                  // and	x6, x6, #0x3c
	LSL R6, R16, R6  // <--                                  // lsl	x6, x16, x6
	BIC R6, R10, R10 // <--                                  // bic	x10, x10, x6
	CBZ R10, LBB0_79 // <--                                  // cbz	x10, .LBB0_79

LBB0_60:
	RBIT R10, R6    // <--                                  // rbit	x6, x10
	SUBS R0, R9, R5 // <--                                  // subs	x5, x9, x0
	CLZ  R6, R6     // <--                                  // clz	x6, x6
	BNE  LBB0_62    // <--                                  // b.ne	.LBB0_62
	CMP  $4, R6     // <--                                  // cmp	x6, #4
	BCC  LBB0_59    // <--                                  // b.lo	.LBB0_59

LBB0_62:
	LSRW $2, R6, R7  // <--                                  // lsr	w7, w6, #2
	CMP  $20, R3     // <--                                  // cmp	x3, #20
	SUBW $1, R7, R7  // <--                                  // sub	w7, w7, #1
	SXTW R7, R7      // <--                                  // sxtw	x7, w7
	ADD  R7, R4, R20 // <--                                  // add	x20, x4, x7
	BCS  LBB0_64     // <--                                  // b.hs	.LBB0_64
	MOVD R14, R19    // <--                                  // mov	x19, x14
	JMP  LBB0_67     // <--                                  // b	.LBB0_67

LBB0_64:
	ADD  R17, R20, R21 // <--                                  // add	x21, x20, x17
	MOVD R14, R19      // <--                                  // mov	x19, x14

LBB0_65:
	WORD  $0x3cc10691                        // FMOVQ.P 16(R20), F17                 // ldr	q17, [x20], #16
	WORD  $0x3cc10672                        // FMOVQ.P 16(R19), F18                 // ldr	q18, [x19], #16
	VADD  V6.B16, V17.B16, V17.B16           // <--                                  // add	v17.16b, v17.16b, v6.16b
	VADD  V6.B16, V18.B16, V18.B16           // <--                                  // add	v18.16b, v18.16b, v6.16b
	VTBL  V17.B16, [V0.B16, V1.B16], V19.B16 // <--                                  // tbl	v19.16b, { v0.16b, v1.16b }, v17.16b
	VTBL  V18.B16, [V0.B16, V1.B16], V20.B16 // <--                                  // tbl	v20.16b, { v0.16b, v1.16b }, v18.16b
	VSUB  V19.B16, V17.B16, V17.B16          // <--                                  // sub	v17.16b, v17.16b, v19.16b
	VSUB  V20.B16, V18.B16, V18.B16          // <--                                  // sub	v18.16b, v18.16b, v20.16b
	VCMEQ V18.B16, V17.B16, V17.B16          // <--                                  // cmeq	v17.16b, v17.16b, v18.16b
	WORD  $0x0f0c8631                        // VSHRN $4, V17.H8, V17.B8             // shrn	v17.8b, v17.8h, #4
	FMOVD F17, R22                           // <--                                  // fmov	x22, d17
	CMN   $1, R22                            // <--                                  // cmn	x22, #1
	BNE   LBB0_58                            // <--                                  // b.ne	.LBB0_58
	CMP   R21, R20                           // <--                                  // cmp	x20, x21
	BCC   LBB0_65                            // <--                                  // b.lo	.LBB0_65

LBB0_67:
	CMP   $8, R13                          // <--                                  // cmp	x13, #8
	BCC   LBB0_70                          // <--                                  // b.lo	.LBB0_70
	WORD  $0xfc408691                      // FMOVD.P 8(R20), F17                  // ldr	d17, [x20], #8
	WORD  $0xfc408672                      // FMOVD.P 8(R19), F18                  // ldr	d18, [x19], #8
	VADD  V16.B8, V17.B8, V17.B8           // <--                                  // add	v17.8b, v17.8b, v16.8b
	VADD  V16.B8, V18.B8, V18.B8           // <--                                  // add	v18.8b, v18.8b, v16.8b
	VTBL  V17.B8, [V0.B16, V1.B16], V19.B8 // <--                                  // tbl	v19.8b, { v0.16b, v1.16b }, v17.8b
	VTBL  V18.B8, [V0.B16, V1.B16], V20.B8 // <--                                  // tbl	v20.8b, { v0.16b, v1.16b }, v18.8b
	VSUB  V19.B8, V17.B8, V17.B8           // <--                                  // sub	v17.8b, v17.8b, v19.8b
	VSUB  V20.B8, V18.B8, V18.B8           // <--                                  // sub	v18.8b, v18.8b, v20.8b
	VCMEQ V18.B8, V17.B8, V17.B8           // <--                                  // cmeq	v17.8b, v17.8b, v18.8b
	FMOVD F17, R21                         // <--                                  // fmov	x21, d17
	CMN   $1, R21                          // <--                                  // cmn	x21, #1
	BNE   LBB0_58                          // <--                                  // b.ne	.LBB0_58
	MOVD  R15, R23                         // <--                                  // mov	x23, x15
	JMP   LBB0_71                          // <--                                  // b	.LBB0_71

LBB0_70:
	MOVD R13, R23 // <--                                  // mov	x23, x13

LBB0_71:
	CBZ  R23, LBB0_98 // <--                                  // cbz	x23, .LBB0_98
	SUBS $4, R23, R24 // <--                                  // subs	x24, x23, #4
	BCC  LBB0_77      // <--                                  // b.lo	.LBB0_77
	WORD $0xb8404696  // MOVWU.P 4(R20), R22                  // ldr	w22, [x20], #4
	MOVD R24, R23     // <--                                  // mov	x23, x24
	WORD $0xb8404675  // MOVWU.P 4(R19), R21                  // ldr	w21, [x19], #4
	CMP  $1, R24      // <--                                  // cmp	x24, #1
	BEQ  LBB0_78      // <--                                  // b.eq	.LBB0_78

LBB0_74:
	CMP  $2, R23          // <--                                  // cmp	x23, #2
	BEQ  LBB0_56          // <--                                  // b.eq	.LBB0_56
	CMP  $3, R23          // <--                                  // cmp	x23, #3
	BNE  LBB0_57          // <--                                  // b.ne	.LBB0_57
	LSL  $24, R22, R22    // <--                                  // lsl	x22, x22, #24
	WORD $0x79400297      // MOVHU (R20), R23                     // ldrh	w23, [x20]
	LSL  $24, R21, R21    // <--                                  // lsl	x21, x21, #24
	WORD $0x79400278      // MOVHU (R19), R24                     // ldrh	w24, [x19]
	WORD $0x39400a94      // MOVBU 2(R20), R20                    // ldrb	w20, [x20, #2]
	WORD $0x39400a73      // MOVBU 2(R19), R19                    // ldrb	w19, [x19, #2]
	ORR  R23<<8, R22, R22 // <--                                  // orr	x22, x22, x23, lsl #8
	ORR  R24<<8, R21, R21 // <--                                  // orr	x21, x21, x24, lsl #8
	ORR  R20, R22, R22    // <--                                  // orr	x22, x22, x20
	ORR  R19, R21, R21    // <--                                  // orr	x21, x21, x19
	JMP  LBB0_57          // <--                                  // b	.LBB0_57

LBB0_77:
	MOVD ZR, R21 // <--                                  // mov	x21, xzr
	MOVD ZR, R22 // <--                                  // mov	x22, xzr
	CMP  $1, R23 // <--                                  // cmp	x23, #1
	BNE  LBB0_74 // <--                                  // b.ne	.LBB0_74

LBB0_78:
	WORD $0x39400294      // MOVBU (R20), R20                     // ldrb	w20, [x20]
	WORD $0x39400273      // MOVBU (R19), R19                     // ldrb	w19, [x19]
	ORR  R22<<8, R20, R22 // <--                                  // orr	x22, x20, x22, lsl #8
	ORR  R21<<8, R19, R21 // <--                                  // orr	x21, x19, x21, lsl #8
	JMP  LBB0_57          // <--                                  // b	.LBB0_57

LBB0_79:
	ADD   $15, R5, R10    // <--                                  // add	x10, x5, #15
	LSR   $4, R10, R10    // <--                                  // lsr	x10, x10, #4
	ADD   $4, R10, R10    // <--                                  // add	x10, x10, #4
	CMP   R10, R11        // <--                                  // cmp	x11, x10
	BLS   LBB0_53         // <--                                  // b.ls	.LBB0_53
	ADD   $15, R9, R10    // <--                                  // add	x10, x9, #15
	CMP   R12, R10        // <--                                  // cmp	x10, x12
	BCS   LBB0_53         // <--                                  // b.hs	.LBB0_53
	MOVW  $403, R11       // <--                                  // mov	w11, #403
	MOVD  ZR, R8          // <--                                  // mov	x8, xzr
	MOVW  ZR, R12         // <--                                  // mov	w12, wzr
	MOVKW $(256<<16), R11 // <--                                  // movk	w11, #256, lsl #16

LBB0_82:
	WORD  $0x3868684d        // MOVBU (R2)(R8), R13                  // ldrb	w13, [x2, x8]
	MULW  R11, R12, R12      // <--                                  // mul	w12, w12, w11
	ADD   $1, R8, R8         // <--                                  // add	x8, x8, #1
	SUBW  $97, R13, R14      // <--                                  // sub	w14, w13, #97
	ORRW  $128, R13, R15     // <--                                  // orr	w15, w13, #0x80
	SUBW  $96, R13, R13      // <--                                  // sub	w13, w13, #96
	CMPW  $26, R14           // <--                                  // cmp	w14, #26
	CSELW LO, R15, R13, R13  // <--                                  // csel	w13, w15, w13, lo
	CMP   R8, R3             // <--                                  // cmp	x3, x8
	ADDW  R13.UXTB, R12, R12 // <--                                  // add	w12, w12, w13, uxtb
	BNE   LBB0_82            // <--                                  // b.ne	.LBB0_82
	MOVW  $403, R14          // <--                                  // mov	w14, #403
	MOVW  $1, R13            // <--                                  // mov	w13, #1
	MOVD  R3, R8             // <--                                  // mov	x8, x3
	MOVKW $(256<<16), R14    // <--                                  // movk	w14, #256, lsl #16

LBB0_84:
	TST    $1, R8           // <--                                  // tst	x8, #0x1
	CSINCW NE, R14, ZR, R15 // <--                                  // csinc	w15, w14, wzr, ne
	MULW   R14, R14, R14    // <--                                  // mul	w14, w14, w14
	CMP    $1, R8           // <--                                  // cmp	x8, #1
	MULW   R13, R15, R13    // <--                                  // mul	w13, w15, w13
	LSR    $1, R8, R15      // <--                                  // lsr	x15, x8, #1
	MOVD   R15, R8          // <--                                  // mov	x8, x15
	BHI    LBB0_84          // <--                                  // b.hi	.LBB0_84
	MOVD   ZR, R8           // <--                                  // mov	x8, xzr
	MOVW   ZR, R14          // <--                                  // mov	w14, wzr

LBB0_86:
	ADD   R8, R9, R15        // <--                                  // add	x15, x9, x8
	MULW  R11, R14, R14      // <--                                  // mul	w14, w14, w11
	ADD   $1, R8, R8         // <--                                  // add	x8, x8, #1
	WORD  $0x39403def        // MOVBU 15(R15), R15                   // ldrb	w15, [x15, #15]
	SUBW  $97, R15, R16      // <--                                  // sub	w16, w15, #97
	ORRW  $128, R15, R17     // <--                                  // orr	w17, w15, #0x80
	SUBW  $96, R15, R15      // <--                                  // sub	w15, w15, #96
	CMPW  $26, R16           // <--                                  // cmp	w16, #26
	CSELW LO, R17, R15, R15  // <--                                  // csel	w15, w17, w15, lo
	CMP   R8, R3             // <--                                  // cmp	x3, x8
	ADDW  R15.UXTB, R14, R14 // <--                                  // add	w14, w14, w15, uxtb
	BNE   LBB0_86            // <--                                  // b.ne	.LBB0_86
	CMPW  R12, R14           // <--                                  // cmp	w14, w12
	SUB   R0, R10, R8        // <--                                  // sub	x8, x10, x0
	BNE   LBB0_205           // <--                                  // b.ne	.LBB0_205
	CMP   $16, R3            // <--                                  // cmp	x3, #16
	AND   $15, R3, R16       // <--                                  // and	x16, x3, #0xf
	MOVD  R2, R9             // <--                                  // mov	x9, x2
	MOVD  R10, R15           // <--                                  // mov	x15, x10
	BCC   LBB0_92            // <--                                  // b.lo	.LBB0_92
	WORD  $0x4f05e402        // VMOVI $160, V2.B16                   // movi	v2.16b, #160
	ADD   R3, R10, R9        // <--                                  // add	x9, x10, x3
	MOVD  R10, R15           // <--                                  // mov	x15, x10
	SUB   R16, R9, R17       // <--                                  // sub	x17, x9, x16
	MOVD  R2, R9             // <--                                  // mov	x9, x2

LBB0_90:
	WORD  $0x3cc105e3                      // FMOVQ.P 16(R15), F3                  // ldr	q3, [x15], #16
	WORD  $0x3cc10524                      // FMOVQ.P 16(R9), F4                   // ldr	q4, [x9], #16
	VADD  V2.B16, V3.B16, V3.B16           // <--                                  // add	v3.16b, v3.16b, v2.16b
	VADD  V2.B16, V4.B16, V4.B16           // <--                                  // add	v4.16b, v4.16b, v2.16b
	VTBL  V3.B16, [V0.B16, V1.B16], V5.B16 // <--                                  // tbl	v5.16b, { v0.16b, v1.16b }, v3.16b
	VTBL  V4.B16, [V0.B16, V1.B16], V6.B16 // <--                                  // tbl	v6.16b, { v0.16b, v1.16b }, v4.16b
	VSUB  V5.B16, V3.B16, V3.B16           // <--                                  // sub	v3.16b, v3.16b, v5.16b
	VSUB  V6.B16, V4.B16, V4.B16           // <--                                  // sub	v4.16b, v4.16b, v6.16b
	VCMEQ V4.B16, V3.B16, V3.B16           // <--                                  // cmeq	v3.16b, v3.16b, v4.16b
	WORD  $0x0f0c8463                      // VSHRN $4, V3.H8, V3.B8               // shrn	v3.8b, v3.8h, #4
	FMOVD F3, R0                           // <--                                  // fmov	x0, d3
	CMN   $1, R0                           // <--                                  // cmn	x0, #1
	BNE   LBB0_205                         // <--                                  // b.ne	.LBB0_205
	CMP   R17, R15                         // <--                                  // cmp	x15, x17
	BCC   LBB0_90                          // <--                                  // b.lo	.LBB0_90

LBB0_92:
	CMP   $8, R16                        // <--                                  // cmp	x16, #8
	BCC   LBB0_95                        // <--                                  // b.lo	.LBB0_95
	WORD  $0x0f05e402                    // VMOVI $160, V2.B8                    // movi	v2.8b, #160
	WORD  $0xfc4085e3                    // FMOVD.P 8(R15), F3                   // ldr	d3, [x15], #8
	WORD  $0xfc408524                    // FMOVD.P 8(R9), F4                    // ldr	d4, [x9], #8
	VADD  V2.B8, V3.B8, V3.B8            // <--                                  // add	v3.8b, v3.8b, v2.8b
	VADD  V2.B8, V4.B8, V2.B8            // <--                                  // add	v2.8b, v4.8b, v2.8b
	VTBL  V3.B8, [V0.B16, V1.B16], V4.B8 // <--                                  // tbl	v4.8b, { v0.16b, v1.16b }, v3.8b
	VTBL  V2.B8, [V0.B16, V1.B16], V5.B8 // <--                                  // tbl	v5.8b, { v0.16b, v1.16b }, v2.8b
	VSUB  V4.B8, V3.B8, V3.B8            // <--                                  // sub	v3.8b, v3.8b, v4.8b
	VSUB  V5.B8, V2.B8, V2.B8            // <--                                  // sub	v2.8b, v2.8b, v5.8b
	VCMEQ V2.B8, V3.B8, V2.B8            // <--                                  // cmeq	v2.8b, v3.8b, v2.8b
	FMOVD F2, R16                        // <--                                  // fmov	x16, d2
	CMN   $1, R16                        // <--                                  // cmn	x16, #1
	BNE   LBB0_205                       // <--                                  // b.ne	.LBB0_205
	AND   $7, R3, R16                    // <--                                  // and	x16, x3, #0x7

LBB0_95:
	CBZ  R16, LBB0_2 // <--                                  // cbz	x16, .LBB0_2
	SUBS $4, R16, R4 // <--                                  // subs	x4, x16, #4
	BCC  LBB0_197    // <--                                  // b.lo	.LBB0_197
	WORD $0xb84045e0 // MOVWU.P 4(R15), R0                   // ldr	w0, [x15], #4
	MOVD R4, R16     // <--                                  // mov	x16, x4
	WORD $0xb8404531 // MOVWU.P 4(R9), R17                   // ldr	w17, [x9], #4
	JMP  LBB0_198    // <--                                  // b	.LBB0_198

LBB0_98:
	ADD  R7, R5, R8     // <--                                  // add	x8, x5, x7
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+32(FP) // <--
	RET                 // <--                                  // ret

LBB0_99:
	MOVD ZR, R9  // <--                                  // mov	x9, xzr
	MOVD ZR, R10 // <--                                  // mov	x10, xzr

LBB0_100:
	CMP  $1, R8         // <--                                  // cmp	x8, #1
	BEQ  LBB0_180       // <--                                  // b.eq	.LBB0_180
	CMP  $2, R8         // <--                                  // cmp	x8, #2
	BEQ  LBB0_179       // <--                                  // b.eq	.LBB0_179
	CMP  $3, R8         // <--                                  // cmp	x8, #3
	BNE  LBB0_181       // <--                                  // b.ne	.LBB0_181
	LSL  $24, R10, R8   // <--                                  // lsl	x8, x10, #24
	WORD $0x7940000a    // MOVHU (R0), R10                      // ldrh	w10, [x0]
	LSL  $24, R9, R9    // <--                                  // lsl	x9, x9, #24
	WORD $0x7940004b    // MOVHU (R2), R11                      // ldrh	w11, [x2]
	ORR  R10<<8, R8, R8 // <--                                  // orr	x8, x8, x10, lsl #8
	WORD $0x3940080a    // MOVBU 2(R0), R10                     // ldrb	w10, [x0, #2]
	ORR  R11<<8, R9, R9 // <--                                  // orr	x9, x9, x11, lsl #8
	WORD $0x3940084b    // MOVBU 2(R2), R11                     // ldrb	w11, [x2, #2]
	ORR  R10, R8, R10   // <--                                  // orr	x10, x8, x10
	ORR  R11, R9, R9    // <--                                  // orr	x9, x9, x11
	JMP  LBB0_181       // <--                                  // b	.LBB0_181

LBB0_104:
	WORD $0x6f00e405 // VMOVI $0, V5.D2                      // movi	v5.2d, #0000000000000000
	WORD $0x6f00e404 // VMOVI $0, V4.D2                      // movi	v4.2d, #0000000000000000
	MOVD R0, R9      // <--                                  // mov	x9, x0

LBB0_105:
	ADD  R8, R0, R8     // <--                                  // add	x8, x0, x8
	ADD  $1, R8, R10    // <--                                  // add	x10, x8, #1
	CMP  R10, R9        // <--                                  // cmp	x9, x10
	BHI  LBB0_231       // <--                                  // b.hi	.LBB0_231
	CMP  $4, R3         // <--                                  // cmp	x3, #4
	MOVW $4, R8         // <--                                  // mov	w8, #4
	WORD $0x4f05e406    // VMOVI $160, V6.B16                   // movi	v6.16b, #160
	CSEL GT, R3, R8, R8 // <--                                  // csel	x8, x3, x8, gt
	WORD $0x4f078607    // VMOVI $240, V7.H8                    // movi	v7.8h, #240
	WORD $0x0f05e410    // VMOVI $160, V16.B8                   // movi	v16.8b, #160
	SUB  $4, R8, R8     // <--                                  // sub	x8, x8, #4
	ADD  $2, R2, R12    // <--                                  // add	x12, x2, #2
	MOVW $15, R14       // <--                                  // mov	w14, #15
	AND  $15, R8, R11   // <--                                  // and	x11, x8, #0xf
	AND  $7, R8, R13    // <--                                  // and	x13, x8, #0x7
	NEG  R11, R15       // <--                                  // neg	x15, x11
	ADD  R15, R8, R15   // <--                                  // add	x15, x8, x15
	JMP  LBB0_108       // <--                                  // b	.LBB0_108

LBB0_107:
	VMOV V18.B16, V4.B16 // <--                                  // mov	v4.16b, v18.16b
	VMOV V17.B16, V5.B16 // <--                                  // mov	v5.16b, v17.16b
	ADD  $16, R9, R9     // <--                                  // add	x9, x9, #16
	CMP  R10, R9         // <--                                  // cmp	x9, x10
	MOVD $-1, R8         // <--                                  // mov	x8, #-1
	BHI  LBB0_2          // <--                                  // b.hi	.LBB0_2

LBB0_108:
	SUB  R0, R9, R8  // <--                                  // sub	x8, x9, x0
	SUB  R8, R1, R16 // <--                                  // sub	x16, x1, x8
	CMP  $16, R16    // <--                                  // cmp	x16, #16
	BLT  LBB0_110    // <--                                  // b.lt	.LBB0_110
	WORD $0x3dc00131 // FMOVQ (R9), F17                      // ldr	q17, [x9]
	JMP  LBB0_129    // <--                                  // b	.LBB0_129

LBB0_110:
	SUBS $8, R16, R2 // <--                                  // subs	x2, x16, #8
	BNE  LBB0_112    // <--                                  // b.ne	.LBB0_112
	WORD $0xfd400131 // FMOVD (R9), F17                      // ldr	d17, [x9]
	JMP  LBB0_129    // <--                                  // b	.LBB0_129

LBB0_112:
	CMP  $1, R16           // <--                                  // cmp	x16, #1
	BLT  LBB0_117          // <--                                  // b.lt	.LBB0_117
	MOVD R16, R5           // <--                                  // mov	x5, x16
	MOVD R9, R4            // <--                                  // mov	x4, x9
	TBZ  $3, R16, LBB0_115 // <--                                  // tbz	w16, #3, .LBB0_115
	MOVD R9, R4            // <--                                  // mov	x4, x9
	MOVD R2, R5            // <--                                  // mov	x5, x2
	WORD $0xf8408491       // MOVD.P 8(R4), R17                    // ldr	x17, [x4], #8

LBB0_115:
	TBNZ $2, R5, LBB0_118 // <--                                  // tbnz	w5, #2, .LBB0_118
	MOVD ZR, R2           // <--                                  // mov	x2, xzr
	JMP  LBB0_119         // <--                                  // b	.LBB0_119

LBB0_117:
	WORD $0x6f00e411 // VMOVI $0, V17.D2                     // movi	v17.2d, #0000000000000000
	JMP  LBB0_129    // <--                                  // b	.LBB0_129

LBB0_118:
	WORD $0xb8404482 // MOVWU.P 4(R4), R2                    // ldr	w2, [x4], #4
	SUB  $4, R5, R5  // <--                                  // sub	x5, x5, #4

LBB0_119:
	CMP  $1, R5          // <--                                  // cmp	x5, #1
	BEQ  LBB0_124        // <--                                  // b.eq	.LBB0_124
	CMP  $2, R5          // <--                                  // cmp	x5, #2
	BEQ  LBB0_123        // <--                                  // b.eq	.LBB0_123
	CMP  $3, R5          // <--                                  // cmp	x5, #3
	BNE  LBB0_126        // <--                                  // b.ne	.LBB0_126
	LSRW $2, R16, R5     // <--                                  // lsr	w5, w16, #2
	LSLW $3, R16, R6     // <--                                  // lsl	w6, w16, #3
	WORD $0x79400087     // MOVHU (R4), R7                       // ldrh	w7, [x4]
	MOVW $16, R19        // <--                                  // mov	w19, #16
	WORD $0x39400884     // MOVBU 2(R4), R4                      // ldrb	w4, [x4, #2]
	ANDW $32, R6, R6     // <--                                  // and	w6, w6, #0x20
	BFIW $5, R5, $1, R19 // <--                                  // bfi	w19, w5, #5, #1
	LSL  R6, R7, R5      // <--                                  // lsl	x5, x7, x6
	LSL  R19, R4, R4     // <--                                  // lsl	x4, x4, x19
	ORR  R2, R5, R2      // <--                                  // orr	x2, x5, x2
	ORR  R4, R2, R2      // <--                                  // orr	x2, x2, x4
	JMP  LBB0_126        // <--                                  // b	.LBB0_126

LBB0_123:
	WORD $0x79400084 // MOVHU (R4), R4                       // ldrh	w4, [x4]
	LSL  $3, R16, R5 // <--                                  // lsl	x5, x16, #3
	JMP  LBB0_125    // <--                                  // b	.LBB0_125

LBB0_124:
	LSL  $3, R16, R5 // <--                                  // lsl	x5, x16, #3
	WORD $0x39400084 // MOVBU (R4), R4                       // ldrb	w4, [x4]

LBB0_125:
	AND $32, R5, R5 // <--                                  // and	x5, x5, #0x20
	LSL R5, R4, R4  // <--                                  // lsl	x4, x4, x5
	ORR R2, R4, R2  // <--                                  // orr	x2, x4, x2

LBB0_126:
	CMP  $7, R16      // <--                                  // cmp	x16, #7
	BHI  LBB0_128     // <--                                  // b.hi	.LBB0_128
	WORD $0x6f00e411  // VMOVI $0, V17.D2                     // movi	v17.2d, #0000000000000000
	VMOV R2, V17.D[0] // <--                                  // mov	v17.d[0], x2
	JMP  LBB0_129     // <--                                  // b	.LBB0_129

LBB0_128:
	FMOVD R17, F17     // <--                                  // fmov	d17, x17
	VMOV  R2, V17.D[1] // <--                                  // mov	v17.d[1], x2

LBB0_129:
	SUB  R3, R16, R4 // <--                                  // sub	x4, x16, x3
	ADD  R3, R9, R6  // <--                                  // add	x6, x9, x3
	CMP  $14, R4     // <--                                  // cmp	x4, #14
	SUB  $2, R6, R2  // <--                                  // sub	x2, x6, #2
	BLT  LBB0_131    // <--                                  // b.lt	.LBB0_131
	WORD $0x3dc00052 // FMOVQ (R2), F18                      // ldr	q18, [x2]
	JMP  LBB0_149    // <--                                  // b	.LBB0_149

LBB0_131:
	ADD  $2, R4, R16 // <--                                  // add	x16, x4, #2
	CMP  $8, R16     // <--                                  // cmp	x16, #8
	BNE  LBB0_133    // <--                                  // b.ne	.LBB0_133
	WORD $0xfd400052 // FMOVD (R2), F18                      // ldr	d18, [x2]
	JMP  LBB0_149    // <--                                  // b	.LBB0_149

LBB0_133:
	WORD $0x6f00e412       // VMOVI $0, V18.D2                     // movi	v18.2d, #0000000000000000
	CMN  $1, R4            // <--                                  // cmn	x4, #1
	BLT  LBB0_149          // <--                                  // b.lt	.LBB0_149
	MOVD R16, R5           // <--                                  // mov	x5, x16
	TBZ  $3, R16, LBB0_136 // <--                                  // tbz	w16, #3, .LBB0_136
	WORD $0xf85fe0d1       // MOVD -2(R6), R17                     // ldur	x17, [x6, #-2]
	ADD  $6, R6, R2        // <--                                  // add	x2, x6, #6
	SUB  $6, R4, R5        // <--                                  // sub	x5, x4, #6

LBB0_136:
	TBNZ $2, R5, LBB0_138 // <--                                  // tbnz	w5, #2, .LBB0_138
	MOVD ZR, R4           // <--                                  // mov	x4, xzr
	JMP  LBB0_139         // <--                                  // b	.LBB0_139

LBB0_138:
	WORD $0xb8404444 // MOVWU.P 4(R2), R4                    // ldr	w4, [x2], #4
	SUB  $4, R5, R5  // <--                                  // sub	x5, x5, #4

LBB0_139:
	CMP  $1, R5          // <--                                  // cmp	x5, #1
	BEQ  LBB0_144        // <--                                  // b.eq	.LBB0_144
	CMP  $2, R5          // <--                                  // cmp	x5, #2
	BEQ  LBB0_143        // <--                                  // b.eq	.LBB0_143
	CMP  $3, R5          // <--                                  // cmp	x5, #3
	BNE  LBB0_146        // <--                                  // b.ne	.LBB0_146
	LSRW $2, R16, R5     // <--                                  // lsr	w5, w16, #2
	LSLW $3, R16, R6     // <--                                  // lsl	w6, w16, #3
	WORD $0x79400047     // MOVHU (R2), R7                       // ldrh	w7, [x2]
	MOVW $16, R19        // <--                                  // mov	w19, #16
	WORD $0x39400842     // MOVBU 2(R2), R2                      // ldrb	w2, [x2, #2]
	ANDW $32, R6, R6     // <--                                  // and	w6, w6, #0x20
	BFIW $5, R5, $1, R19 // <--                                  // bfi	w19, w5, #5, #1
	LSL  R6, R7, R5      // <--                                  // lsl	x5, x7, x6
	LSL  R19, R2, R2     // <--                                  // lsl	x2, x2, x19
	ORR  R4, R5, R4      // <--                                  // orr	x4, x5, x4
	ORR  R2, R4, R4      // <--                                  // orr	x4, x4, x2
	JMP  LBB0_146        // <--                                  // b	.LBB0_146

LBB0_143:
	WORD $0x79400042 // MOVHU (R2), R2                       // ldrh	w2, [x2]
	LSL  $3, R16, R5 // <--                                  // lsl	x5, x16, #3
	JMP  LBB0_145    // <--                                  // b	.LBB0_145

LBB0_144:
	LSL  $3, R16, R5 // <--                                  // lsl	x5, x16, #3
	WORD $0x39400042 // MOVBU (R2), R2                       // ldrb	w2, [x2]

LBB0_145:
	AND $32, R5, R5 // <--                                  // and	x5, x5, #0x20
	LSL R5, R2, R2  // <--                                  // lsl	x2, x2, x5
	ORR R4, R2, R4  // <--                                  // orr	x4, x2, x4

LBB0_146:
	CMP  $7, R16      // <--                                  // cmp	x16, #7
	BHI  LBB0_148     // <--                                  // b.hi	.LBB0_148
	VMOV R4, V18.D[0] // <--                                  // mov	v18.d[0], x4
	JMP  LBB0_149     // <--                                  // b	.LBB0_149

LBB0_148:
	FMOVD R17, F18     // <--                                  // fmov	d18, x17
	VMOV  R4, V18.D[1] // <--                                  // mov	v18.d[1], x4

LBB0_149:
	VADD  V6.B16, V17.B16, V17.B16           // <--                                  // add	v17.16b, v17.16b, v6.16b
	VADD  V6.B16, V18.B16, V18.B16           // <--                                  // add	v18.16b, v18.16b, v6.16b
	VTBL  V17.B16, [V0.B16, V1.B16], V19.B16 // <--                                  // tbl	v19.16b, { v0.16b, v1.16b }, v17.16b
	VTBL  V18.B16, [V0.B16, V1.B16], V20.B16 // <--                                  // tbl	v20.16b, { v0.16b, v1.16b }, v18.16b
	VSUB  V19.B16, V17.B16, V17.B16          // <--                                  // sub	v17.16b, v17.16b, v19.16b
	VSUB  V20.B16, V18.B16, V18.B16          // <--                                  // sub	v18.16b, v18.16b, v20.16b
	VEXT  $15, V17.B16, V5.B16, V5.B16       // <--                                  // ext	v5.16b, v5.16b, v17.16b, #15
	VEXT  $15, V18.B16, V4.B16, V4.B16       // <--                                  // ext	v4.16b, v4.16b, v18.16b, #15
	VCMEQ V17.H8, V2.H8, V19.H8              // <--                                  // cmeq	v19.8h, v2.8h, v17.8h
	VCMEQ V18.H8, V3.H8, V20.H8              // <--                                  // cmeq	v20.8h, v3.8h, v18.8h
	VCMEQ V5.H8, V2.H8, V5.H8                // <--                                  // cmeq	v5.8h, v2.8h, v5.8h
	VCMEQ V4.H8, V3.H8, V4.H8                // <--                                  // cmeq	v4.8h, v3.8h, v4.8h
	VAND  V20.B16, V19.B16, V19.B16          // <--                                  // and	v19.16b, v19.16b, v20.16b
	VAND  V4.B16, V5.B16, V4.B16             // <--                                  // and	v4.16b, v5.16b, v4.16b
	VSHL  $8, V19.H8, V5.H8                  // <--                                  // shl	v5.8h, v19.8h, #8
	VAND  V7.B16, V4.B16, V4.B16             // <--                                  // and	v4.16b, v4.16b, v7.16b
	VORR  V5.B16, V4.B16, V4.B16             // <--                                  // orr	v4.16b, v4.16b, v5.16b
	WORD  $0x0f0c8484                        // VSHRN $4, V4.H8, V4.B8               // shrn	v4.8b, v4.8h, #4
	FMOVD F4, R16                            // <--                                  // fmov	x16, d4
	CBNZ  R16, LBB0_153                      // <--                                  // cbnz	x16, .LBB0_153
	JMP   LBB0_107                           // <--                                  // b	.LBB0_107

LBB0_150:
	WORD $0x794000a5    // MOVHU (R5), R5                       // ldrh	w5, [x5]
	WORD $0x79400084    // MOVHU (R4), R4                       // ldrh	w4, [x4]
	ORR  R7<<16, R5, R7 // <--                                  // orr	x7, x5, x7, lsl #16
	ORR  R6<<16, R4, R6 // <--                                  // orr	x6, x4, x6, lsl #16

LBB0_151:
	FMOVD R7, F4                          // <--                                  // fmov	d4, x7
	FMOVD R6, F5                          // <--                                  // fmov	d5, x6
	VADD  V16.B8, V4.B8, V4.B8            // <--                                  // add	v4.8b, v4.8b, v16.8b
	VADD  V16.B8, V5.B8, V5.B8            // <--                                  // add	v5.8b, v5.8b, v16.8b
	VTBL  V4.B8, [V0.B16, V1.B16], V19.B8 // <--                                  // tbl	v19.8b, { v0.16b, v1.16b }, v4.8b
	VTBL  V5.B8, [V0.B16, V1.B16], V20.B8 // <--                                  // tbl	v20.8b, { v0.16b, v1.16b }, v5.8b
	VSUB  V19.B8, V4.B8, V4.B8            // <--                                  // sub	v4.8b, v4.8b, v19.8b
	VSUB  V20.B8, V5.B8, V5.B8            // <--                                  // sub	v5.8b, v5.8b, v20.8b
	VCMEQ V5.B8, V4.B8, V4.B8             // <--                                  // cmeq	v4.8b, v4.8b, v5.8b
	FMOVD F4, R4                          // <--                                  // fmov	x4, d4
	CMN   $1, R4                          // <--                                  // cmn	x4, #1
	BEQ   LBB0_182                        // <--                                  // b.eq	.LBB0_182

LBB0_152:
	AND $60, R17, R17 // <--                                  // and	x17, x17, #0x3c
	LSL R17, R14, R17 // <--                                  // lsl	x17, x14, x17
	BIC R17, R16, R16 // <--                                  // bic	x16, x16, x17
	CBZ R16, LBB0_107 // <--                                  // cbz	x16, .LBB0_107

LBB0_153:
	RBIT R16, R17 // <--                                  // rbit	x17, x16
	CMP  R0, R9   // <--                                  // cmp	x9, x0
	CLZ  R17, R17 // <--                                  // clz	x17, x17
	BNE  LBB0_155 // <--                                  // b.ne	.LBB0_155
	CMP  $4, R17  // <--                                  // cmp	x17, #4
	BCC  LBB0_152 // <--                                  // b.lo	.LBB0_152

LBB0_155:
	LSRW $2, R17, R2 // <--                                  // lsr	w2, w17, #2
	SUBW $1, R2, R2  // <--                                  // sub	w2, w2, #1
	SXTW R2, R2      // <--                                  // sxtw	x2, w2
	ADD  R2, R9, R4  // <--                                  // add	x4, x9, x2
	CMP  R10, R4     // <--                                  // cmp	x4, x10
	BCS  LBB0_152    // <--                                  // b.hs	.LBB0_152
	CMP  $20, R3     // <--                                  // cmp	x3, #20
	ADD  $2, R4, R5  // <--                                  // add	x5, x4, #2
	BGE  LBB0_158    // <--                                  // b.ge	.LBB0_158
	MOVD R12, R4     // <--                                  // mov	x4, x12
	JMP  LBB0_161    // <--                                  // b	.LBB0_161

LBB0_158:
	ADD  R15, R5, R6 // <--                                  // add	x6, x5, x15
	MOVD R12, R4     // <--                                  // mov	x4, x12

LBB0_159:
	WORD  $0x3cc104a4                       // FMOVQ.P 16(R5), F4                   // ldr	q4, [x5], #16
	WORD  $0x3cc10485                       // FMOVQ.P 16(R4), F5                   // ldr	q5, [x4], #16
	VADD  V6.B16, V4.B16, V4.B16            // <--                                  // add	v4.16b, v4.16b, v6.16b
	VADD  V6.B16, V5.B16, V5.B16            // <--                                  // add	v5.16b, v5.16b, v6.16b
	VTBL  V4.B16, [V0.B16, V1.B16], V19.B16 // <--                                  // tbl	v19.16b, { v0.16b, v1.16b }, v4.16b
	VTBL  V5.B16, [V0.B16, V1.B16], V20.B16 // <--                                  // tbl	v20.16b, { v0.16b, v1.16b }, v5.16b
	VSUB  V19.B16, V4.B16, V4.B16           // <--                                  // sub	v4.16b, v4.16b, v19.16b
	VSUB  V20.B16, V5.B16, V5.B16           // <--                                  // sub	v5.16b, v5.16b, v20.16b
	VCMEQ V5.B16, V4.B16, V4.B16            // <--                                  // cmeq	v4.16b, v4.16b, v5.16b
	WORD  $0x0f0c8484                       // VSHRN $4, V4.H8, V4.B8               // shrn	v4.8b, v4.8h, #4
	FMOVD F4, R7                            // <--                                  // fmov	x7, d4
	CMN   $1, R7                            // <--                                  // cmn	x7, #1
	BNE   LBB0_152                          // <--                                  // b.ne	.LBB0_152
	CMP   R6, R5                            // <--                                  // cmp	x5, x6
	BCC   LBB0_159                          // <--                                  // b.lo	.LBB0_159

LBB0_161:
	CMP   $8, R11                         // <--                                  // cmp	x11, #8
	BCC   LBB0_164                        // <--                                  // b.lo	.LBB0_164
	WORD  $0xfc4084a4                     // FMOVD.P 8(R5), F4                    // ldr	d4, [x5], #8
	WORD  $0xfc408485                     // FMOVD.P 8(R4), F5                    // ldr	d5, [x4], #8
	VADD  V16.B8, V4.B8, V4.B8            // <--                                  // add	v4.8b, v4.8b, v16.8b
	VADD  V16.B8, V5.B8, V5.B8            // <--                                  // add	v5.8b, v5.8b, v16.8b
	VTBL  V4.B8, [V0.B16, V1.B16], V19.B8 // <--                                  // tbl	v19.8b, { v0.16b, v1.16b }, v4.8b
	VTBL  V5.B8, [V0.B16, V1.B16], V20.B8 // <--                                  // tbl	v20.8b, { v0.16b, v1.16b }, v5.8b
	VSUB  V19.B8, V4.B8, V4.B8            // <--                                  // sub	v4.8b, v4.8b, v19.8b
	VSUB  V20.B8, V5.B8, V5.B8            // <--                                  // sub	v5.8b, v5.8b, v20.8b
	VCMEQ V5.B8, V4.B8, V4.B8             // <--                                  // cmeq	v4.8b, v4.8b, v5.8b
	FMOVD F4, R6                          // <--                                  // fmov	x6, d4
	CMN   $1, R6                          // <--                                  // cmn	x6, #1
	BNE   LBB0_152                        // <--                                  // b.ne	.LBB0_152
	MOVD  R13, R19                        // <--                                  // mov	x19, x13
	JMP   LBB0_165                        // <--                                  // b	.LBB0_165

LBB0_164:
	MOVD R11, R19 // <--                                  // mov	x19, x11

LBB0_165:
	CBZ  R19, LBB0_182 // <--                                  // cbz	x19, .LBB0_182
	SUBS $4, R19, R20  // <--                                  // subs	x20, x19, #4
	BCC  LBB0_171      // <--                                  // b.lo	.LBB0_171
	WORD $0xb84044a7   // MOVWU.P 4(R5), R7                    // ldr	w7, [x5], #4
	MOVD R20, R19      // <--                                  // mov	x19, x20
	WORD $0xb8404486   // MOVWU.P 4(R4), R6                    // ldr	w6, [x4], #4
	CMP  $1, R20       // <--                                  // cmp	x20, #1
	BEQ  LBB0_172      // <--                                  // b.eq	.LBB0_172

LBB0_168:
	CMP  $2, R19        // <--                                  // cmp	x19, #2
	BEQ  LBB0_150       // <--                                  // b.eq	.LBB0_150
	CMP  $3, R19        // <--                                  // cmp	x19, #3
	BNE  LBB0_151       // <--                                  // b.ne	.LBB0_151
	LSL  $24, R7, R7    // <--                                  // lsl	x7, x7, #24
	WORD $0x794000b3    // MOVHU (R5), R19                      // ldrh	w19, [x5]
	LSL  $24, R6, R6    // <--                                  // lsl	x6, x6, #24
	WORD $0x79400094    // MOVHU (R4), R20                      // ldrh	w20, [x4]
	WORD $0x394008a5    // MOVBU 2(R5), R5                      // ldrb	w5, [x5, #2]
	WORD $0x39400884    // MOVBU 2(R4), R4                      // ldrb	w4, [x4, #2]
	ORR  R19<<8, R7, R7 // <--                                  // orr	x7, x7, x19, lsl #8
	ORR  R20<<8, R6, R6 // <--                                  // orr	x6, x6, x20, lsl #8
	ORR  R5, R7, R7     // <--                                  // orr	x7, x7, x5
	ORR  R4, R6, R6     // <--                                  // orr	x6, x6, x4
	JMP  LBB0_151       // <--                                  // b	.LBB0_151

LBB0_171:
	MOVD ZR, R6   // <--                                  // mov	x6, xzr
	MOVD ZR, R7   // <--                                  // mov	x7, xzr
	CMP  $1, R19  // <--                                  // cmp	x19, #1
	BNE  LBB0_168 // <--                                  // b.ne	.LBB0_168

LBB0_172:
	WORD $0x394000a5   // MOVBU (R5), R5                       // ldrb	w5, [x5]
	WORD $0x39400084   // MOVBU (R4), R4                       // ldrb	w4, [x4]
	ORR  R7<<8, R5, R7 // <--                                  // orr	x7, x5, x7, lsl #8
	ORR  R6<<8, R4, R6 // <--                                  // orr	x6, x4, x6, lsl #8
	JMP  LBB0_151      // <--                                  // b	.LBB0_151

LBB0_173:
	RBIT  R9, R8         // <--                                  // rbit	x8, x9
	CLZ   R8, R8         // <--                                  // clz	x8, x8
	ADD   R8>>2, R10, R8 // <--                                  // add	x8, x10, x8, lsr #2
	ADD   R0, R8, R9     // <--                                  // add	x9, x8, x0
	CMP   R11, R9        // <--                                  // cmp	x9, x11
	CSINV LO, R8, ZR, R8 // <--                                  // csinv	x8, x8, xzr, lo
	NOP                  // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD  R8, R0         // <--                                  // mov	x0, x8
	NOP                  // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                  // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD  R0, ret+32(FP) // <--
	RET                  // <--                                  // ret

LBB0_174:
	RBIT  R8, R8         // <--                                  // rbit	x8, x8
	CLZ   R8, R8         // <--                                  // clz	x8, x8
	ADD   R8>>2, R10, R8 // <--                                  // add	x8, x10, x8, lsr #2
	SUB   $1, R8, R8     // <--                                  // sub	x8, x8, #1
	ADD   R0, R8, R10    // <--                                  // add	x10, x8, x0
	CMP   R9, R10        // <--                                  // cmp	x10, x9
	CSINV LO, R8, ZR, R8 // <--                                  // csinv	x8, x8, xzr, lo
	NOP                  // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD  R8, R0         // <--                                  // mov	x0, x8
	NOP                  // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                  // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD  R0, ret+32(FP) // <--
	RET                  // <--                                  // ret

LBB0_175:
	MOVD R8, R13          // <--                                  // mov	x13, x8
	MOVD R9, R12          // <--                                  // mov	x12, x9
	TBZ  $3, R1, LBB0_177 // <--                                  // tbz	w1, #3, .LBB0_177
	MOVD R9, R12          // <--                                  // mov	x12, x9
	MOVD R11, R13         // <--                                  // mov	x13, x11
	WORD $0xf840858a      // MOVD.P 8(R12), R10                   // ldr	x10, [x12], #8

LBB0_177:
	TBNZ $2, R13, LBB0_183 // <--                                  // tbnz	w13, #2, .LBB0_183
	MOVD ZR, R11           // <--                                  // mov	x11, xzr
	JMP  LBB0_184          // <--                                  // b	.LBB0_184

LBB0_179:
	WORD $0x79400008      // MOVHU (R0), R8                       // ldrh	w8, [x0]
	WORD $0x7940004b      // MOVHU (R2), R11                      // ldrh	w11, [x2]
	ORR  R10<<16, R8, R10 // <--                                  // orr	x10, x8, x10, lsl #16
	ORR  R9<<16, R11, R9  // <--                                  // orr	x9, x11, x9, lsl #16
	JMP  LBB0_181         // <--                                  // b	.LBB0_181

LBB0_180:
	WORD $0x39400008     // MOVBU (R0), R8                       // ldrb	w8, [x0]
	WORD $0x3940004b     // MOVBU (R2), R11                      // ldrb	w11, [x2]
	ORR  R10<<8, R8, R10 // <--                                  // orr	x10, x8, x10, lsl #8
	ORR  R9<<8, R11, R9  // <--                                  // orr	x9, x11, x9, lsl #8

LBB0_181:
	WORD  $0x0f05e402                    // VMOVI $160, V2.B8                    // movi	v2.8b, #160
	FMOVD R10, F3                        // <--                                  // fmov	d3, x10
	FMOVD R9, F4                         // <--                                  // fmov	d4, x9
	VADD  V2.B8, V3.B8, V3.B8            // <--                                  // add	v3.8b, v3.8b, v2.8b
	VADD  V2.B8, V4.B8, V2.B8            // <--                                  // add	v2.8b, v4.8b, v2.8b
	VTBL  V3.B8, [V0.B16, V1.B16], V4.B8 // <--                                  // tbl	v4.8b, { v0.16b, v1.16b }, v3.8b
	VTBL  V2.B8, [V0.B16, V1.B16], V0.B8 // <--                                  // tbl	v0.8b, { v0.16b, v1.16b }, v2.8b
	VSUB  V4.B8, V3.B8, V1.B8            // <--                                  // sub	v1.8b, v3.8b, v4.8b
	VSUB  V0.B8, V2.B8, V0.B8            // <--                                  // sub	v0.8b, v2.8b, v0.8b
	VCMEQ V0.B8, V1.B8, V0.B8            // <--                                  // cmeq	v0.8b, v1.8b, v0.8b
	FMOVD F0, R8                         // <--                                  // fmov	x8, d0
	CMN   $1, R8                         // <--                                  // cmn	x8, #1
	CSETM NE, R8                         // <--                                  // csetm	x8, ne
	NOP                                  // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD  R8, R0                         // <--                                  // mov	x0, x8
	NOP                                  // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                                  // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD  R0, ret+32(FP)                 // <--
	RET                                  // <--                                  // ret

LBB0_182:
	ADD  R2, R8, R8     // <--                                  // add	x8, x8, x2
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+32(FP) // <--
	RET                 // <--                                  // ret

LBB0_183:
	WORD $0xb840458b  // MOVWU.P 4(R12), R11                  // ldr	w11, [x12], #4
	SUB  $4, R13, R13 // <--                                  // sub	x13, x13, #4

LBB0_184:
	CMP  $1, R13          // <--                                  // cmp	x13, #1
	BEQ  LBB0_189         // <--                                  // b.eq	.LBB0_189
	CMP  $2, R13          // <--                                  // cmp	x13, #2
	BEQ  LBB0_188         // <--                                  // b.eq	.LBB0_188
	CMP  $3, R13          // <--                                  // cmp	x13, #3
	BNE  LBB0_192         // <--                                  // b.ne	.LBB0_192
	LSRW $2, R8, R13      // <--                                  // lsr	w13, w8, #2
	LSLW $3, R8, R14      // <--                                  // lsl	w14, w8, #3
	MOVW $16, R15         // <--                                  // mov	w15, #16
	WORD $0x79400190      // MOVHU (R12), R16                     // ldrh	w16, [x12]
	WORD $0x3940098c      // MOVBU 2(R12), R12                    // ldrb	w12, [x12, #2]
	BFIW $5, R13, $1, R15 // <--                                  // bfi	w15, w13, #5, #1
	ANDW $32, R14, R13    // <--                                  // and	w13, w14, #0x20
	LSL  R13, R16, R13    // <--                                  // lsl	x13, x16, x13
	LSL  R15, R12, R12    // <--                                  // lsl	x12, x12, x15
	ORR  R12, R13, R12    // <--                                  // orr	x12, x13, x12
	JMP  LBB0_191         // <--                                  // b	.LBB0_191

LBB0_188:
	WORD $0x7940018c // MOVHU (R12), R12                     // ldrh	w12, [x12]
	LSL  $3, R8, R13 // <--                                  // lsl	x13, x8, #3
	JMP  LBB0_190    // <--                                  // b	.LBB0_190

LBB0_189:
	LSL  $3, R8, R13 // <--                                  // lsl	x13, x8, #3
	WORD $0x3940018c // MOVBU (R12), R12                     // ldrb	w12, [x12]

LBB0_190:
	AND $32, R13, R13 // <--                                  // and	x13, x13, #0x20
	LSL R13, R12, R12 // <--                                  // lsl	x12, x12, x13

LBB0_191:
	ORR R11, R12, R11 // <--                                  // orr	x11, x12, x11

LBB0_192:
	CMP  $7, R8       // <--                                  // cmp	x8, #7
	BHI  LBB0_194     // <--                                  // b.hi	.LBB0_194
	WORD $0x6f00e403  // VMOVI $0, V3.D2                      // movi	v3.2d, #0000000000000000
	VMOV R11, V3.D[0] // <--                                  // mov	v3.d[0], x11
	JMP  LBB0_195     // <--                                  // b	.LBB0_195

LBB0_194:
	FMOVD R10, F3      // <--                                  // fmov	d3, x10
	VMOV  R11, V3.D[1] // <--                                  // mov	v3.d[1], x11

LBB0_195:
	WORD  $0x4f05e404                      // VMOVI $160, V4.B16                   // movi	v4.16b, #160
	VADD  V4.B16, V3.B16, V3.B16           // <--                                  // add	v3.16b, v3.16b, v4.16b
	VTBL  V3.B16, [V0.B16, V1.B16], V0.B16 // <--                                  // tbl	v0.16b, { v0.16b, v1.16b }, v3.16b
	VSUB  V0.B16, V3.B16, V0.B16           // <--                                  // sub	v0.16b, v3.16b, v0.16b
	VCMEQ V2.B16, V0.B16, V0.B16           // <--                                  // cmeq	v0.16b, v0.16b, v2.16b
	WORD  $0x0f0c8400                      // VSHRN $4, V0.H8, V0.B8               // shrn	v0.8b, v0.8h, #4
	FMOVD F0, R10                          // <--                                  // fmov	x10, d0
	CBZ   R10, LBB0_231                    // <--                                  // cbz	x10, .LBB0_231
	RBIT  R10, R10                         // <--                                  // rbit	x10, x10
	SUB   R0, R9, R9                       // <--                                  // sub	x9, x9, x0
	CLZ   R10, R10                         // <--                                  // clz	x10, x10
	LSR   $2, R10, R10                     // <--                                  // lsr	x10, x10, #2
	ADD   R10, R9, R9                      // <--                                  // add	x9, x9, x10
	CMP   R8, R10                          // <--                                  // cmp	x10, x8
	CSINV LO, R9, ZR, R8                   // <--                                  // csinv	x8, x9, xzr, lo
	NOP                                    // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD  R8, R0                           // <--                                  // mov	x0, x8
	NOP                                    // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                                    // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD  R0, ret+32(FP)                   // <--
	RET                                    // <--                                  // ret

LBB0_197:
	MOVD ZR, R17 // <--                                  // mov	x17, xzr
	MOVD ZR, R0  // <--                                  // mov	x0, xzr

LBB0_198:
	CMP  $1, R16         // <--                                  // cmp	x16, #1
	BEQ  LBB0_203        // <--                                  // b.eq	.LBB0_203
	CMP  $2, R16         // <--                                  // cmp	x16, #2
	BEQ  LBB0_202        // <--                                  // b.eq	.LBB0_202
	CMP  $3, R16         // <--                                  // cmp	x16, #3
	BNE  LBB0_204        // <--                                  // b.ne	.LBB0_204
	LSL  $24, R0, R16    // <--                                  // lsl	x16, x0, #24
	WORD $0x794001e0     // MOVHU (R15), R0                      // ldrh	w0, [x15]
	LSL  $24, R17, R17   // <--                                  // lsl	x17, x17, #24
	WORD $0x79400124     // MOVHU (R9), R4                       // ldrh	w4, [x9]
	WORD $0x394009ef     // MOVBU 2(R15), R15                    // ldrb	w15, [x15, #2]
	WORD $0x39400929     // MOVBU 2(R9), R9                      // ldrb	w9, [x9, #2]
	ORR  R0<<8, R16, R16 // <--                                  // orr	x16, x16, x0, lsl #8
	ORR  R4<<8, R17, R17 // <--                                  // orr	x17, x17, x4, lsl #8
	ORR  R15, R16, R0    // <--                                  // orr	x0, x16, x15
	ORR  R9, R17, R17    // <--                                  // orr	x17, x17, x9
	JMP  LBB0_204        // <--                                  // b	.LBB0_204

LBB0_202:
	WORD $0x794001ef      // MOVHU (R15), R15                     // ldrh	w15, [x15]
	WORD $0x79400129      // MOVHU (R9), R9                       // ldrh	w9, [x9]
	ORR  R0<<16, R15, R0  // <--                                  // orr	x0, x15, x0, lsl #16
	ORR  R17<<16, R9, R17 // <--                                  // orr	x17, x9, x17, lsl #16
	JMP  LBB0_204         // <--                                  // b	.LBB0_204

LBB0_203:
	WORD $0x394001ef     // MOVBU (R15), R15                     // ldrb	w15, [x15]
	WORD $0x39400129     // MOVBU (R9), R9                       // ldrb	w9, [x9]
	ORR  R0<<8, R15, R0  // <--                                  // orr	x0, x15, x0, lsl #8
	ORR  R17<<8, R9, R17 // <--                                  // orr	x17, x9, x17, lsl #8

LBB0_204:
	WORD  $0x0f05e402                    // VMOVI $160, V2.B8                    // movi	v2.8b, #160
	FMOVD R0, F3                         // <--                                  // fmov	d3, x0
	FMOVD R17, F4                        // <--                                  // fmov	d4, x17
	VADD  V2.B8, V3.B8, V3.B8            // <--                                  // add	v3.8b, v3.8b, v2.8b
	VADD  V2.B8, V4.B8, V2.B8            // <--                                  // add	v2.8b, v4.8b, v2.8b
	VTBL  V3.B8, [V0.B16, V1.B16], V4.B8 // <--                                  // tbl	v4.8b, { v0.16b, v1.16b }, v3.8b
	VTBL  V2.B8, [V0.B16, V1.B16], V5.B8 // <--                                  // tbl	v5.8b, { v0.16b, v1.16b }, v2.8b
	VSUB  V4.B8, V3.B8, V3.B8            // <--                                  // sub	v3.8b, v3.8b, v4.8b
	VSUB  V5.B8, V2.B8, V2.B8            // <--                                  // sub	v2.8b, v2.8b, v5.8b
	VCMEQ V2.B8, V3.B8, V2.B8            // <--                                  // cmeq	v2.8b, v3.8b, v2.8b
	FMOVD F2, R9                         // <--                                  // fmov	x9, d2
	CMN   $1, R9                         // <--                                  // cmn	x9, #1
	BEQ   LBB0_2                         // <--                                  // b.eq	.LBB0_2

LBB0_205:
	SUB  R8, R1, R9   // <--                                  // sub	x9, x1, x8
	CMP  R9, R3       // <--                                  // cmp	x3, x9
	BCS  LBB0_231     // <--                                  // b.hs	.LBB0_231
	WORD $0x0f05e402  // VMOVI $160, V2.B8                    // movi	v2.8b, #160
	WORD $0x4f05e403  // VMOVI $160, V3.B16                   // movi	v3.16b, #160
	AND  $15, R3, R15 // <--                                  // and	x15, x3, #0xf
	NEG  R15, R0      // <--                                  // neg	x0, x15
	NEG  R3, R16      // <--                                  // neg	x16, x3
	AND  $7, R3, R17  // <--                                  // and	x17, x3, #0x7
	ADD  R0, R3, R0   // <--                                  // add	x0, x3, x0
	MOVD R3, R1       // <--                                  // mov	x1, x3
	JMP  LBB0_210     // <--                                  // b	.LBB0_210

LBB0_207:
	WORD $0x794000c6      // MOVHU (R6), R6                       // ldrh	w6, [x6]
	WORD $0x794000a5      // MOVHU (R5), R5                       // ldrh	w5, [x5]
	ORR  R19<<16, R6, R19 // <--                                  // orr	x19, x6, x19, lsl #16
	ORR  R7<<16, R5, R7   // <--                                  // orr	x7, x5, x7, lsl #16

LBB0_208:
	FMOVD R19, F4                        // <--                                  // fmov	d4, x19
	FMOVD R7, F5                         // <--                                  // fmov	d5, x7
	VADD  V2.B8, V4.B8, V4.B8            // <--                                  // add	v4.8b, v4.8b, v2.8b
	VADD  V2.B8, V5.B8, V5.B8            // <--                                  // add	v5.8b, v5.8b, v2.8b
	VTBL  V4.B8, [V0.B16, V1.B16], V6.B8 // <--                                  // tbl	v6.8b, { v0.16b, v1.16b }, v4.8b
	VTBL  V5.B8, [V0.B16, V1.B16], V7.B8 // <--                                  // tbl	v7.8b, { v0.16b, v1.16b }, v5.8b
	VSUB  V6.B8, V4.B8, V4.B8            // <--                                  // sub	v4.8b, v4.8b, v6.8b
	VSUB  V7.B8, V5.B8, V5.B8            // <--                                  // sub	v5.8b, v5.8b, v7.8b
	VCMEQ V5.B8, V4.B8, V4.B8            // <--                                  // cmeq	v4.8b, v4.8b, v5.8b
	FMOVD F4, R5                         // <--                                  // fmov	x5, d4
	CMN   $1, R5                         // <--                                  // cmn	x5, #1
	BEQ   LBB0_229                       // <--                                  // b.eq	.LBB0_229

LBB0_209:
	ADD $1, R1, R1 // <--                                  // add	x1, x1, #1
	CMP R9, R1     // <--                                  // cmp	x1, x9
	BEQ LBB0_231   // <--                                  // b.eq	.LBB0_231

LBB0_210:
	ADD   R1, R10, R5       // <--                                  // add	x5, x10, x1
	SUB   R3, R1, R4        // <--                                  // sub	x4, x1, x3
	MULW  R11, R14, R14     // <--                                  // mul	w14, w14, w11
	WORD  $0x394000a6       // MOVBU (R5), R6                       // ldrb	w6, [x5]
	WORD  $0x38646947       // MOVBU (R10)(R4), R7                  // ldrb	w7, [x10, x4]
	SUBW  $97, R6, R19      // <--                                  // sub	w19, w6, #97
	CMPW  $26, R19          // <--                                  // cmp	w19, #26
	ORRW  $128, R6, R19     // <--                                  // orr	w19, w6, #0x80
	SUBW  $96, R6, R6       // <--                                  // sub	w6, w6, #96
	CSELW LO, R19, R6, R6   // <--                                  // csel	w6, w19, w6, lo
	SUBW  $97, R7, R19      // <--                                  // sub	w19, w7, #97
	CMPW  $26, R19          // <--                                  // cmp	w19, #26
	ORRW  $128, R7, R19     // <--                                  // orr	w19, w7, #0x80
	SUBW  $96, R7, R7       // <--                                  // sub	w7, w7, #96
	CSELW LO, R19, R7, R7   // <--                                  // csel	w7, w19, w7, lo
	ADDW  R6.UXTB, R14, R14 // <--                                  // add	w14, w14, w6, uxtb
	ANDW  $255, R7, R7      // <--                                  // and	w7, w7, #0xff
	MSUBW R7, R14, R13, R14 // <--                                  // msub	w14, w13, w7, w14
	CMPW  R12, R14          // <--                                  // cmp	w14, w12
	BNE   LBB0_209          // <--                                  // b.ne	.LBB0_209
	ADD   R16, R5, R5       // <--                                  // add	x5, x5, x16
	CMP   $16, R3           // <--                                  // cmp	x3, #16
	ADD   $1, R5, R6        // <--                                  // add	x6, x5, #1
	BCS   LBB0_213          // <--                                  // b.hs	.LBB0_213
	MOVD  R2, R5            // <--                                  // mov	x5, x2
	JMP   LBB0_216          // <--                                  // b	.LBB0_216

LBB0_213:
	ADD  R0, R6, R7 // <--                                  // add	x7, x6, x0
	MOVD R2, R5     // <--                                  // mov	x5, x2

LBB0_214:
	WORD  $0x3cc104c4                      // FMOVQ.P 16(R6), F4                   // ldr	q4, [x6], #16
	WORD  $0x3cc104a5                      // FMOVQ.P 16(R5), F5                   // ldr	q5, [x5], #16
	VADD  V3.B16, V4.B16, V4.B16           // <--                                  // add	v4.16b, v4.16b, v3.16b
	VADD  V3.B16, V5.B16, V5.B16           // <--                                  // add	v5.16b, v5.16b, v3.16b
	VTBL  V4.B16, [V0.B16, V1.B16], V6.B16 // <--                                  // tbl	v6.16b, { v0.16b, v1.16b }, v4.16b
	VTBL  V5.B16, [V0.B16, V1.B16], V7.B16 // <--                                  // tbl	v7.16b, { v0.16b, v1.16b }, v5.16b
	VSUB  V6.B16, V4.B16, V4.B16           // <--                                  // sub	v4.16b, v4.16b, v6.16b
	VSUB  V7.B16, V5.B16, V5.B16           // <--                                  // sub	v5.16b, v5.16b, v7.16b
	VCMEQ V5.B16, V4.B16, V4.B16           // <--                                  // cmeq	v4.16b, v4.16b, v5.16b
	WORD  $0x0f0c8484                      // VSHRN $4, V4.H8, V4.B8               // shrn	v4.8b, v4.8h, #4
	FMOVD F4, R19                          // <--                                  // fmov	x19, d4
	CMN   $1, R19                          // <--                                  // cmn	x19, #1
	BNE   LBB0_209                         // <--                                  // b.ne	.LBB0_209
	CMP   R7, R6                           // <--                                  // cmp	x6, x7
	BCC   LBB0_214                         // <--                                  // b.lo	.LBB0_214

LBB0_216:
	CMP   $8, R15                        // <--                                  // cmp	x15, #8
	BCC   LBB0_219                       // <--                                  // b.lo	.LBB0_219
	WORD  $0xfc4084c4                    // FMOVD.P 8(R6), F4                    // ldr	d4, [x6], #8
	WORD  $0xfc4084a5                    // FMOVD.P 8(R5), F5                    // ldr	d5, [x5], #8
	VADD  V2.B8, V4.B8, V4.B8            // <--                                  // add	v4.8b, v4.8b, v2.8b
	VADD  V2.B8, V5.B8, V5.B8            // <--                                  // add	v5.8b, v5.8b, v2.8b
	VTBL  V4.B8, [V0.B16, V1.B16], V6.B8 // <--                                  // tbl	v6.8b, { v0.16b, v1.16b }, v4.8b
	VTBL  V5.B8, [V0.B16, V1.B16], V7.B8 // <--                                  // tbl	v7.8b, { v0.16b, v1.16b }, v5.8b
	VSUB  V6.B8, V4.B8, V4.B8            // <--                                  // sub	v4.8b, v4.8b, v6.8b
	VSUB  V7.B8, V5.B8, V5.B8            // <--                                  // sub	v5.8b, v5.8b, v7.8b
	VCMEQ V5.B8, V4.B8, V4.B8            // <--                                  // cmeq	v4.8b, v4.8b, v5.8b
	FMOVD F4, R7                         // <--                                  // fmov	x7, d4
	CMN   $1, R7                         // <--                                  // cmn	x7, #1
	BNE   LBB0_209                       // <--                                  // b.ne	.LBB0_209
	MOVD  R17, R20                       // <--                                  // mov	x20, x17
	JMP   LBB0_220                       // <--                                  // b	.LBB0_220

LBB0_219:
	MOVD R15, R20 // <--                                  // mov	x20, x15

LBB0_220:
	CBZ  R20, LBB0_229 // <--                                  // cbz	x20, .LBB0_229
	SUBS $4, R20, R21  // <--                                  // subs	x21, x20, #4
	BCC  LBB0_223      // <--                                  // b.lo	.LBB0_223
	WORD $0xb84044d3   // MOVWU.P 4(R6), R19                   // ldr	w19, [x6], #4
	MOVD R21, R20      // <--                                  // mov	x20, x21
	WORD $0xb84044a7   // MOVWU.P 4(R5), R7                    // ldr	w7, [x5], #4
	JMP  LBB0_224      // <--                                  // b	.LBB0_224

LBB0_223:
	MOVD ZR, R7  // <--                                  // mov	x7, xzr
	MOVD ZR, R19 // <--                                  // mov	x19, xzr

LBB0_224:
	CMP  $1, R20          // <--                                  // cmp	x20, #1
	BEQ  LBB0_228         // <--                                  // b.eq	.LBB0_228
	CMP  $2, R20          // <--                                  // cmp	x20, #2
	BEQ  LBB0_207         // <--                                  // b.eq	.LBB0_207
	CMP  $3, R20          // <--                                  // cmp	x20, #3
	BNE  LBB0_208         // <--                                  // b.ne	.LBB0_208
	LSL  $24, R19, R19    // <--                                  // lsl	x19, x19, #24
	WORD $0x794000d4      // MOVHU (R6), R20                      // ldrh	w20, [x6]
	LSL  $24, R7, R7      // <--                                  // lsl	x7, x7, #24
	WORD $0x794000b5      // MOVHU (R5), R21                      // ldrh	w21, [x5]
	WORD $0x394008c6      // MOVBU 2(R6), R6                      // ldrb	w6, [x6, #2]
	WORD $0x394008a5      // MOVBU 2(R5), R5                      // ldrb	w5, [x5, #2]
	ORR  R20<<8, R19, R19 // <--                                  // orr	x19, x19, x20, lsl #8
	ORR  R21<<8, R7, R7   // <--                                  // orr	x7, x7, x21, lsl #8
	ORR  R6, R19, R19     // <--                                  // orr	x19, x19, x6
	ORR  R5, R7, R7       // <--                                  // orr	x7, x7, x5
	JMP  LBB0_208         // <--                                  // b	.LBB0_208

LBB0_228:
	WORD $0x394000c6     // MOVBU (R6), R6                       // ldrb	w6, [x6]
	WORD $0x394000a5     // MOVBU (R5), R5                       // ldrb	w5, [x5]
	ORR  R19<<8, R6, R19 // <--                                  // orr	x19, x6, x19, lsl #8
	ORR  R7<<8, R5, R7   // <--                                  // orr	x7, x5, x7, lsl #8
	JMP  LBB0_208        // <--                                  // b	.LBB0_208

LBB0_229:
	ADD  $1, R4, R9     // <--                                  // add	x9, x4, #1
	CMN  $1, R9         // <--                                  // cmn	x9, #1
	BEQ  LBB0_231       // <--                                  // b.eq	.LBB0_231
	ADD  R8, R9, R8     // <--                                  // add	x8, x9, x8
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+32(FP) // <--
	RET                 // <--                                  // ret

LBB0_231:
	MOVD $-1, R8        // <--                                  // mov	x8, #-1
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+32(FP) // <--
	RET                 // <--                                  // ret
