//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package ascii


//go:noescape
func ValidString(data string) bool

//go:noescape
func IndexMask(data string, mask byte) int

//go:noescape
func EqualFold(a string, b string) bool

//go:noescape
func IndexFoldRabinKarp(a string, b string) int

//go:noescape
func IndexFold(a string, b string) int
