//go:build !noasm && arm64
// Code generated by gocc v0.16.6-0.20260113004826-b04e2010a937+dirty-rev-b04e201-dirty -- DO NOT EDIT.
//
// Source file         : ascii_neon_memchr.c
// Clang version       : Homebrew clang version 21.1.8
// Target architecture : arm64
// Compiler options    : [none]

#include "textflag.h"

TEXT ·IndexFoldMemchr(SB), NOSPLIT, $0-72
	MOVD haystack+0(FP), R0
	MOVD haystack_len+8(FP), R1
	MOVB rare1+16(FP), R2
	MOVD off1+24(FP), R3
	MOVB rare2+32(FP), R4
	MOVD off2+40(FP), R5
	MOVD needle+48(FP), R6
	MOVD needle_len+56(FP), R7
	NOP                         // (skipped)                            // stp	x24, x23, [sp, #-48]!
	NOP                         // (skipped)                            // stp	x22, x21, [sp, #16]
	NOP                         // (skipped)                            // stp	x20, x19, [sp, #32]
	CBZ  R7, LBB0_13            // <--                                  // cbz	x7, .LBB0_13
	SUBS R7, R1, R9             // <--                                  // subs	x9, x1, x7
	BGE  LBB0_4                 // <--                                  // b.ge	.LBB0_4
	MOVD $-1, R8                // <--                                  // mov	x8, #-1

LBB0_3:
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+64(FP) // <--
	RET                 // <--                                  // ret

LBB0_4:
	CMP  $15, R1    // <--                                  // cmp	x1, #15
	BGT  LBB0_14    // <--                                  // b.gt	.LBB0_14
	CMP  $1, R7     // <--                                  // cmp	x7, #1
	BLT  LBB0_13    // <--                                  // b.lt	.LBB0_13
	MOVD ZR, R8     // <--                                  // mov	x8, xzr
	ADD  $1, R9, R9 // <--                                  // add	x9, x9, #1

LBB0_7:
	MOVD ZR, R10 // <--                                  // mov	x10, xzr

LBB0_8:
	WORD  $0x386a680b       // MOVBU (R0)(R10), R11                 // ldrb	w11, [x0, x10]
	WORD  $0x386a68cc       // MOVBU (R6)(R10), R12                 // ldrb	w12, [x6, x10]
	ADD   $1, R10, R10      // <--                                  // add	x10, x10, #1
	SUBW  $65, R11, R13     // <--                                  // sub	w13, w11, #65
	ORRW  $32, R11, R14     // <--                                  // orr	w14, w11, #0x20
	CMPW  $26, R13          // <--                                  // cmp	w13, #26
	SUBW  $65, R12, R13     // <--                                  // sub	w13, w12, #65
	CSELW LO, R14, R11, R11 // <--                                  // csel	w11, w14, w11, lo
	ORRW  $32, R12, R14     // <--                                  // orr	w14, w12, #0x20
	CMPW  $26, R13          // <--                                  // cmp	w13, #26
	CSELW LO, R14, R12, R12 // <--                                  // csel	w12, w14, w12, lo
	CMP   R7, R10           // <--                                  // cmp	x10, x7
	BGE   LBB0_10           // <--                                  // b.ge	.LBB0_10
	CMPW  R12, R11          // <--                                  // cmp	w11, w12
	BEQ   LBB0_8            // <--                                  // b.eq	.LBB0_8

LBB0_10:
	CMPW R12, R11       // <--                                  // cmp	w11, w12
	BEQ  LBB0_3         // <--                                  // b.eq	.LBB0_3
	ADD  $1, R8, R8     // <--                                  // add	x8, x8, #1
	ADD  $1, R0, R0     // <--                                  // add	x0, x0, #1
	CMP  R9, R8         // <--                                  // cmp	x8, x9
	BNE  LBB0_7         // <--                                  // b.ne	.LBB0_7
	MOVD $-1, R8        // <--                                  // mov	x8, #-1
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+64(FP) // <--
	RET                 // <--                                  // ret

LBB0_13:
	MOVD ZR, R8         // <--                                  // mov	x8, xzr
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+64(FP) // <--
	RET                 // <--                                  // ret

LBB0_14:
	SUBW  $97, R2, R8     // <--                                  // sub	w8, w2, #97
	VDUP  R2, V1.B16      // <--                                  // dup	v1.16b, w2
	ADD   $1, R9, R14     // <--                                  // add	x14, x9, #1
	ANDW  $255, R8, R8    // <--                                  // and	w8, w8, #0xff
	ADD   R1, R0, R11     // <--                                  // add	x11, x0, x1
	ADD   R3, R0, R12     // <--                                  // add	x12, x0, x3
	CMPW  $26, R8         // <--                                  // cmp	w8, #26
	MOVW  $32, R8         // <--                                  // mov	w8, #32
	CSELW LO, R8, ZR, R10 // <--                                  // csel	w10, w8, wzr, lo
	CMP   $63, R9         // <--                                  // cmp	x9, #63
	VDUP  R10, V0.B16     // <--                                  // dup	v0.16b, w10
	BLT   LBB0_64         // <--                                  // b.lt	.LBB0_64
	ADD   $64, R12, R8    // <--                                  // add	x8, x12, #64
	CMP   R11, R8         // <--                                  // cmp	x8, x11
	BHI   LBB0_64         // <--                                  // b.hi	.LBB0_64
	WORD  $0x4f01e402     // VMOVI $32, V2.B16                    // movi	v2.16b, #32
	WORD  $0x4f04e7e3     // VMOVI $159, V3.B16                   // movi	v3.16b, #159
	MOVW  $15, R15        // <--                                  // mov	w15, #15
	WORD  $0x4f00e744     // VMOVI $26, V4.B16                    // movi	v4.16b, #26
	MOVD  R12, R16        // <--                                  // mov	x16, x12

LBB0_17:
	WORD  $0xad401a05               // FLDPQ (R16), (F5, F6)                // ldp	q5, q6, [x16]
	MOVD  R8, R13                   // <--                                  // mov	x13, x8
	WORD  $0xad414207               // FLDPQ 32(R16), (F7, F16)             // ldp	q7, q16, [x16, #32]
	VORR  V0.B16, V5.B16, V5.B16    // <--                                  // orr	v5.16b, v5.16b, v0.16b
	VORR  V0.B16, V6.B16, V6.B16    // <--                                  // orr	v6.16b, v6.16b, v0.16b
	VORR  V0.B16, V7.B16, V17.B16   // <--                                  // orr	v17.16b, v7.16b, v0.16b
	VORR  V0.B16, V16.B16, V18.B16  // <--                                  // orr	v18.16b, v16.16b, v0.16b
	VCMEQ V1.B16, V5.B16, V16.B16   // <--                                  // cmeq	v16.16b, v5.16b, v1.16b
	VCMEQ V1.B16, V6.B16, V7.B16    // <--                                  // cmeq	v7.16b, v6.16b, v1.16b
	VCMEQ V1.B16, V17.B16, V6.B16   // <--                                  // cmeq	v6.16b, v17.16b, v1.16b
	VCMEQ V1.B16, V18.B16, V5.B16   // <--                                  // cmeq	v5.16b, v18.16b, v1.16b
	VORR  V16.B16, V7.B16, V17.B16  // <--                                  // orr	v17.16b, v7.16b, v16.16b
	VORR  V5.B16, V6.B16, V18.B16   // <--                                  // orr	v18.16b, v6.16b, v5.16b
	VORR  V18.B16, V17.B16, V17.B16 // <--                                  // orr	v17.16b, v17.16b, v18.16b
	VDUP  V17.D[1], V18.D2          // <--                                  // dup	v18.2d, v17.d[1]
	VORR  V17.B16, V18.B16, V17.B16 // <--                                  // orr	v17.16b, v18.16b, v17.16b
	FMOVD F17, R17                  // <--                                  // fmov	x17, d17
	CBZ   R17, LBB0_62              // <--                                  // cbz	x17, .LBB0_62
	WORD  $0x0f0c8610               // VSHRN $4, V16.H8, V16.B8             // shrn	v16.8b, v16.8h, #4
	FMOVD F16, R17                  // <--                                  // fmov	x17, d16
	CBZ   R17, LBB0_29              // <--                                  // cbz	x17, .LBB0_29
	SUB   R12, R16, R1              // <--                                  // sub	x1, x16, x12
	JMP   LBB0_21                   // <--                                  // b	.LBB0_21

LBB0_20:
	AND  $60, R3, R8  // <--                                  // and	x8, x3, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R17, R17 // <--                                  // bics	x17, x17, x8
	BEQ  LBB0_29      // <--                                  // b.eq	.LBB0_29

LBB0_21:
	RBIT R17, R8       // <--                                  // rbit	x8, x17
	CLZ  R8, R3        // <--                                  // clz	x3, x8
	ADD  R3>>2, R1, R8 // <--                                  // add	x8, x1, x3, lsr #2
	CMP  R9, R8        // <--                                  // cmp	x8, x9
	BHI  LBB0_20       // <--                                  // b.hi	.LBB0_20
	ADD  R8, R0, R4    // <--                                  // add	x4, x0, x8
	MOVD R7, R5        // <--                                  // mov	x5, x7
	MOVD R6, R19       // <--                                  // mov	x19, x6

LBB0_23:
	CMP   $15, R5                   // <--                                  // cmp	x5, #15
	BLE   LBB0_25                   // <--                                  // b.le	.LBB0_25
	WORD  $0x3cc10490               // FMOVQ.P 16(R4), F16                  // ldr	q16, [x4], #16
	SUB   $16, R5, R5               // <--                                  // sub	x5, x5, #16
	WORD  $0x3cc10671               // FMOVQ.P 16(R19), F17                 // ldr	q17, [x19], #16
	VEOR  V16.B16, V17.B16, V17.B16 // <--                                  // eor	v17.16b, v17.16b, v16.16b
	VORR  V2.B16, V16.B16, V16.B16  // <--                                  // orr	v16.16b, v16.16b, v2.16b
	VCMEQ V2.B16, V17.B16, V18.B16  // <--                                  // cmeq	v18.16b, v17.16b, v2.16b
	VADD  V3.B16, V16.B16, V16.B16  // <--                                  // add	v16.16b, v16.16b, v3.16b
	WORD  $0x6e303490               // VCMHI V16.B16, V4.B16, V16.B16       // cmhi	v16.16b, v4.16b, v16.16b
	VAND  V2.B16, V18.B16, V18.B16  // <--                                  // and	v18.16b, v18.16b, v2.16b
	VAND  V16.B16, V18.B16, V16.B16 // <--                                  // and	v16.16b, v18.16b, v16.16b
	VEOR  V17.B16, V16.B16, V16.B16 // <--                                  // eor	v16.16b, v16.16b, v17.16b
	WORD  $0x6e30aa10               // VUMAXV V16.B16, V16                  // umaxv	b16, v16.16b
	FMOVS F16, R20                  // <--                                  // fmov	w20, s16
	CBZW  R20, LBB0_23              // <--                                  // cbz	w20, .LBB0_23
	JMP   LBB0_20                   // <--                                  // b	.LBB0_20

LBB0_25:
	CMP  $1, R5  // <--                                  // cmp	x5, #1
	BLT  LBB0_3  // <--                                  // b.lt	.LBB0_3
	MOVD ZR, R20 // <--                                  // mov	x20, xzr

LBB0_27:
	WORD  $0x38746895       // MOVBU (R4)(R20), R21                 // ldrb	w21, [x4, x20]
	WORD  $0x38746a76       // MOVBU (R19)(R20), R22                // ldrb	w22, [x19, x20]
	SUBW  $65, R21, R23     // <--                                  // sub	w23, w21, #65
	ORRW  $32, R21, R24     // <--                                  // orr	w24, w21, #0x20
	CMPW  $26, R23          // <--                                  // cmp	w23, #26
	SUBW  $65, R22, R23     // <--                                  // sub	w23, w22, #65
	CSELW LO, R24, R21, R21 // <--                                  // csel	w21, w24, w21, lo
	ORRW  $32, R22, R24     // <--                                  // orr	w24, w22, #0x20
	CMPW  $26, R23          // <--                                  // cmp	w23, #26
	CSELW LO, R24, R22, R22 // <--                                  // csel	w22, w24, w22, lo
	CMPW  R22, R21          // <--                                  // cmp	w21, w22
	BNE   LBB0_20           // <--                                  // b.ne	.LBB0_20
	ADD   $1, R20, R20      // <--                                  // add	x20, x20, #1
	CMP   R20, R5           // <--                                  // cmp	x5, x20
	BNE   LBB0_27           // <--                                  // b.ne	.LBB0_27
	JMP   LBB0_3            // <--                                  // b	.LBB0_3

LBB0_29:
	WORD  $0x0f0c84e7  // VSHRN $4, V7.H8, V7.B8               // shrn	v7.8b, v7.8h, #4
	FMOVD F7, R17      // <--                                  // fmov	x17, d7
	CBZ   R17, LBB0_40 // <--                                  // cbz	x17, .LBB0_40
	SUB   R12, R16, R8 // <--                                  // sub	x8, x16, x12
	ADD   $16, R8, R1  // <--                                  // add	x1, x8, #16
	JMP   LBB0_32      // <--                                  // b	.LBB0_32

LBB0_31:
	AND  $60, R3, R8  // <--                                  // and	x8, x3, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R17, R17 // <--                                  // bics	x17, x17, x8
	BEQ  LBB0_40      // <--                                  // b.eq	.LBB0_40

LBB0_32:
	RBIT R17, R8       // <--                                  // rbit	x8, x17
	CLZ  R8, R3        // <--                                  // clz	x3, x8
	ADD  R3>>2, R1, R8 // <--                                  // add	x8, x1, x3, lsr #2
	CMP  R9, R8        // <--                                  // cmp	x8, x9
	BHI  LBB0_31       // <--                                  // b.hi	.LBB0_31
	ADD  R8, R0, R4    // <--                                  // add	x4, x0, x8
	MOVD R7, R5        // <--                                  // mov	x5, x7
	MOVD R6, R19       // <--                                  // mov	x19, x6

LBB0_34:
	CMP   $15, R5                  // <--                                  // cmp	x5, #15
	BLE   LBB0_36                  // <--                                  // b.le	.LBB0_36
	WORD  $0x3cc10487              // FMOVQ.P 16(R4), F7                   // ldr	q7, [x4], #16
	SUB   $16, R5, R5              // <--                                  // sub	x5, x5, #16
	WORD  $0x3cc10670              // FMOVQ.P 16(R19), F16                 // ldr	q16, [x19], #16
	VEOR  V7.B16, V16.B16, V16.B16 // <--                                  // eor	v16.16b, v16.16b, v7.16b
	VORR  V2.B16, V7.B16, V7.B16   // <--                                  // orr	v7.16b, v7.16b, v2.16b
	VCMEQ V2.B16, V16.B16, V17.B16 // <--                                  // cmeq	v17.16b, v16.16b, v2.16b
	VADD  V3.B16, V7.B16, V7.B16   // <--                                  // add	v7.16b, v7.16b, v3.16b
	WORD  $0x6e273487              // VCMHI V7.B16, V4.B16, V7.B16         // cmhi	v7.16b, v4.16b, v7.16b
	VAND  V2.B16, V17.B16, V17.B16 // <--                                  // and	v17.16b, v17.16b, v2.16b
	VAND  V7.B16, V17.B16, V7.B16  // <--                                  // and	v7.16b, v17.16b, v7.16b
	VEOR  V16.B16, V7.B16, V7.B16  // <--                                  // eor	v7.16b, v7.16b, v16.16b
	WORD  $0x6e30a8e7              // VUMAXV V7.B16, V7                    // umaxv	b7, v7.16b
	FMOVS F7, R20                  // <--                                  // fmov	w20, s7
	CBZW  R20, LBB0_34             // <--                                  // cbz	w20, .LBB0_34
	JMP   LBB0_31                  // <--                                  // b	.LBB0_31

LBB0_36:
	CMP  $1, R5  // <--                                  // cmp	x5, #1
	BLT  LBB0_3  // <--                                  // b.lt	.LBB0_3
	MOVD ZR, R20 // <--                                  // mov	x20, xzr

LBB0_38:
	WORD  $0x38746895       // MOVBU (R4)(R20), R21                 // ldrb	w21, [x4, x20]
	WORD  $0x38746a76       // MOVBU (R19)(R20), R22                // ldrb	w22, [x19, x20]
	SUBW  $65, R21, R23     // <--                                  // sub	w23, w21, #65
	ORRW  $32, R21, R24     // <--                                  // orr	w24, w21, #0x20
	CMPW  $26, R23          // <--                                  // cmp	w23, #26
	SUBW  $65, R22, R23     // <--                                  // sub	w23, w22, #65
	CSELW LO, R24, R21, R21 // <--                                  // csel	w21, w24, w21, lo
	ORRW  $32, R22, R24     // <--                                  // orr	w24, w22, #0x20
	CMPW  $26, R23          // <--                                  // cmp	w23, #26
	CSELW LO, R24, R22, R22 // <--                                  // csel	w22, w24, w22, lo
	CMPW  R22, R21          // <--                                  // cmp	w21, w22
	BNE   LBB0_31           // <--                                  // b.ne	.LBB0_31
	ADD   $1, R20, R20      // <--                                  // add	x20, x20, #1
	CMP   R20, R5           // <--                                  // cmp	x5, x20
	BNE   LBB0_38           // <--                                  // b.ne	.LBB0_38
	JMP   LBB0_3            // <--                                  // b	.LBB0_3

LBB0_40:
	WORD  $0x0f0c84c6  // VSHRN $4, V6.H8, V6.B8               // shrn	v6.8b, v6.8h, #4
	FMOVD F6, R17      // <--                                  // fmov	x17, d6
	CBZ   R17, LBB0_51 // <--                                  // cbz	x17, .LBB0_51
	SUB   R12, R16, R8 // <--                                  // sub	x8, x16, x12
	ADD   $32, R8, R1  // <--                                  // add	x1, x8, #32
	JMP   LBB0_43      // <--                                  // b	.LBB0_43

LBB0_42:
	AND  $60, R3, R8  // <--                                  // and	x8, x3, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R17, R17 // <--                                  // bics	x17, x17, x8
	BEQ  LBB0_51      // <--                                  // b.eq	.LBB0_51

LBB0_43:
	RBIT R17, R8       // <--                                  // rbit	x8, x17
	CLZ  R8, R3        // <--                                  // clz	x3, x8
	ADD  R3>>2, R1, R8 // <--                                  // add	x8, x1, x3, lsr #2
	CMP  R9, R8        // <--                                  // cmp	x8, x9
	BHI  LBB0_42       // <--                                  // b.hi	.LBB0_42
	ADD  R8, R0, R4    // <--                                  // add	x4, x0, x8
	MOVD R7, R5        // <--                                  // mov	x5, x7
	MOVD R6, R19       // <--                                  // mov	x19, x6

LBB0_45:
	CMP   $15, R5                  // <--                                  // cmp	x5, #15
	BLE   LBB0_47                  // <--                                  // b.le	.LBB0_47
	WORD  $0x3cc10486              // FMOVQ.P 16(R4), F6                   // ldr	q6, [x4], #16
	SUB   $16, R5, R5              // <--                                  // sub	x5, x5, #16
	WORD  $0x3cc10667              // FMOVQ.P 16(R19), F7                  // ldr	q7, [x19], #16
	VEOR  V6.B16, V7.B16, V7.B16   // <--                                  // eor	v7.16b, v7.16b, v6.16b
	VORR  V2.B16, V6.B16, V6.B16   // <--                                  // orr	v6.16b, v6.16b, v2.16b
	VCMEQ V2.B16, V7.B16, V16.B16  // <--                                  // cmeq	v16.16b, v7.16b, v2.16b
	VADD  V3.B16, V6.B16, V6.B16   // <--                                  // add	v6.16b, v6.16b, v3.16b
	WORD  $0x6e263486              // VCMHI V6.B16, V4.B16, V6.B16         // cmhi	v6.16b, v4.16b, v6.16b
	VAND  V2.B16, V16.B16, V16.B16 // <--                                  // and	v16.16b, v16.16b, v2.16b
	VAND  V6.B16, V16.B16, V6.B16  // <--                                  // and	v6.16b, v16.16b, v6.16b
	VEOR  V7.B16, V6.B16, V6.B16   // <--                                  // eor	v6.16b, v6.16b, v7.16b
	WORD  $0x6e30a8c6              // VUMAXV V6.B16, V6                    // umaxv	b6, v6.16b
	FMOVS F6, R20                  // <--                                  // fmov	w20, s6
	CBZW  R20, LBB0_45             // <--                                  // cbz	w20, .LBB0_45
	JMP   LBB0_42                  // <--                                  // b	.LBB0_42

LBB0_47:
	CMP  $1, R5  // <--                                  // cmp	x5, #1
	BLT  LBB0_3  // <--                                  // b.lt	.LBB0_3
	MOVD ZR, R20 // <--                                  // mov	x20, xzr

LBB0_49:
	WORD  $0x38746895       // MOVBU (R4)(R20), R21                 // ldrb	w21, [x4, x20]
	WORD  $0x38746a76       // MOVBU (R19)(R20), R22                // ldrb	w22, [x19, x20]
	SUBW  $65, R21, R23     // <--                                  // sub	w23, w21, #65
	ORRW  $32, R21, R24     // <--                                  // orr	w24, w21, #0x20
	CMPW  $26, R23          // <--                                  // cmp	w23, #26
	SUBW  $65, R22, R23     // <--                                  // sub	w23, w22, #65
	CSELW LO, R24, R21, R21 // <--                                  // csel	w21, w24, w21, lo
	ORRW  $32, R22, R24     // <--                                  // orr	w24, w22, #0x20
	CMPW  $26, R23          // <--                                  // cmp	w23, #26
	CSELW LO, R24, R22, R22 // <--                                  // csel	w22, w24, w22, lo
	CMPW  R22, R21          // <--                                  // cmp	w21, w22
	BNE   LBB0_42           // <--                                  // b.ne	.LBB0_42
	ADD   $1, R20, R20      // <--                                  // add	x20, x20, #1
	CMP   R20, R5           // <--                                  // cmp	x5, x20
	BNE   LBB0_49           // <--                                  // b.ne	.LBB0_49
	JMP   LBB0_3            // <--                                  // b	.LBB0_3

LBB0_51:
	WORD  $0x0f0c84a5  // VSHRN $4, V5.H8, V5.B8               // shrn	v5.8b, v5.8h, #4
	FMOVD F5, R17      // <--                                  // fmov	x17, d5
	CBZ   R17, LBB0_62 // <--                                  // cbz	x17, .LBB0_62
	SUB   R12, R16, R8 // <--                                  // sub	x8, x16, x12
	ADD   $48, R8, R16 // <--                                  // add	x16, x8, #48
	JMP   LBB0_54      // <--                                  // b	.LBB0_54

LBB0_53:
	AND  $60, R1, R8  // <--                                  // and	x8, x1, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R17, R17 // <--                                  // bics	x17, x17, x8
	BEQ  LBB0_62      // <--                                  // b.eq	.LBB0_62

LBB0_54:
	RBIT R17, R8        // <--                                  // rbit	x8, x17
	CLZ  R8, R1         // <--                                  // clz	x1, x8
	ADD  R1>>2, R16, R8 // <--                                  // add	x8, x16, x1, lsr #2
	CMP  R9, R8         // <--                                  // cmp	x8, x9
	BHI  LBB0_53        // <--                                  // b.hi	.LBB0_53
	ADD  R8, R0, R3     // <--                                  // add	x3, x0, x8
	MOVD R7, R4         // <--                                  // mov	x4, x7
	MOVD R6, R5         // <--                                  // mov	x5, x6

LBB0_56:
	CMP   $15, R4                // <--                                  // cmp	x4, #15
	BLE   LBB0_58                // <--                                  // b.le	.LBB0_58
	WORD  $0x3cc10465            // FMOVQ.P 16(R3), F5                   // ldr	q5, [x3], #16
	SUB   $16, R4, R4            // <--                                  // sub	x4, x4, #16
	WORD  $0x3cc104a6            // FMOVQ.P 16(R5), F6                   // ldr	q6, [x5], #16
	VEOR  V5.B16, V6.B16, V6.B16 // <--                                  // eor	v6.16b, v6.16b, v5.16b
	VORR  V2.B16, V5.B16, V5.B16 // <--                                  // orr	v5.16b, v5.16b, v2.16b
	VCMEQ V2.B16, V6.B16, V7.B16 // <--                                  // cmeq	v7.16b, v6.16b, v2.16b
	VADD  V3.B16, V5.B16, V5.B16 // <--                                  // add	v5.16b, v5.16b, v3.16b
	WORD  $0x6e253485            // VCMHI V5.B16, V4.B16, V5.B16         // cmhi	v5.16b, v4.16b, v5.16b
	VAND  V2.B16, V7.B16, V7.B16 // <--                                  // and	v7.16b, v7.16b, v2.16b
	VAND  V5.B16, V7.B16, V5.B16 // <--                                  // and	v5.16b, v7.16b, v5.16b
	VEOR  V6.B16, V5.B16, V5.B16 // <--                                  // eor	v5.16b, v5.16b, v6.16b
	WORD  $0x6e30a8a5            // VUMAXV V5.B16, V5                    // umaxv	b5, v5.16b
	FMOVS F5, R19                // <--                                  // fmov	w19, s5
	CBZW  R19, LBB0_56           // <--                                  // cbz	w19, .LBB0_56
	JMP   LBB0_53                // <--                                  // b	.LBB0_53

LBB0_58:
	CMP  $1, R4  // <--                                  // cmp	x4, #1
	BLT  LBB0_3  // <--                                  // b.lt	.LBB0_3
	MOVD ZR, R19 // <--                                  // mov	x19, xzr

LBB0_60:
	WORD  $0x38736874       // MOVBU (R3)(R19), R20                 // ldrb	w20, [x3, x19]
	WORD  $0x387368b5       // MOVBU (R5)(R19), R21                 // ldrb	w21, [x5, x19]
	SUBW  $65, R20, R22     // <--                                  // sub	w22, w20, #65
	ORRW  $32, R20, R23     // <--                                  // orr	w23, w20, #0x20
	CMPW  $26, R22          // <--                                  // cmp	w22, #26
	SUBW  $65, R21, R22     // <--                                  // sub	w22, w21, #65
	CSELW LO, R23, R20, R20 // <--                                  // csel	w20, w23, w20, lo
	ORRW  $32, R21, R23     // <--                                  // orr	w23, w21, #0x20
	CMPW  $26, R22          // <--                                  // cmp	w22, #26
	CSELW LO, R23, R21, R21 // <--                                  // csel	w21, w23, w21, lo
	CMPW  R21, R20          // <--                                  // cmp	w20, w21
	BNE   LBB0_53           // <--                                  // b.ne	.LBB0_53
	ADD   $1, R19, R19      // <--                                  // add	x19, x19, #1
	CMP   R19, R4           // <--                                  // cmp	x4, x19
	BNE   LBB0_60           // <--                                  // b.ne	.LBB0_60
	JMP   LBB0_3            // <--                                  // b	.LBB0_3

LBB0_62:
	CMP  $128, R14     // <--                                  // cmp	x14, #128
	SUB  $64, R14, R17 // <--                                  // sub	x17, x14, #64
	BLT  LBB0_65       // <--                                  // b.lt	.LBB0_65
	ADD  $64, R13, R8  // <--                                  // add	x8, x13, #64
	MOVD R13, R16      // <--                                  // mov	x16, x13
	MOVD R17, R14      // <--                                  // mov	x14, x17
	CMP  R11, R8       // <--                                  // cmp	x8, x11
	BLS  LBB0_17       // <--                                  // b.ls	.LBB0_17
	JMP  LBB0_65       // <--                                  // b	.LBB0_65

LBB0_64:
	MOVD R14, R17 // <--                                  // mov	x17, x14
	MOVD R12, R13 // <--                                  // mov	x13, x12

LBB0_65:
	CMP  $32, R17     // <--                                  // cmp	x17, #32
	BLT  LBB0_95      // <--                                  // b.lt	.LBB0_95
	ADD  $32, R13, R8 // <--                                  // add	x8, x13, #32
	CMP  R11, R8      // <--                                  // cmp	x8, x11
	BHI  LBB0_95      // <--                                  // b.hi	.LBB0_95
	WORD $0x4f01e402  // VMOVI $32, V2.B16                    // movi	v2.16b, #32
	WORD $0x4f04e7e3  // VMOVI $159, V3.B16                   // movi	v3.16b, #159
	MOVW $15, R15     // <--                                  // mov	w15, #15
	WORD $0x4f00e744  // VMOVI $26, V4.B16                    // movi	v4.16b, #26

LBB0_68:
	WORD  $0xad4019a5             // FLDPQ (R13), (F5, F6)                // ldp	q5, q6, [x13]
	MOVD  R8, R14                 // <--                                  // mov	x14, x8
	VORR  V0.B16, V5.B16, V5.B16  // <--                                  // orr	v5.16b, v5.16b, v0.16b
	VORR  V0.B16, V6.B16, V7.B16  // <--                                  // orr	v7.16b, v6.16b, v0.16b
	VCMEQ V1.B16, V5.B16, V6.B16  // <--                                  // cmeq	v6.16b, v5.16b, v1.16b
	VCMEQ V1.B16, V7.B16, V5.B16  // <--                                  // cmeq	v5.16b, v7.16b, v1.16b
	VORR  V6.B16, V5.B16, V7.B16  // <--                                  // orr	v7.16b, v5.16b, v6.16b
	VDUP  V7.D[1], V16.D2         // <--                                  // dup	v16.2d, v7.d[1]
	VORR  V7.B16, V16.B16, V7.B16 // <--                                  // orr	v7.16b, v16.16b, v7.16b
	FMOVD F7, R16                 // <--                                  // fmov	x16, d7
	CBZ   R16, LBB0_93            // <--                                  // cbz	x16, .LBB0_93
	WORD  $0x0f0c84c6             // VSHRN $4, V6.H8, V6.B8               // shrn	v6.8b, v6.8h, #4
	FMOVD F6, R16                 // <--                                  // fmov	x16, d6
	CBZ   R16, LBB0_81            // <--                                  // cbz	x16, .LBB0_81
	SUB   R12, R13, R1            // <--                                  // sub	x1, x13, x12
	JMP   LBB0_72                 // <--                                  // b	.LBB0_72

LBB0_71:
	AND  $60, R3, R8  // <--                                  // and	x8, x3, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R16, R16 // <--                                  // bics	x16, x16, x8
	BEQ  LBB0_81      // <--                                  // b.eq	.LBB0_81

LBB0_72:
	RBIT R16, R8       // <--                                  // rbit	x8, x16
	CLZ  R8, R3        // <--                                  // clz	x3, x8
	ADDS R3>>2, R1, R8 // <--                                  // adds	x8, x1, x3, lsr #2
	BMI  LBB0_71       // <--                                  // b.mi	.LBB0_71
	CMP  R9, R8        // <--                                  // cmp	x8, x9
	BGT  LBB0_71       // <--                                  // b.gt	.LBB0_71
	ADD  R8, R0, R4    // <--                                  // add	x4, x0, x8
	MOVD R7, R5        // <--                                  // mov	x5, x7
	MOVD R6, R19       // <--                                  // mov	x19, x6

LBB0_75:
	CMP   $15, R5                  // <--                                  // cmp	x5, #15
	BLE   LBB0_77                  // <--                                  // b.le	.LBB0_77
	WORD  $0x3cc10486              // FMOVQ.P 16(R4), F6                   // ldr	q6, [x4], #16
	SUB   $16, R5, R5              // <--                                  // sub	x5, x5, #16
	WORD  $0x3cc10667              // FMOVQ.P 16(R19), F7                  // ldr	q7, [x19], #16
	VEOR  V6.B16, V7.B16, V7.B16   // <--                                  // eor	v7.16b, v7.16b, v6.16b
	VORR  V2.B16, V6.B16, V6.B16   // <--                                  // orr	v6.16b, v6.16b, v2.16b
	VCMEQ V2.B16, V7.B16, V16.B16  // <--                                  // cmeq	v16.16b, v7.16b, v2.16b
	VADD  V3.B16, V6.B16, V6.B16   // <--                                  // add	v6.16b, v6.16b, v3.16b
	WORD  $0x6e263486              // VCMHI V6.B16, V4.B16, V6.B16         // cmhi	v6.16b, v4.16b, v6.16b
	VAND  V2.B16, V16.B16, V16.B16 // <--                                  // and	v16.16b, v16.16b, v2.16b
	VAND  V6.B16, V16.B16, V6.B16  // <--                                  // and	v6.16b, v16.16b, v6.16b
	VEOR  V7.B16, V6.B16, V6.B16   // <--                                  // eor	v6.16b, v6.16b, v7.16b
	WORD  $0x6e30a8c6              // VUMAXV V6.B16, V6                    // umaxv	b6, v6.16b
	FMOVS F6, R20                  // <--                                  // fmov	w20, s6
	CBZW  R20, LBB0_75             // <--                                  // cbz	w20, .LBB0_75
	JMP   LBB0_71                  // <--                                  // b	.LBB0_71

LBB0_77:
	CMP  $1, R5  // <--                                  // cmp	x5, #1
	BLT  LBB0_3  // <--                                  // b.lt	.LBB0_3
	MOVD ZR, R20 // <--                                  // mov	x20, xzr

LBB0_79:
	WORD  $0x38746895       // MOVBU (R4)(R20), R21                 // ldrb	w21, [x4, x20]
	WORD  $0x38746a76       // MOVBU (R19)(R20), R22                // ldrb	w22, [x19, x20]
	SUBW  $65, R21, R23     // <--                                  // sub	w23, w21, #65
	ORRW  $32, R21, R24     // <--                                  // orr	w24, w21, #0x20
	CMPW  $26, R23          // <--                                  // cmp	w23, #26
	SUBW  $65, R22, R23     // <--                                  // sub	w23, w22, #65
	CSELW LO, R24, R21, R21 // <--                                  // csel	w21, w24, w21, lo
	ORRW  $32, R22, R24     // <--                                  // orr	w24, w22, #0x20
	CMPW  $26, R23          // <--                                  // cmp	w23, #26
	CSELW LO, R24, R22, R22 // <--                                  // csel	w22, w24, w22, lo
	CMPW  R22, R21          // <--                                  // cmp	w21, w22
	BNE   LBB0_71           // <--                                  // b.ne	.LBB0_71
	ADD   $1, R20, R20      // <--                                  // add	x20, x20, #1
	CMP   R20, R5           // <--                                  // cmp	x5, x20
	BNE   LBB0_79           // <--                                  // b.ne	.LBB0_79
	JMP   LBB0_3            // <--                                  // b	.LBB0_3

LBB0_81:
	WORD  $0x0f0c84a5  // VSHRN $4, V5.H8, V5.B8               // shrn	v5.8b, v5.8h, #4
	FMOVD F5, R16      // <--                                  // fmov	x16, d5
	CBZ   R16, LBB0_93 // <--                                  // cbz	x16, .LBB0_93
	SUB   R12, R13, R8 // <--                                  // sub	x8, x13, x12
	ADD   $16, R8, R13 // <--                                  // add	x13, x8, #16
	JMP   LBB0_84      // <--                                  // b	.LBB0_84

LBB0_83:
	AND  $60, R1, R8  // <--                                  // and	x8, x1, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R16, R16 // <--                                  // bics	x16, x16, x8
	BEQ  LBB0_93      // <--                                  // b.eq	.LBB0_93

LBB0_84:
	RBIT R16, R8        // <--                                  // rbit	x8, x16
	CLZ  R8, R1         // <--                                  // clz	x1, x8
	ADDS R1>>2, R13, R8 // <--                                  // adds	x8, x13, x1, lsr #2
	BMI  LBB0_83        // <--                                  // b.mi	.LBB0_83
	CMP  R9, R8         // <--                                  // cmp	x8, x9
	BGT  LBB0_83        // <--                                  // b.gt	.LBB0_83
	ADD  R8, R0, R3     // <--                                  // add	x3, x0, x8
	MOVD R7, R4         // <--                                  // mov	x4, x7
	MOVD R6, R5         // <--                                  // mov	x5, x6

LBB0_87:
	CMP   $15, R4                // <--                                  // cmp	x4, #15
	BLE   LBB0_89                // <--                                  // b.le	.LBB0_89
	WORD  $0x3cc10465            // FMOVQ.P 16(R3), F5                   // ldr	q5, [x3], #16
	SUB   $16, R4, R4            // <--                                  // sub	x4, x4, #16
	WORD  $0x3cc104a6            // FMOVQ.P 16(R5), F6                   // ldr	q6, [x5], #16
	VEOR  V5.B16, V6.B16, V6.B16 // <--                                  // eor	v6.16b, v6.16b, v5.16b
	VORR  V2.B16, V5.B16, V5.B16 // <--                                  // orr	v5.16b, v5.16b, v2.16b
	VCMEQ V2.B16, V6.B16, V7.B16 // <--                                  // cmeq	v7.16b, v6.16b, v2.16b
	VADD  V3.B16, V5.B16, V5.B16 // <--                                  // add	v5.16b, v5.16b, v3.16b
	WORD  $0x6e253485            // VCMHI V5.B16, V4.B16, V5.B16         // cmhi	v5.16b, v4.16b, v5.16b
	VAND  V2.B16, V7.B16, V7.B16 // <--                                  // and	v7.16b, v7.16b, v2.16b
	VAND  V5.B16, V7.B16, V5.B16 // <--                                  // and	v5.16b, v7.16b, v5.16b
	VEOR  V6.B16, V5.B16, V5.B16 // <--                                  // eor	v5.16b, v5.16b, v6.16b
	WORD  $0x6e30a8a5            // VUMAXV V5.B16, V5                    // umaxv	b5, v5.16b
	FMOVS F5, R19                // <--                                  // fmov	w19, s5
	CBZW  R19, LBB0_87           // <--                                  // cbz	w19, .LBB0_87
	JMP   LBB0_83                // <--                                  // b	.LBB0_83

LBB0_89:
	CMP  $1, R4  // <--                                  // cmp	x4, #1
	BLT  LBB0_3  // <--                                  // b.lt	.LBB0_3
	MOVD ZR, R19 // <--                                  // mov	x19, xzr

LBB0_91:
	WORD  $0x38736874       // MOVBU (R3)(R19), R20                 // ldrb	w20, [x3, x19]
	WORD  $0x387368b5       // MOVBU (R5)(R19), R21                 // ldrb	w21, [x5, x19]
	SUBW  $65, R20, R22     // <--                                  // sub	w22, w20, #65
	ORRW  $32, R20, R23     // <--                                  // orr	w23, w20, #0x20
	CMPW  $26, R22          // <--                                  // cmp	w22, #26
	SUBW  $65, R21, R22     // <--                                  // sub	w22, w21, #65
	CSELW LO, R23, R20, R20 // <--                                  // csel	w20, w23, w20, lo
	ORRW  $32, R21, R23     // <--                                  // orr	w23, w21, #0x20
	CMPW  $26, R22          // <--                                  // cmp	w22, #26
	CSELW LO, R23, R21, R21 // <--                                  // csel	w21, w23, w21, lo
	CMPW  R21, R20          // <--                                  // cmp	w20, w21
	BNE   LBB0_83           // <--                                  // b.ne	.LBB0_83
	ADD   $1, R19, R19      // <--                                  // add	x19, x19, #1
	CMP   R19, R4           // <--                                  // cmp	x4, x19
	BNE   LBB0_91           // <--                                  // b.ne	.LBB0_91
	JMP   LBB0_3            // <--                                  // b	.LBB0_3

LBB0_93:
	CMP  $64, R17      // <--                                  // cmp	x17, #64
	SUB  $32, R17, R16 // <--                                  // sub	x16, x17, #32
	BLT  LBB0_96       // <--                                  // b.lt	.LBB0_96
	ADD  $32, R14, R8  // <--                                  // add	x8, x14, #32
	MOVD R14, R13      // <--                                  // mov	x13, x14
	MOVD R16, R17      // <--                                  // mov	x17, x16
	CMP  R11, R8       // <--                                  // cmp	x8, x11
	BLS  LBB0_68       // <--                                  // b.ls	.LBB0_68
	JMP  LBB0_96       // <--                                  // b	.LBB0_96

LBB0_95:
	MOVD R17, R16 // <--                                  // mov	x16, x17
	MOVD R13, R14 // <--                                  // mov	x14, x13

LBB0_96:
	CMP  $1, R16     // <--                                  // cmp	x16, #1
	MOVD $-1, R8     // <--                                  // mov	x8, #-1
	BLT  LBB0_3      // <--                                  // b.lt	.LBB0_3
	CMP  R11, R14    // <--                                  // cmp	x14, x11
	BCS  LBB0_3      // <--                                  // b.hs	.LBB0_3
	WORD $0x4f01e400 // VMOVI $32, V0.B16                    // movi	v0.16b, #32
	WORD $0x4f04e7e1 // VMOVI $159, V1.B16                   // movi	v1.16b, #159
	WORD $0x4f00e742 // VMOVI $26, V2.B16                    // movi	v2.16b, #26

LBB0_99:
	WORD $0x394001c8  // MOVBU (R14), R8                      // ldrb	w8, [x14]
	ORRW R10, R8, R8  // <--                                  // orr	w8, w8, w10
	CMPW R2.UXTB, R8  // <--                                  // cmp	w8, w2, uxtb
	BNE  LBB0_105     // <--                                  // b.ne	.LBB0_105
	SUBS R12, R14, R8 // <--                                  // subs	x8, x14, x12
	BMI  LBB0_105     // <--                                  // b.mi	.LBB0_105
	CMP  R9, R8       // <--                                  // cmp	x8, x9
	BGT  LBB0_105     // <--                                  // b.gt	.LBB0_105
	ADD  R8, R0, R13  // <--                                  // add	x13, x0, x8
	MOVD R7, R15      // <--                                  // mov	x15, x7
	MOVD R6, R17      // <--                                  // mov	x17, x6

LBB0_103:
	CMP   $15, R15               // <--                                  // cmp	x15, #15
	BLE   LBB0_107               // <--                                  // b.le	.LBB0_107
	WORD  $0x3cc105a3            // FMOVQ.P 16(R13), F3                  // ldr	q3, [x13], #16
	SUB   $16, R15, R15          // <--                                  // sub	x15, x15, #16
	WORD  $0x3cc10624            // FMOVQ.P 16(R17), F4                  // ldr	q4, [x17], #16
	VEOR  V3.B16, V4.B16, V4.B16 // <--                                  // eor	v4.16b, v4.16b, v3.16b
	VORR  V0.B16, V3.B16, V3.B16 // <--                                  // orr	v3.16b, v3.16b, v0.16b
	VCMEQ V0.B16, V4.B16, V5.B16 // <--                                  // cmeq	v5.16b, v4.16b, v0.16b
	VADD  V1.B16, V3.B16, V3.B16 // <--                                  // add	v3.16b, v3.16b, v1.16b
	WORD  $0x6e233443            // VCMHI V3.B16, V2.B16, V3.B16         // cmhi	v3.16b, v2.16b, v3.16b
	VAND  V0.B16, V5.B16, V5.B16 // <--                                  // and	v5.16b, v5.16b, v0.16b
	VAND  V3.B16, V5.B16, V3.B16 // <--                                  // and	v3.16b, v5.16b, v3.16b
	VEOR  V4.B16, V3.B16, V3.B16 // <--                                  // eor	v3.16b, v3.16b, v4.16b
	WORD  $0x6e30a863            // VUMAXV V3.B16, V3                    // umaxv	b3, v3.16b
	FMOVS F3, R1                 // <--                                  // fmov	w1, s3
	CBZW  R1, LBB0_103           // <--                                  // cbz	w1, .LBB0_103

LBB0_105:
	CMP  $2, R16      // <--                                  // cmp	x16, #2
	MOVD $-1, R8      // <--                                  // mov	x8, #-1
	BLT  LBB0_3       // <--                                  // b.lt	.LBB0_3
	ADD  $1, R14, R14 // <--                                  // add	x14, x14, #1
	SUB  $1, R16, R16 // <--                                  // sub	x16, x16, #1
	CMP  R11, R14     // <--                                  // cmp	x14, x11
	BCC  LBB0_99      // <--                                  // b.lo	.LBB0_99
	JMP  LBB0_3       // <--                                  // b	.LBB0_3

LBB0_107:
	CMP  $1, R15 // <--                                  // cmp	x15, #1
	BLT  LBB0_3  // <--                                  // b.lt	.LBB0_3
	MOVD ZR, R1  // <--                                  // mov	x1, xzr

LBB0_109:
	WORD  $0x386169a3     // MOVBU (R13)(R1), R3                  // ldrb	w3, [x13, x1]
	WORD  $0x38616a24     // MOVBU (R17)(R1), R4                  // ldrb	w4, [x17, x1]
	SUBW  $65, R3, R5     // <--                                  // sub	w5, w3, #65
	ORRW  $32, R3, R19    // <--                                  // orr	w19, w3, #0x20
	CMPW  $26, R5         // <--                                  // cmp	w5, #26
	SUBW  $65, R4, R5     // <--                                  // sub	w5, w4, #65
	CSELW LO, R19, R3, R3 // <--                                  // csel	w3, w19, w3, lo
	ORRW  $32, R4, R19    // <--                                  // orr	w19, w4, #0x20
	CMPW  $26, R5         // <--                                  // cmp	w5, #26
	CSELW LO, R19, R4, R4 // <--                                  // csel	w4, w19, w4, lo
	CMPW  R4, R3          // <--                                  // cmp	w3, w4
	BNE   LBB0_105        // <--                                  // b.ne	.LBB0_105
	ADD   $1, R1, R1      // <--                                  // add	x1, x1, #1
	CMP   R1, R15         // <--                                  // cmp	x15, x1
	BNE   LBB0_109        // <--                                  // b.ne	.LBB0_109
	JMP   LBB0_3          // <--                                  // b	.LBB0_3

TEXT ·SearcherIndexFoldMemchr(SB), NOSPLIT, $0-72
	MOVD haystack+0(FP), R0
	MOVD haystack_len+8(FP), R1
	MOVB rare1+16(FP), R2
	MOVD off1+24(FP), R3
	MOVB rare2+32(FP), R4
	MOVD off2+40(FP), R5
	MOVD norm_needle+48(FP), R6
	MOVD needle_len+56(FP), R7
	NOP                         // (skipped)                            // stp	x24, x23, [sp, #-48]!
	NOP                         // (skipped)                            // stp	x22, x21, [sp, #16]
	NOP                         // (skipped)                            // stp	x20, x19, [sp, #32]
	CBZ  R7, LBB1_13            // <--                                  // cbz	x7, .LBB1_13
	SUBS R7, R1, R9             // <--                                  // subs	x9, x1, x7
	BGE  LBB1_4                 // <--                                  // b.ge	.LBB1_4
	MOVD $-1, R8                // <--                                  // mov	x8, #-1

LBB1_3:
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+64(FP) // <--
	RET                 // <--                                  // ret

LBB1_4:
	CMP  $15, R1    // <--                                  // cmp	x1, #15
	BGT  LBB1_14    // <--                                  // b.gt	.LBB1_14
	CMP  $1, R7     // <--                                  // cmp	x7, #1
	BLT  LBB1_13    // <--                                  // b.lt	.LBB1_13
	MOVD ZR, R8     // <--                                  // mov	x8, xzr
	ADD  $1, R9, R9 // <--                                  // add	x9, x9, #1

LBB1_7:
	MOVD ZR, R10 // <--                                  // mov	x10, xzr

LBB1_8:
	WORD  $0x386a680c       // MOVBU (R0)(R10), R12                 // ldrb	w12, [x0, x10]
	WORD  $0x386a68cb       // MOVBU (R6)(R10), R11                 // ldrb	w11, [x6, x10]
	ADD   $1, R10, R10      // <--                                  // add	x10, x10, #1
	SUBW  $65, R12, R13     // <--                                  // sub	w13, w12, #65
	ORRW  $32, R12, R14     // <--                                  // orr	w14, w12, #0x20
	CMPW  $26, R13          // <--                                  // cmp	w13, #26
	CSELW LO, R14, R12, R12 // <--                                  // csel	w12, w14, w12, lo
	CMP   R7, R10           // <--                                  // cmp	x10, x7
	BGE   LBB1_10           // <--                                  // b.ge	.LBB1_10
	CMPW  R11, R12          // <--                                  // cmp	w12, w11
	BEQ   LBB1_8            // <--                                  // b.eq	.LBB1_8

LBB1_10:
	CMPW R11, R12       // <--                                  // cmp	w12, w11
	BEQ  LBB1_3         // <--                                  // b.eq	.LBB1_3
	ADD  $1, R8, R8     // <--                                  // add	x8, x8, #1
	ADD  $1, R0, R0     // <--                                  // add	x0, x0, #1
	CMP  R9, R8         // <--                                  // cmp	x8, x9
	BNE  LBB1_7         // <--                                  // b.ne	.LBB1_7
	MOVD $-1, R8        // <--                                  // mov	x8, #-1
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+64(FP) // <--
	RET                 // <--                                  // ret

LBB1_13:
	MOVD ZR, R8         // <--                                  // mov	x8, xzr
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #32]
	MOVD R8, R0         // <--                                  // mov	x0, x8
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #16]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp], #48
	MOVD R0, ret+64(FP) // <--
	RET                 // <--                                  // ret

LBB1_14:
	SUBW  $97, R2, R8     // <--                                  // sub	w8, w2, #97
	VDUP  R2, V1.B16      // <--                                  // dup	v1.16b, w2
	ADD   $1, R9, R14     // <--                                  // add	x14, x9, #1
	ANDW  $255, R8, R8    // <--                                  // and	w8, w8, #0xff
	ADD   R1, R0, R11     // <--                                  // add	x11, x0, x1
	ADD   R3, R0, R12     // <--                                  // add	x12, x0, x3
	CMPW  $26, R8         // <--                                  // cmp	w8, #26
	MOVW  $32, R8         // <--                                  // mov	w8, #32
	CSELW LO, R8, ZR, R10 // <--                                  // csel	w10, w8, wzr, lo
	CMP   $63, R9         // <--                                  // cmp	x9, #63
	VDUP  R10, V0.B16     // <--                                  // dup	v0.16b, w10
	BLT   LBB1_64         // <--                                  // b.lt	.LBB1_64
	ADD   $64, R12, R8    // <--                                  // add	x8, x12, #64
	CMP   R11, R8         // <--                                  // cmp	x8, x11
	BHI   LBB1_64         // <--                                  // b.hi	.LBB1_64
	WORD  $0x4f01e402     // VMOVI $32, V2.B16                    // movi	v2.16b, #32
	MOVW  $15, R15        // <--                                  // mov	w15, #15
	MOVD  R12, R16        // <--                                  // mov	x16, x12

LBB1_17:
	WORD  $0xad401203             // FLDPQ (R16), (F3, F4)                // ldp	q3, q4, [x16]
	MOVD  R8, R13                 // <--                                  // mov	x13, x8
	WORD  $0xad411a05             // FLDPQ 32(R16), (F5, F6)              // ldp	q5, q6, [x16, #32]
	VORR  V0.B16, V3.B16, V3.B16  // <--                                  // orr	v3.16b, v3.16b, v0.16b
	VORR  V0.B16, V4.B16, V4.B16  // <--                                  // orr	v4.16b, v4.16b, v0.16b
	VORR  V0.B16, V5.B16, V7.B16  // <--                                  // orr	v7.16b, v5.16b, v0.16b
	VORR  V0.B16, V6.B16, V16.B16 // <--                                  // orr	v16.16b, v6.16b, v0.16b
	VCMEQ V1.B16, V3.B16, V6.B16  // <--                                  // cmeq	v6.16b, v3.16b, v1.16b
	VCMEQ V1.B16, V4.B16, V5.B16  // <--                                  // cmeq	v5.16b, v4.16b, v1.16b
	VCMEQ V1.B16, V7.B16, V4.B16  // <--                                  // cmeq	v4.16b, v7.16b, v1.16b
	VCMEQ V1.B16, V16.B16, V3.B16 // <--                                  // cmeq	v3.16b, v16.16b, v1.16b
	VORR  V6.B16, V5.B16, V7.B16  // <--                                  // orr	v7.16b, v5.16b, v6.16b
	VORR  V3.B16, V4.B16, V16.B16 // <--                                  // orr	v16.16b, v4.16b, v3.16b
	VORR  V16.B16, V7.B16, V7.B16 // <--                                  // orr	v7.16b, v7.16b, v16.16b
	VDUP  V7.D[1], V16.D2         // <--                                  // dup	v16.2d, v7.d[1]
	VORR  V7.B16, V16.B16, V7.B16 // <--                                  // orr	v7.16b, v16.16b, v7.16b
	FMOVD F7, R17                 // <--                                  // fmov	x17, d7
	CBZ   R17, LBB1_62            // <--                                  // cbz	x17, .LBB1_62
	WORD  $0x0f0c84c6             // VSHRN $4, V6.H8, V6.B8               // shrn	v6.8b, v6.8h, #4
	FMOVD F6, R17                 // <--                                  // fmov	x17, d6
	CBZ   R17, LBB1_29            // <--                                  // cbz	x17, .LBB1_29
	SUB   R12, R16, R1            // <--                                  // sub	x1, x16, x12
	JMP   LBB1_21                 // <--                                  // b	.LBB1_21

LBB1_20:
	AND  $60, R3, R8  // <--                                  // and	x8, x3, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R17, R17 // <--                                  // bics	x17, x17, x8
	BEQ  LBB1_29      // <--                                  // b.eq	.LBB1_29

LBB1_21:
	RBIT R17, R8       // <--                                  // rbit	x8, x17
	CLZ  R8, R3        // <--                                  // clz	x3, x8
	ADD  R3>>2, R1, R8 // <--                                  // add	x8, x1, x3, lsr #2
	CMP  R9, R8        // <--                                  // cmp	x8, x9
	BHI  LBB1_20       // <--                                  // b.hi	.LBB1_20
	ADD  R8, R0, R4    // <--                                  // add	x4, x0, x8
	MOVD R7, R5        // <--                                  // mov	x5, x7
	MOVD R6, R19       // <--                                  // mov	x19, x6

LBB1_23:
	CMP   $15, R5                // <--                                  // cmp	x5, #15
	BLE   LBB1_25                // <--                                  // b.le	.LBB1_25
	WORD  $0x3cc10486            // FMOVQ.P 16(R4), F6                   // ldr	q6, [x4], #16
	SUB   $16, R5, R5            // <--                                  // sub	x5, x5, #16
	WORD  $0x3cc10667            // FMOVQ.P 16(R19), F7                  // ldr	q7, [x19], #16
	VORR  V2.B16, V6.B16, V6.B16 // <--                                  // orr	v6.16b, v6.16b, v2.16b
	VEOR  V7.B16, V6.B16, V6.B16 // <--                                  // eor	v6.16b, v6.16b, v7.16b
	WORD  $0x6e30a8c6            // VUMAXV V6.B16, V6                    // umaxv	b6, v6.16b
	FMOVS F6, R20                // <--                                  // fmov	w20, s6
	CBZW  R20, LBB1_23           // <--                                  // cbz	w20, .LBB1_23
	JMP   LBB1_20                // <--                                  // b	.LBB1_20

LBB1_25:
	CMP  $1, R5  // <--                                  // cmp	x5, #1
	BLT  LBB1_3  // <--                                  // b.lt	.LBB1_3
	MOVD ZR, R20 // <--                                  // mov	x20, xzr

LBB1_27:
	WORD  $0x38746895       // MOVBU (R4)(R20), R21                 // ldrb	w21, [x4, x20]
	WORD  $0x38746a77       // MOVBU (R19)(R20), R23                // ldrb	w23, [x19, x20]
	SUBW  $65, R21, R22     // <--                                  // sub	w22, w21, #65
	ORRW  $32, R21, R24     // <--                                  // orr	w24, w21, #0x20
	CMPW  $26, R22          // <--                                  // cmp	w22, #26
	CSELW LO, R24, R21, R21 // <--                                  // csel	w21, w24, w21, lo
	CMPW  R23, R21          // <--                                  // cmp	w21, w23
	BNE   LBB1_20           // <--                                  // b.ne	.LBB1_20
	ADD   $1, R20, R20      // <--                                  // add	x20, x20, #1
	CMP   R20, R5           // <--                                  // cmp	x5, x20
	BNE   LBB1_27           // <--                                  // b.ne	.LBB1_27
	JMP   LBB1_3            // <--                                  // b	.LBB1_3

LBB1_29:
	WORD  $0x0f0c84a5  // VSHRN $4, V5.H8, V5.B8               // shrn	v5.8b, v5.8h, #4
	FMOVD F5, R17      // <--                                  // fmov	x17, d5
	CBZ   R17, LBB1_40 // <--                                  // cbz	x17, .LBB1_40
	SUB   R12, R16, R8 // <--                                  // sub	x8, x16, x12
	ADD   $16, R8, R1  // <--                                  // add	x1, x8, #16
	JMP   LBB1_32      // <--                                  // b	.LBB1_32

LBB1_31:
	AND  $60, R3, R8  // <--                                  // and	x8, x3, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R17, R17 // <--                                  // bics	x17, x17, x8
	BEQ  LBB1_40      // <--                                  // b.eq	.LBB1_40

LBB1_32:
	RBIT R17, R8       // <--                                  // rbit	x8, x17
	CLZ  R8, R3        // <--                                  // clz	x3, x8
	ADD  R3>>2, R1, R8 // <--                                  // add	x8, x1, x3, lsr #2
	CMP  R9, R8        // <--                                  // cmp	x8, x9
	BHI  LBB1_31       // <--                                  // b.hi	.LBB1_31
	ADD  R8, R0, R4    // <--                                  // add	x4, x0, x8
	MOVD R7, R5        // <--                                  // mov	x5, x7
	MOVD R6, R19       // <--                                  // mov	x19, x6

LBB1_34:
	CMP   $15, R5                // <--                                  // cmp	x5, #15
	BLE   LBB1_36                // <--                                  // b.le	.LBB1_36
	WORD  $0x3cc10485            // FMOVQ.P 16(R4), F5                   // ldr	q5, [x4], #16
	SUB   $16, R5, R5            // <--                                  // sub	x5, x5, #16
	WORD  $0x3cc10666            // FMOVQ.P 16(R19), F6                  // ldr	q6, [x19], #16
	VORR  V2.B16, V5.B16, V5.B16 // <--                                  // orr	v5.16b, v5.16b, v2.16b
	VEOR  V6.B16, V5.B16, V5.B16 // <--                                  // eor	v5.16b, v5.16b, v6.16b
	WORD  $0x6e30a8a5            // VUMAXV V5.B16, V5                    // umaxv	b5, v5.16b
	FMOVS F5, R20                // <--                                  // fmov	w20, s5
	CBZW  R20, LBB1_34           // <--                                  // cbz	w20, .LBB1_34
	JMP   LBB1_31                // <--                                  // b	.LBB1_31

LBB1_36:
	CMP  $1, R5  // <--                                  // cmp	x5, #1
	BLT  LBB1_3  // <--                                  // b.lt	.LBB1_3
	MOVD ZR, R20 // <--                                  // mov	x20, xzr

LBB1_38:
	WORD  $0x38746895       // MOVBU (R4)(R20), R21                 // ldrb	w21, [x4, x20]
	WORD  $0x38746a77       // MOVBU (R19)(R20), R23                // ldrb	w23, [x19, x20]
	SUBW  $65, R21, R22     // <--                                  // sub	w22, w21, #65
	ORRW  $32, R21, R24     // <--                                  // orr	w24, w21, #0x20
	CMPW  $26, R22          // <--                                  // cmp	w22, #26
	CSELW LO, R24, R21, R21 // <--                                  // csel	w21, w24, w21, lo
	CMPW  R23, R21          // <--                                  // cmp	w21, w23
	BNE   LBB1_31           // <--                                  // b.ne	.LBB1_31
	ADD   $1, R20, R20      // <--                                  // add	x20, x20, #1
	CMP   R20, R5           // <--                                  // cmp	x5, x20
	BNE   LBB1_38           // <--                                  // b.ne	.LBB1_38
	JMP   LBB1_3            // <--                                  // b	.LBB1_3

LBB1_40:
	WORD  $0x0f0c8484  // VSHRN $4, V4.H8, V4.B8               // shrn	v4.8b, v4.8h, #4
	FMOVD F4, R17      // <--                                  // fmov	x17, d4
	CBZ   R17, LBB1_51 // <--                                  // cbz	x17, .LBB1_51
	SUB   R12, R16, R8 // <--                                  // sub	x8, x16, x12
	ADD   $32, R8, R1  // <--                                  // add	x1, x8, #32
	JMP   LBB1_43      // <--                                  // b	.LBB1_43

LBB1_42:
	AND  $60, R3, R8  // <--                                  // and	x8, x3, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R17, R17 // <--                                  // bics	x17, x17, x8
	BEQ  LBB1_51      // <--                                  // b.eq	.LBB1_51

LBB1_43:
	RBIT R17, R8       // <--                                  // rbit	x8, x17
	CLZ  R8, R3        // <--                                  // clz	x3, x8
	ADD  R3>>2, R1, R8 // <--                                  // add	x8, x1, x3, lsr #2
	CMP  R9, R8        // <--                                  // cmp	x8, x9
	BHI  LBB1_42       // <--                                  // b.hi	.LBB1_42
	ADD  R8, R0, R4    // <--                                  // add	x4, x0, x8
	MOVD R7, R5        // <--                                  // mov	x5, x7
	MOVD R6, R19       // <--                                  // mov	x19, x6

LBB1_45:
	CMP   $15, R5                // <--                                  // cmp	x5, #15
	BLE   LBB1_47                // <--                                  // b.le	.LBB1_47
	WORD  $0x3cc10484            // FMOVQ.P 16(R4), F4                   // ldr	q4, [x4], #16
	SUB   $16, R5, R5            // <--                                  // sub	x5, x5, #16
	WORD  $0x3cc10665            // FMOVQ.P 16(R19), F5                  // ldr	q5, [x19], #16
	VORR  V2.B16, V4.B16, V4.B16 // <--                                  // orr	v4.16b, v4.16b, v2.16b
	VEOR  V5.B16, V4.B16, V4.B16 // <--                                  // eor	v4.16b, v4.16b, v5.16b
	WORD  $0x6e30a884            // VUMAXV V4.B16, V4                    // umaxv	b4, v4.16b
	FMOVS F4, R20                // <--                                  // fmov	w20, s4
	CBZW  R20, LBB1_45           // <--                                  // cbz	w20, .LBB1_45
	JMP   LBB1_42                // <--                                  // b	.LBB1_42

LBB1_47:
	CMP  $1, R5  // <--                                  // cmp	x5, #1
	BLT  LBB1_3  // <--                                  // b.lt	.LBB1_3
	MOVD ZR, R20 // <--                                  // mov	x20, xzr

LBB1_49:
	WORD  $0x38746895       // MOVBU (R4)(R20), R21                 // ldrb	w21, [x4, x20]
	WORD  $0x38746a77       // MOVBU (R19)(R20), R23                // ldrb	w23, [x19, x20]
	SUBW  $65, R21, R22     // <--                                  // sub	w22, w21, #65
	ORRW  $32, R21, R24     // <--                                  // orr	w24, w21, #0x20
	CMPW  $26, R22          // <--                                  // cmp	w22, #26
	CSELW LO, R24, R21, R21 // <--                                  // csel	w21, w24, w21, lo
	CMPW  R23, R21          // <--                                  // cmp	w21, w23
	BNE   LBB1_42           // <--                                  // b.ne	.LBB1_42
	ADD   $1, R20, R20      // <--                                  // add	x20, x20, #1
	CMP   R20, R5           // <--                                  // cmp	x5, x20
	BNE   LBB1_49           // <--                                  // b.ne	.LBB1_49
	JMP   LBB1_3            // <--                                  // b	.LBB1_3

LBB1_51:
	WORD  $0x0f0c8463  // VSHRN $4, V3.H8, V3.B8               // shrn	v3.8b, v3.8h, #4
	FMOVD F3, R17      // <--                                  // fmov	x17, d3
	CBZ   R17, LBB1_62 // <--                                  // cbz	x17, .LBB1_62
	SUB   R12, R16, R8 // <--                                  // sub	x8, x16, x12
	ADD   $48, R8, R16 // <--                                  // add	x16, x8, #48
	JMP   LBB1_54      // <--                                  // b	.LBB1_54

LBB1_53:
	AND  $60, R1, R8  // <--                                  // and	x8, x1, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R17, R17 // <--                                  // bics	x17, x17, x8
	BEQ  LBB1_62      // <--                                  // b.eq	.LBB1_62

LBB1_54:
	RBIT R17, R8        // <--                                  // rbit	x8, x17
	CLZ  R8, R1         // <--                                  // clz	x1, x8
	ADD  R1>>2, R16, R8 // <--                                  // add	x8, x16, x1, lsr #2
	CMP  R9, R8         // <--                                  // cmp	x8, x9
	BHI  LBB1_53        // <--                                  // b.hi	.LBB1_53
	ADD  R8, R0, R3     // <--                                  // add	x3, x0, x8
	MOVD R7, R4         // <--                                  // mov	x4, x7
	MOVD R6, R5         // <--                                  // mov	x5, x6

LBB1_56:
	CMP   $15, R4                // <--                                  // cmp	x4, #15
	BLE   LBB1_58                // <--                                  // b.le	.LBB1_58
	WORD  $0x3cc10463            // FMOVQ.P 16(R3), F3                   // ldr	q3, [x3], #16
	SUB   $16, R4, R4            // <--                                  // sub	x4, x4, #16
	WORD  $0x3cc104a4            // FMOVQ.P 16(R5), F4                   // ldr	q4, [x5], #16
	VORR  V2.B16, V3.B16, V3.B16 // <--                                  // orr	v3.16b, v3.16b, v2.16b
	VEOR  V4.B16, V3.B16, V3.B16 // <--                                  // eor	v3.16b, v3.16b, v4.16b
	WORD  $0x6e30a863            // VUMAXV V3.B16, V3                    // umaxv	b3, v3.16b
	FMOVS F3, R19                // <--                                  // fmov	w19, s3
	CBZW  R19, LBB1_56           // <--                                  // cbz	w19, .LBB1_56
	JMP   LBB1_53                // <--                                  // b	.LBB1_53

LBB1_58:
	CMP  $1, R4  // <--                                  // cmp	x4, #1
	BLT  LBB1_3  // <--                                  // b.lt	.LBB1_3
	MOVD ZR, R19 // <--                                  // mov	x19, xzr

LBB1_60:
	WORD  $0x38736874       // MOVBU (R3)(R19), R20                 // ldrb	w20, [x3, x19]
	WORD  $0x387368b6       // MOVBU (R5)(R19), R22                 // ldrb	w22, [x5, x19]
	SUBW  $65, R20, R21     // <--                                  // sub	w21, w20, #65
	ORRW  $32, R20, R23     // <--                                  // orr	w23, w20, #0x20
	CMPW  $26, R21          // <--                                  // cmp	w21, #26
	CSELW LO, R23, R20, R20 // <--                                  // csel	w20, w23, w20, lo
	CMPW  R22, R20          // <--                                  // cmp	w20, w22
	BNE   LBB1_53           // <--                                  // b.ne	.LBB1_53
	ADD   $1, R19, R19      // <--                                  // add	x19, x19, #1
	CMP   R19, R4           // <--                                  // cmp	x4, x19
	BNE   LBB1_60           // <--                                  // b.ne	.LBB1_60
	JMP   LBB1_3            // <--                                  // b	.LBB1_3

LBB1_62:
	CMP  $128, R14     // <--                                  // cmp	x14, #128
	SUB  $64, R14, R17 // <--                                  // sub	x17, x14, #64
	BLT  LBB1_65       // <--                                  // b.lt	.LBB1_65
	ADD  $64, R13, R8  // <--                                  // add	x8, x13, #64
	MOVD R13, R16      // <--                                  // mov	x16, x13
	MOVD R17, R14      // <--                                  // mov	x14, x17
	CMP  R11, R8       // <--                                  // cmp	x8, x11
	BLS  LBB1_17       // <--                                  // b.ls	.LBB1_17
	JMP  LBB1_65       // <--                                  // b	.LBB1_65

LBB1_64:
	MOVD R14, R17 // <--                                  // mov	x17, x14
	MOVD R12, R13 // <--                                  // mov	x13, x12

LBB1_65:
	CMP  $32, R17     // <--                                  // cmp	x17, #32
	BLT  LBB1_95      // <--                                  // b.lt	.LBB1_95
	ADD  $32, R13, R8 // <--                                  // add	x8, x13, #32
	CMP  R11, R8      // <--                                  // cmp	x8, x11
	BHI  LBB1_95      // <--                                  // b.hi	.LBB1_95
	WORD $0x4f01e402  // VMOVI $32, V2.B16                    // movi	v2.16b, #32
	MOVW $15, R15     // <--                                  // mov	w15, #15

LBB1_68:
	WORD  $0xad4011a3            // FLDPQ (R13), (F3, F4)                // ldp	q3, q4, [x13]
	MOVD  R8, R14                // <--                                  // mov	x14, x8
	VORR  V0.B16, V3.B16, V3.B16 // <--                                  // orr	v3.16b, v3.16b, v0.16b
	VORR  V0.B16, V4.B16, V5.B16 // <--                                  // orr	v5.16b, v4.16b, v0.16b
	VCMEQ V1.B16, V3.B16, V4.B16 // <--                                  // cmeq	v4.16b, v3.16b, v1.16b
	VCMEQ V1.B16, V5.B16, V3.B16 // <--                                  // cmeq	v3.16b, v5.16b, v1.16b
	VORR  V4.B16, V3.B16, V5.B16 // <--                                  // orr	v5.16b, v3.16b, v4.16b
	VDUP  V5.D[1], V6.D2         // <--                                  // dup	v6.2d, v5.d[1]
	VORR  V5.B16, V6.B16, V5.B16 // <--                                  // orr	v5.16b, v6.16b, v5.16b
	FMOVD F5, R16                // <--                                  // fmov	x16, d5
	CBZ   R16, LBB1_93           // <--                                  // cbz	x16, .LBB1_93
	WORD  $0x0f0c8484            // VSHRN $4, V4.H8, V4.B8               // shrn	v4.8b, v4.8h, #4
	FMOVD F4, R16                // <--                                  // fmov	x16, d4
	CBZ   R16, LBB1_81           // <--                                  // cbz	x16, .LBB1_81
	SUB   R12, R13, R1           // <--                                  // sub	x1, x13, x12
	JMP   LBB1_72                // <--                                  // b	.LBB1_72

LBB1_71:
	AND  $60, R3, R8  // <--                                  // and	x8, x3, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R16, R16 // <--                                  // bics	x16, x16, x8
	BEQ  LBB1_81      // <--                                  // b.eq	.LBB1_81

LBB1_72:
	RBIT R16, R8       // <--                                  // rbit	x8, x16
	CLZ  R8, R3        // <--                                  // clz	x3, x8
	ADDS R3>>2, R1, R8 // <--                                  // adds	x8, x1, x3, lsr #2
	BMI  LBB1_71       // <--                                  // b.mi	.LBB1_71
	CMP  R9, R8        // <--                                  // cmp	x8, x9
	BGT  LBB1_71       // <--                                  // b.gt	.LBB1_71
	ADD  R8, R0, R4    // <--                                  // add	x4, x0, x8
	MOVD R7, R5        // <--                                  // mov	x5, x7
	MOVD R6, R19       // <--                                  // mov	x19, x6

LBB1_75:
	CMP   $15, R5                // <--                                  // cmp	x5, #15
	BLE   LBB1_77                // <--                                  // b.le	.LBB1_77
	WORD  $0x3cc10484            // FMOVQ.P 16(R4), F4                   // ldr	q4, [x4], #16
	SUB   $16, R5, R5            // <--                                  // sub	x5, x5, #16
	WORD  $0x3cc10665            // FMOVQ.P 16(R19), F5                  // ldr	q5, [x19], #16
	VORR  V2.B16, V4.B16, V4.B16 // <--                                  // orr	v4.16b, v4.16b, v2.16b
	VEOR  V5.B16, V4.B16, V4.B16 // <--                                  // eor	v4.16b, v4.16b, v5.16b
	WORD  $0x6e30a884            // VUMAXV V4.B16, V4                    // umaxv	b4, v4.16b
	FMOVS F4, R20                // <--                                  // fmov	w20, s4
	CBZW  R20, LBB1_75           // <--                                  // cbz	w20, .LBB1_75
	JMP   LBB1_71                // <--                                  // b	.LBB1_71

LBB1_77:
	CMP  $1, R5  // <--                                  // cmp	x5, #1
	BLT  LBB1_3  // <--                                  // b.lt	.LBB1_3
	MOVD ZR, R20 // <--                                  // mov	x20, xzr

LBB1_79:
	WORD  $0x38746895       // MOVBU (R4)(R20), R21                 // ldrb	w21, [x4, x20]
	WORD  $0x38746a77       // MOVBU (R19)(R20), R23                // ldrb	w23, [x19, x20]
	SUBW  $65, R21, R22     // <--                                  // sub	w22, w21, #65
	ORRW  $32, R21, R24     // <--                                  // orr	w24, w21, #0x20
	CMPW  $26, R22          // <--                                  // cmp	w22, #26
	CSELW LO, R24, R21, R21 // <--                                  // csel	w21, w24, w21, lo
	CMPW  R23, R21          // <--                                  // cmp	w21, w23
	BNE   LBB1_71           // <--                                  // b.ne	.LBB1_71
	ADD   $1, R20, R20      // <--                                  // add	x20, x20, #1
	CMP   R20, R5           // <--                                  // cmp	x5, x20
	BNE   LBB1_79           // <--                                  // b.ne	.LBB1_79
	JMP   LBB1_3            // <--                                  // b	.LBB1_3

LBB1_81:
	WORD  $0x0f0c8463  // VSHRN $4, V3.H8, V3.B8               // shrn	v3.8b, v3.8h, #4
	FMOVD F3, R16      // <--                                  // fmov	x16, d3
	CBZ   R16, LBB1_93 // <--                                  // cbz	x16, .LBB1_93
	SUB   R12, R13, R8 // <--                                  // sub	x8, x13, x12
	ADD   $16, R8, R13 // <--                                  // add	x13, x8, #16
	JMP   LBB1_84      // <--                                  // b	.LBB1_84

LBB1_83:
	AND  $60, R1, R8  // <--                                  // and	x8, x1, #0x3c
	LSL  R8, R15, R8  // <--                                  // lsl	x8, x15, x8
	BICS R8, R16, R16 // <--                                  // bics	x16, x16, x8
	BEQ  LBB1_93      // <--                                  // b.eq	.LBB1_93

LBB1_84:
	RBIT R16, R8        // <--                                  // rbit	x8, x16
	CLZ  R8, R1         // <--                                  // clz	x1, x8
	ADDS R1>>2, R13, R8 // <--                                  // adds	x8, x13, x1, lsr #2
	BMI  LBB1_83        // <--                                  // b.mi	.LBB1_83
	CMP  R9, R8         // <--                                  // cmp	x8, x9
	BGT  LBB1_83        // <--                                  // b.gt	.LBB1_83
	ADD  R8, R0, R3     // <--                                  // add	x3, x0, x8
	MOVD R7, R4         // <--                                  // mov	x4, x7
	MOVD R6, R5         // <--                                  // mov	x5, x6

LBB1_87:
	CMP   $15, R4                // <--                                  // cmp	x4, #15
	BLE   LBB1_89                // <--                                  // b.le	.LBB1_89
	WORD  $0x3cc10463            // FMOVQ.P 16(R3), F3                   // ldr	q3, [x3], #16
	SUB   $16, R4, R4            // <--                                  // sub	x4, x4, #16
	WORD  $0x3cc104a4            // FMOVQ.P 16(R5), F4                   // ldr	q4, [x5], #16
	VORR  V2.B16, V3.B16, V3.B16 // <--                                  // orr	v3.16b, v3.16b, v2.16b
	VEOR  V4.B16, V3.B16, V3.B16 // <--                                  // eor	v3.16b, v3.16b, v4.16b
	WORD  $0x6e30a863            // VUMAXV V3.B16, V3                    // umaxv	b3, v3.16b
	FMOVS F3, R19                // <--                                  // fmov	w19, s3
	CBZW  R19, LBB1_87           // <--                                  // cbz	w19, .LBB1_87
	JMP   LBB1_83                // <--                                  // b	.LBB1_83

LBB1_89:
	CMP  $1, R4  // <--                                  // cmp	x4, #1
	BLT  LBB1_3  // <--                                  // b.lt	.LBB1_3
	MOVD ZR, R19 // <--                                  // mov	x19, xzr

LBB1_91:
	WORD  $0x38736874       // MOVBU (R3)(R19), R20                 // ldrb	w20, [x3, x19]
	WORD  $0x387368b6       // MOVBU (R5)(R19), R22                 // ldrb	w22, [x5, x19]
	SUBW  $65, R20, R21     // <--                                  // sub	w21, w20, #65
	ORRW  $32, R20, R23     // <--                                  // orr	w23, w20, #0x20
	CMPW  $26, R21          // <--                                  // cmp	w21, #26
	CSELW LO, R23, R20, R20 // <--                                  // csel	w20, w23, w20, lo
	CMPW  R22, R20          // <--                                  // cmp	w20, w22
	BNE   LBB1_83           // <--                                  // b.ne	.LBB1_83
	ADD   $1, R19, R19      // <--                                  // add	x19, x19, #1
	CMP   R19, R4           // <--                                  // cmp	x4, x19
	BNE   LBB1_91           // <--                                  // b.ne	.LBB1_91
	JMP   LBB1_3            // <--                                  // b	.LBB1_3

LBB1_93:
	CMP  $64, R17      // <--                                  // cmp	x17, #64
	SUB  $32, R17, R16 // <--                                  // sub	x16, x17, #32
	BLT  LBB1_96       // <--                                  // b.lt	.LBB1_96
	ADD  $32, R14, R8  // <--                                  // add	x8, x14, #32
	MOVD R14, R13      // <--                                  // mov	x13, x14
	MOVD R16, R17      // <--                                  // mov	x17, x16
	CMP  R11, R8       // <--                                  // cmp	x8, x11
	BLS  LBB1_68       // <--                                  // b.ls	.LBB1_68
	JMP  LBB1_96       // <--                                  // b	.LBB1_96

LBB1_95:
	MOVD R17, R16 // <--                                  // mov	x16, x17
	MOVD R13, R14 // <--                                  // mov	x14, x13

LBB1_96:
	CMP  $1, R16     // <--                                  // cmp	x16, #1
	MOVD $-1, R8     // <--                                  // mov	x8, #-1
	BLT  LBB1_3      // <--                                  // b.lt	.LBB1_3
	CMP  R11, R14    // <--                                  // cmp	x14, x11
	BCS  LBB1_3      // <--                                  // b.hs	.LBB1_3
	WORD $0x4f01e400 // VMOVI $32, V0.B16                    // movi	v0.16b, #32

LBB1_99:
	WORD $0x394001c8  // MOVBU (R14), R8                      // ldrb	w8, [x14]
	ORRW R10, R8, R8  // <--                                  // orr	w8, w8, w10
	CMPW R2.UXTB, R8  // <--                                  // cmp	w8, w2, uxtb
	BNE  LBB1_105     // <--                                  // b.ne	.LBB1_105
	SUBS R12, R14, R8 // <--                                  // subs	x8, x14, x12
	BMI  LBB1_105     // <--                                  // b.mi	.LBB1_105
	CMP  R9, R8       // <--                                  // cmp	x8, x9
	BGT  LBB1_105     // <--                                  // b.gt	.LBB1_105
	ADD  R8, R0, R13  // <--                                  // add	x13, x0, x8
	MOVD R7, R15      // <--                                  // mov	x15, x7
	MOVD R6, R17      // <--                                  // mov	x17, x6

LBB1_103:
	CMP   $15, R15               // <--                                  // cmp	x15, #15
	BLE   LBB1_107               // <--                                  // b.le	.LBB1_107
	WORD  $0x3cc105a1            // FMOVQ.P 16(R13), F1                  // ldr	q1, [x13], #16
	SUB   $16, R15, R15          // <--                                  // sub	x15, x15, #16
	WORD  $0x3cc10622            // FMOVQ.P 16(R17), F2                  // ldr	q2, [x17], #16
	VORR  V0.B16, V1.B16, V1.B16 // <--                                  // orr	v1.16b, v1.16b, v0.16b
	VEOR  V2.B16, V1.B16, V1.B16 // <--                                  // eor	v1.16b, v1.16b, v2.16b
	WORD  $0x6e30a821            // VUMAXV V1.B16, V1                    // umaxv	b1, v1.16b
	FMOVS F1, R1                 // <--                                  // fmov	w1, s1
	CBZW  R1, LBB1_103           // <--                                  // cbz	w1, .LBB1_103

LBB1_105:
	CMP  $2, R16      // <--                                  // cmp	x16, #2
	MOVD $-1, R8      // <--                                  // mov	x8, #-1
	BLT  LBB1_3       // <--                                  // b.lt	.LBB1_3
	ADD  $1, R14, R14 // <--                                  // add	x14, x14, #1
	SUB  $1, R16, R16 // <--                                  // sub	x16, x16, #1
	CMP  R11, R14     // <--                                  // cmp	x14, x11
	BCC  LBB1_99      // <--                                  // b.lo	.LBB1_99
	JMP  LBB1_3       // <--                                  // b	.LBB1_3

LBB1_107:
	CMP  $1, R15 // <--                                  // cmp	x15, #1
	BLT  LBB1_3  // <--                                  // b.lt	.LBB1_3
	MOVD ZR, R1  // <--                                  // mov	x1, xzr

LBB1_109:
	WORD  $0x386169a3     // MOVBU (R13)(R1), R3                  // ldrb	w3, [x13, x1]
	WORD  $0x38616a25     // MOVBU (R17)(R1), R5                  // ldrb	w5, [x17, x1]
	SUBW  $65, R3, R4     // <--                                  // sub	w4, w3, #65
	ORRW  $32, R3, R19    // <--                                  // orr	w19, w3, #0x20
	CMPW  $26, R4         // <--                                  // cmp	w4, #26
	CSELW LO, R19, R3, R3 // <--                                  // csel	w3, w19, w3, lo
	CMPW  R5, R3          // <--                                  // cmp	w3, w5
	BNE   LBB1_105        // <--                                  // b.ne	.LBB1_105
	ADD   $1, R1, R1      // <--                                  // add	x1, x1, #1
	CMP   R1, R15         // <--                                  // cmp	x15, x1
	BNE   LBB1_109        // <--                                  // b.ne	.LBB1_109
	JMP   LBB1_3          // <--                                  // b	.LBB1_3
