//go:build !noasm && amd64
// Code generated by gocc v0.16.5-rev-57c4d32 -- DO NOT EDIT.
//
// Source file         : ascii_sse.c
// Clang version       : Apple clang version 17.0.0 (clang-1700.6.3.2)
// Target architecture : amd64
// Compiler options    : -msse4.1

#include "textflag.h"

DATA LCPI0_0<>+0x00(SB)/8, $0x8080808080808080
DATA LCPI0_0<>+0x08(SB)/8, $0x8080808080808080
GLOBL LCPI0_0<>(SB), (RODATA|NOPTR), $16

TEXT ·isAsciiSse(SB), NOSPLIT, $0-17
	MOVQ src+0(FP), DI
	MOVQ src_len+8(FP), SI
	NOP                      // (skipped)                            // push	rbp
	NOP                      // (skipped)                            // mov	rbp, rsp
	NOP                      // (skipped)                            // and	rsp, -8
	CMPQ SI, $0x10           // <--                                  // cmp	rsi, 16
	JB   LBB0_9              // <--                                  // jb	.LBB0_9
	LEAQ 0(DI)(SI*1), CX     // <--                                  // lea	rcx, [rdi + rsi]
	WORD $0xf089             // MOVL SI, AX                          // mov	eax, esi
	WORD $0xe083; BYTE $0x3f // ANDL $0x3f, AX                       // and	eax, 63
	SUBQ AX, CX              // <--                                  // sub	rcx, rax
	CMPQ CX, DI              // <--                                  // cmp	rcx, rdi
	JBE  LBB0_5              // <--                                  // jbe	.LBB0_5
	MOVO LCPI0_0<>(SB), X0   // <--                                  // movdqa	xmm0, xmmword ptr [rip + .LCPI0_0]

LBB0_3:
	LONG $0x0f6f0ff3             // MOVDQU 0(DI), X1                     // movdqu	xmm1, xmmword ptr [rdi]
	LONG $0x576f0ff3; BYTE $0x10 // MOVDQU 0x10(DI), X2                  // movdqu	xmm2, xmmword ptr [rdi + 16]
	LONG $0xd1eb0f66             // POR X1, X2                           // por	xmm2, xmm1
	LONG $0x4f6f0ff3; BYTE $0x20 // MOVDQU 0x20(DI), X1                  // movdqu	xmm1, xmmword ptr [rdi + 32]
	LONG $0x5f6f0ff3; BYTE $0x30 // MOVDQU 0x30(DI), X3                  // movdqu	xmm3, xmmword ptr [rdi + 48]
	LONG $0xd9eb0f66             // POR X1, X3                           // por	xmm3, xmm1
	LONG $0xdaeb0f66             // POR X2, X3                           // por	xmm3, xmm2
	LONG $0x17380f66; BYTE $0xd8 // PTEST X0, X3                         // ptest	xmm3, xmm0
	JNE  LBB0_15                 // <--                                  // jne	.LBB0_15
	ADDQ $0x40, DI               // <--                                  // add	rdi, 64
	CMPQ DI, CX                  // <--                                  // cmp	rdi, rcx
	JB   LBB0_3                  // <--                                  // jb	.LBB0_3

LBB0_5:
	ADDQ DI, AX              // <--                                  // add	rax, rdi
	WORD $0xe683; BYTE $0x0f // ANDL $0xf, SI                        // and	esi, 15
	SUBQ SI, AX              // <--                                  // sub	rax, rsi
	CMPQ DI, AX              // <--                                  // cmp	rdi, rax
	JAE  LBB0_9              // <--                                  // jae	.LBB0_9
	MOVO LCPI0_0<>(SB), X0   // <--                                  // movdqa	xmm0, xmmword ptr [rip + .LCPI0_0]

LBB0_7:
	LONG $0x0f6f0ff3             // MOVDQU 0(DI), X1                     // movdqu	xmm1, xmmword ptr [rdi]
	LONG $0x17380f66; BYTE $0xc8 // PTEST X0, X1                         // ptest	xmm1, xmm0
	JNE  LBB0_15                 // <--                                  // jne	.LBB0_15
	ADDQ $0x10, DI               // <--                                  // add	rdi, 16
	CMPQ DI, AX                  // <--                                  // cmp	rdi, rax
	JB   LBB0_7                  // <--                                  // jb	.LBB0_7

LBB0_9:
	WORD $0x8548; BYTE $0xf6 // TESTQ SI, SI                         // test	rsi, rsi
	JE   LBB0_13             // <--                                  // je	.LBB0_13
	CMPQ SI, $0x8            // <--                                  // cmp	rsi, 8
	JAE  LBB0_14             // <--                                  // jae	.LBB0_14
	CMPQ SI, $0x4            // <--                                  // cmp	rsi, 4
	JAE  LBB0_16             // <--                                  // jae	.LBB0_16
	MOVQ SI, AX              // <--                                  // mov	rax, rsi
	SHRQ $0x1, AX            // <--                                  // shr	rax
	LONG $0x0704b60f         // MOVZX 0(DI)(AX*1), AX                // movzx	eax, byte ptr [rdi + rax]
	ORB  0(DI), AL           // <--                                  // or	al, byte ptr [rdi]
	ORB  -0x1(DI)(SI*1), AL  // <--                                  // or	al, byte ptr [rdi + rsi - 1]
	WORD $0x990f; BYTE $0xc0 // SETNS AL                             // setns	al
	NOP                      // (skipped)                            // mov	rsp, rbp
	NOP                      // (skipped)                            // pop	rbp
	MOVB AX, ret+16(FP)      // <--
	RET                      // <--                                  // ret

LBB0_13:
	WORD $0x01b0        // MOVL $0x1, AL                        // mov	al, 1
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	MOVB AX, ret+16(FP) // <--
	RET                 // <--                                  // ret

LBB0_14:
	MOVQ -0x8(DI)(SI*1), AX                // <--                                  // mov	rax, qword ptr [rdi + rsi - 8]
	ORQ  0(DI), AX                         // <--                                  // or	rax, qword ptr [rdi]
	QUAD $0x808080808080b948; WORD $0x8080 // MOVQ $0x8080808080808080, CX         // movabs	rcx, -9187201950435737472
	WORD $0x8548; BYTE $0xc8               // TESTQ CX, AX                         // test	rax, rcx
	WORD $0x940f; BYTE $0xc0               // SETE AL                              // sete	al
	NOP                                    // (skipped)                            // mov	rsp, rbp
	NOP                                    // (skipped)                            // pop	rbp
	MOVB AX, ret+16(FP)                    // <--
	RET                                    // <--                                  // ret

LBB0_15:
	XORL AX, AX         // <--                                  // xor	eax, eax
	NOP                 // (skipped)                            // mov	rsp, rbp
	NOP                 // (skipped)                            // pop	rbp
	MOVB AX, ret+16(FP) // <--
	RET                 // <--                                  // ret

LBB0_16:
	LONG $0xfc37448b             // MOVL -0x4(DI)(SI*1), AX              // mov	eax, dword ptr [rdi + rsi - 4]
	WORD $0x070b                 // ORL 0(DI), AX                        // or	eax, dword ptr [rdi]
	LONG $0x808080a9; BYTE $0x80 // TESTL $-0x7f7f7f80, AX               // test	eax, -2139062144
	WORD $0x940f; BYTE $0xc0     // SETE AL                              // sete	al
	NOP                          // (skipped)                            // mov	rsp, rbp
	NOP                          // (skipped)                            // pop	rbp
	MOVB AX, ret+16(FP)          // <--
	RET                          // <--                                  // ret
