//go:build !noasm && arm64
// Code generated by gocc v0.16.5-rev-57c4d32 -- DO NOT EDIT.
//
// Source file         : ascii_sve2.c
// Clang version       : Apple clang version 16.0.0 (clang-1600.0.26.6)
// Target architecture : arm64
// Compiler options    : -march=armv9-a+sve2

#include "textflag.h"

TEXT ·indexFoldNeedleSve2(SB), NOSPLIT, $0-72
	MOVD haystack+0(FP), R0
	MOVD haystack_len+8(FP), R1
	MOVB rare1+16(FP), R2
	MOVD off1+24(FP), R3
	MOVB rare2+32(FP), R4
	MOVD off2+40(FP), R5
	MOVD norm_needle+48(FP), R6
	MOVD needle_len+56(FP), R7
	SUBS R7, R1, R9             // <--                                  // subs	x9, x1, x7
	BGE  LBB0_2                 // <--                                  // b.ge	.LBB0_2
	MOVD $-1, R0                // <--                                  // mov	x0, #-1
	MOVD R0, ret+64(FP)         // <--
	RET                         // <--                                  // ret

LBB0_2:
	SUBS  $1, R7, R1           // <--                                  // subs	x1, x7, #1
	BLT   LBB0_5               // <--                                  // b.lt	.LBB0_5
	NOP                        // (skipped)                            // stp	x29, x30, [sp, #-80]!
	ANDW  $4294967263, R2, R8  // <--                                  // and	w8, w2, #0xffffffdf
	ANDW  $4294967263, R4, R12 // <--                                  // and	w12, w4, #0xffffffdf
	SUBW  $65, R8, R11         // <--                                  // sub	w11, w8, #65
	SUBW  $65, R12, R13        // <--                                  // sub	w13, w12, #65
	ANDW  $255, R11, R11       // <--                                  // and	w11, w11, #0xff
	ORRW  $32, R2, R10         // <--                                  // orr	w10, w2, #0x20
	CMPW  $26, R11             // <--                                  // cmp	w11, #26
	ANDW  $255, R13, R11       // <--                                  // and	w11, w13, #0xff
	CSELW LO, R8, R2, R8       // <--                                  // csel	w8, w8, w2, lo
	CSELW LO, R10, R2, R13     // <--                                  // csel	w13, w10, w2, lo
	CMPW  $26, R11             // <--                                  // cmp	w11, #26
	ORRW  $32, R4, R10         // <--                                  // orr	w10, w4, #0x20
	CSELW LO, R12, R4, R12     // <--                                  // csel	w12, w12, w4, lo
	CSELW LO, R10, R4, R14     // <--                                  // csel	w14, w10, w4, lo
	LSR   $1, R7, R10          // <--                                  // lsr	x10, x7, #1
	CMP   $4, R7               // <--                                  // cmp	x7, #4
	ADD   $1, R9, R16          // <--                                  // add	x16, x9, #1
	WORD  $0x05203900          // ?                                    // mov	z0.b, w8
	ADD   R7, R6, R8           // <--                                  // add	x8, x6, x7
	CSINV HS, R10, ZR, R17     // <--                                  // csinv	x17, x10, xzr, hs
	WORD  $0x04bf502b          // ?                                    // rdvl	x11, #1
	WORD  $0x052039a3          // ?                                    // mov	z3.b, w13
	WORD  $0x05203981          // ?                                    // mov	z1.b, w12
	WORD  $0x052039c2          // ?                                    // mov	z2.b, w14
	NOP                        // (skipped)                            // str	x25, [sp, #16]
	NOP                        // (skipped)                            // mov	x29, sp
	NOP                        // (skipped)                            // stp	x24, x23, [sp, #32]
	NOP                        // (skipped)                            // stp	x22, x21, [sp, #48]
	NOP                        // (skipped)                            // stp	x20, x19, [sp, #64]
	BCS   LBB0_6               // <--                                  // b.hs	.LBB0_6
	MOVW  ZR, R12              // <--                                  // mov	w12, wzr
	JMP   LBB0_7               // <--                                  // b	.LBB0_7

LBB0_5:
	MOVD ZR, R0         // <--                                  // mov	x0, xzr
	MOVD R0, ret+64(FP) // <--
	RET                 // <--                                  // ret

LBB0_6:
	WORD $0x386a68cc // MOVBU (R6)(R10), R12                 // ldrb	w12, [x6, x10]

LBB0_7:
	WORD $0x394000cd // MOVBU (R6), R13                      // ldrb	w13, [x6]
	WORD $0x05236000 // ?                                    // zip1	z0.b, z0.b, z3.b
	WORD $0x385ff10e // LDURBW -1(R8), R14                   // ldurb	w14, [x8, #-1]
	CMP  R16, R11    // <--                                  // cmp	x11, x16
	WORD $0x05226021 // ?                                    // zip1	z1.b, z1.b, z2.b
	WORD $0x2518e3e0 // ?                                    // ptrue	p0.b
	BLE  LBB0_12     // <--                                  // b.le	.LBB0_12
	MOVD ZR, R15     // <--                                  // mov	x15, xzr

LBB0_9:
	CMP  R9, R15      // <--                                  // cmp	x15, x9
	BGT  LBB0_42      // <--                                  // b.gt	.LBB0_42
	SUB  R15, R16, R8 // <--                                  // sub	x8, x16, x15
	ADD  R15, R0, R16 // <--                                  // add	x16, x0, x15
	WORD $0x25281fe1  // ?                                    // whilelo	p1.b, xzr, x8
	WORD $0xa4034602  // ?                                    // ld1b	{ z2.b }, p1/z, [x16, x3]
	WORD $0xa4054603  // ?                                    // ld1b	{ z3.b }, p1/z, [x16, x5]
	WORD $0x45208442  // ?                                    // match	p2.b, p1/z, z2.b, z0.b
	WORD $0x45218463  // ?                                    // match	p3.b, p1/z, z3.b, z1.b
	WORD $0x25434442  // ?                                    // ands	p2.b, p1/z, p2.b, p3.b
	BEQ  LBB0_42      // <--                                  // b.eq	.LBB0_42
	SUB  $1, R0, R16  // <--                                  // sub	x16, x0, #1
	WORD $0x2538c000  // ?                                    // mov	z0.b, #0
	WORD $0x2538c401  // ?                                    // mov	z1.b, #32
	JMP  LBB0_25      // <--                                  // b	.LBB0_25

LBB0_12:
	CMP  $9, R7      // <--                                  // cmp	x7, #9
	BCS  LBB0_44     // <--                                  // b.hs	.LBB0_44
	CMP  $3, R7      // <--                                  // cmp	x7, #3
	BHI  LBB0_58     // <--                                  // b.hi	.LBB0_58
	MOVD ZR, R19     // <--                                  // mov	x19, xzr
	SUB  $1, R0, R17 // <--                                  // sub	x17, x0, #1
	ADD  $1, R6, R2  // <--                                  // add	x2, x6, #1
	ADD  $1, R0, R4  // <--                                  // add	x4, x0, #1
	MOVD R11, R8     // <--                                  // mov	x8, x11

LBB0_15:
	ADD  R19, R0, R15 // <--                                  // add	x15, x0, x19
	WORD $0xa40341e2  // ?                                    // ld1b	{ z2.b }, p0/z, [x15, x3]
	WORD $0xa40541e3  // ?                                    // ld1b	{ z3.b }, p0/z, [x15, x5]
	MOVD R8, R15      // <--                                  // mov	x15, x8
	WORD $0x45208041  // ?                                    // match	p1.b, p0/z, z2.b, z0.b
	WORD $0x45218062  // ?                                    // match	p2.b, p0/z, z3.b, z1.b
	WORD $0x25424021  // ?                                    // ands	p1.b, p0/z, p1.b, p2.b
	BNE  LBB0_18      // <--                                  // b.ne	.LBB0_18

LBB0_16:
	ADD  R11, R15, R8 // <--                                  // add	x8, x15, x11
	ADD  R11, R4, R4  // <--                                  // add	x4, x4, x11
	MOVD R15, R19     // <--                                  // mov	x19, x15
	CMP  R16, R8      // <--                                  // cmp	x8, x16
	BLE  LBB0_15      // <--                                  // b.le	.LBB0_15
	JMP  LBB0_9       // <--                                  // b	.LBB0_9

LBB0_17:
	WORD $0x25104022 // ?                                    // brka	p2.b, p0/z, p1.b
	WORD $0x25424031 // ?                                    // bics	p1.b, p0/z, p1.b, p2.b
	BEQ  LBB0_16     // <--                                  // b.eq	.LBB0_16

LBB0_18:
	WORD  $0x25904022           // ?                                    // brkb	p2.b, p0/z, p1.b
	WORD  $0x25208055           // ?                                    // cntp	x21, p0, p2.b
	ADD   R19, R21, R8          // <--                                  // add	x8, x21, x19
	ADD   R8, R7, R20           // <--                                  // add	x20, x7, x8
	WORD  $0x38686816           // MOVBU (R0)(R8), R22                  // ldrb	w22, [x0, x8]
	WORD  $0x38746a34           // MOVBU (R17)(R20), R20                // ldrb	w20, [x17, x20]
	ANDW  $4294967263, R22, R23 // <--                                  // and	w23, w22, #0xffffffdf
	SUBW  $65, R23, R24         // <--                                  // sub	w24, w23, #65
	ANDW  $4294967263, R20, R25 // <--                                  // and	w25, w20, #0xffffffdf
	CMPW  $26, R24              // <--                                  // cmp	w24, #26
	SUBW  $65, R25, R24         // <--                                  // sub	w24, w25, #65
	CSELW LO, R23, R22, R22     // <--                                  // csel	w22, w23, w22, lo
	CMPW  $26, R24              // <--                                  // cmp	w24, #26
	CSELW LO, R25, R20, R20     // <--                                  // csel	w20, w25, w20, lo
	CMPW  R13, R22              // <--                                  // cmp	w22, w13
	CCMPW EQ, R20, R14, $0      // <--                                  // ccmp	w20, w14, #0, eq
	BNE   LBB0_17               // <--                                  // b.ne	.LBB0_17
	MOVD  ZR, R20               // <--                                  // mov	x20, xzr
	ADD   R21, R4, R21          // <--                                  // add	x21, x4, x21

LBB0_20:
	CMP   R20, R1               // <--                                  // cmp	x1, x20
	BEQ   LBB0_43               // <--                                  // b.eq	.LBB0_43
	WORD  $0x38746ab6           // MOVBU (R21)(R20), R22                // ldrb	w22, [x21, x20]
	WORD  $0x38746858           // MOVBU (R2)(R20), R24                 // ldrb	w24, [x2, x20]
	ADD   $1, R20, R20          // <--                                  // add	x20, x20, #1
	ANDW  $4294967263, R22, R23 // <--                                  // and	w23, w22, #0xffffffdf
	SUBW  $65, R23, R25         // <--                                  // sub	w25, w23, #65
	CMPW  $26, R25              // <--                                  // cmp	w25, #26
	CSELW LO, R23, R22, R22     // <--                                  // csel	w22, w23, w22, lo
	CMPW  R24, R22              // <--                                  // cmp	w22, w24
	BEQ   LBB0_20               // <--                                  // b.eq	.LBB0_20
	CMP   R7, R20               // <--                                  // cmp	x20, x7
	BLT   LBB0_17               // <--                                  // b.lt	.LBB0_17
	JMP   LBB0_43               // <--                                  // b	.LBB0_43

LBB0_23:
	CMP R7, R1  // <--                                  // cmp	x1, x7
	BGE LBB0_43 // <--                                  // b.ge	.LBB0_43

LBB0_24:
	WORD $0x25104443 // ?                                    // brka	p3.b, p1/z, p2.b
	WORD $0x25434452 // ?                                    // bics	p2.b, p1/z, p2.b, p3.b
	BEQ  LBB0_42     // <--                                  // b.eq	.LBB0_42

LBB0_25:
	WORD  $0x25904443         // ?                                    // brkb	p3.b, p1/z, p2.b
	WORD  $0x25208468         // ?                                    // cntp	x8, p1, p3.b
	ADD   R15, R8, R8         // <--                                  // add	x8, x8, x15
	CMP   R9, R8              // <--                                  // cmp	x8, x9
	BGT   LBB0_24             // <--                                  // b.gt	.LBB0_24
	ADD   R8, R0, R17         // <--                                  // add	x17, x0, x8
	ADD   R8, R7, R1          // <--                                  // add	x1, x7, x8
	WORD  $0x39400222         // MOVBU (R17), R2                      // ldrb	w2, [x17]
	WORD  $0x38616a01         // MOVBU (R16)(R1), R1                  // ldrb	w1, [x16, x1]
	ANDW  $4294967263, R2, R3 // <--                                  // and	w3, w2, #0xffffffdf
	SUBW  $65, R3, R4         // <--                                  // sub	w4, w3, #65
	ANDW  $4294967263, R1, R5 // <--                                  // and	w5, w1, #0xffffffdf
	CMPW  $26, R4             // <--                                  // cmp	w4, #26
	SUBW  $65, R5, R4         // <--                                  // sub	w4, w5, #65
	CSELW LO, R3, R2, R2      // <--                                  // csel	w2, w3, w2, lo
	CMPW  $26, R4             // <--                                  // cmp	w4, #26
	CSELW LO, R5, R1, R1      // <--                                  // csel	w1, w5, w1, lo
	CMPW  R13, R2             // <--                                  // cmp	w2, w13
	CCMPW EQ, R1, R14, $0     // <--                                  // ccmp	w1, w14, #0, eq
	BNE   LBB0_24             // <--                                  // b.ne	.LBB0_24
	CMP   $4, R7              // <--                                  // cmp	x7, #4
	BCS   LBB0_32             // <--                                  // b.hs	.LBB0_32

LBB0_28:
	WORD $0x394000c1 // MOVBU (R6), R1                       // ldrb	w1, [x6]
	CMPW R1, R13     // <--                                  // cmp	w13, w1
	BNE  LBB0_24     // <--                                  // b.ne	.LBB0_24
	MOVW $1, R2      // <--                                  // mov	w2, #1

LBB0_30:
	MOVD  R2, R1              // <--                                  // mov	x1, x2
	CMP   R2, R7              // <--                                  // cmp	x7, x2
	BEQ   LBB0_23             // <--                                  // b.eq	.LBB0_23
	WORD  $0x38616a22         // MOVBU (R17)(R1), R2                  // ldrb	w2, [x17, x1]
	WORD  $0x386168c4         // MOVBU (R6)(R1), R4                   // ldrb	w4, [x6, x1]
	ANDW  $4294967263, R2, R3 // <--                                  // and	w3, w2, #0xffffffdf
	SUBW  $65, R3, R5         // <--                                  // sub	w5, w3, #65
	CMPW  $26, R5             // <--                                  // cmp	w5, #26
	CSELW LO, R3, R2, R3      // <--                                  // csel	w3, w3, w2, lo
	ADD   $1, R1, R2          // <--                                  // add	x2, x1, #1
	CMPW  R4, R3              // <--                                  // cmp	w3, w4
	BEQ   LBB0_30             // <--                                  // b.eq	.LBB0_30
	JMP   LBB0_23             // <--                                  // b	.LBB0_23

LBB0_32:
	ADD   R10, R8, R1         // <--                                  // add	x1, x8, x10
	WORD  $0x38616801         // MOVBU (R0)(R1), R1                   // ldrb	w1, [x0, x1]
	ANDW  $4294967263, R1, R2 // <--                                  // and	w2, w1, #0xffffffdf
	SUBW  $65, R2, R3         // <--                                  // sub	w3, w2, #65
	CMPW  $26, R3             // <--                                  // cmp	w3, #26
	CSELW LO, R2, R1, R1      // <--                                  // csel	w1, w2, w1, lo
	CMPW  R1, R12             // <--                                  // cmp	w12, w1
	BNE   LBB0_24             // <--                                  // b.ne	.LBB0_24
	CMP   $8, R7              // <--                                  // cmp	x7, #8
	BLE   LBB0_28             // <--                                  // b.le	.LBB0_28
	CMP   $65, R7             // <--                                  // cmp	x7, #65
	BCS   LBB0_36             // <--                                  // b.hs	.LBB0_36
	WORD  $0x25271fe3         // ?                                    // whilelo	p3.b, xzr, x7
	WORD  $0xa400ae22         // ?                                    // ld1b	{ z2.b }, p3/z, [x17]
	WORD  $0xa400acc3         // ?                                    // ld1b	{ z3.b }, p3/z, [x6]
	JMP   LBB0_41             // <--                                  // b	.LBB0_41

LBB0_36:
	MOVD ZR, R1 // <--                                  // mov	x1, xzr
	MOVD R7, R3 // <--                                  // mov	x3, x7

LBB0_37:
	SUBS R11, R3, R2 // <--                                  // subs	x2, x3, x11
	BLT  LBB0_39     // <--                                  // b.lt	.LBB0_39
	WORD $0xa4014222 // ?                                    // ld1b	{ z2.b }, p0/z, [x17, x1]
	WORD $0xa40140c3 // ?                                    // ld1b	{ z3.b }, p0/z, [x6, x1]
	ADD  R11, R1, R1 // <--                                  // add	x1, x1, x11
	MOVD R2, R3      // <--                                  // mov	x3, x2
	WORD $0x24384043 // ?                                    // cmphs	p3.b, p0/z, z2.b, #97
	WORD $0x243ea054 // ?                                    // cmpls	p4.b, p0/z, z2.b, #122
	WORD $0x25044063 // ?                                    // and	p3.b, p0/z, p3.b, p4.b
	WORD $0x04190c22 // ?                                    // eor	z2.b, p3/m, z2.b, z1.b
	WORD $0x04190043 // ?                                    // eor	z3.b, p0/m, z3.b, z2.b
	WORD $0x25008073 // ?                                    // cmpne	p3.b, p0/z, z3.b, #0
	BEQ  LBB0_37     // <--                                  // b.eq	.LBB0_37
	JMP  LBB0_24     // <--                                  // b	.LBB0_24

LBB0_39:
	CMP  $1, R3      // <--                                  // cmp	x3, #1
	BLT  LBB0_43     // <--                                  // b.lt	.LBB0_43
	WORD $0x25231fe3 // ?                                    // whilelo	p3.b, xzr, x3
	WORD $0xa4014e22 // ?                                    // ld1b	{ z2.b }, p3/z, [x17, x1]
	WORD $0xa4014cc3 // ?                                    // ld1b	{ z3.b }, p3/z, [x6, x1]

LBB0_41:
	WORD $0x24384c44 // ?                                    // cmphs	p4.b, p3/z, z2.b, #97
	WORD $0x243eac55 // ?                                    // cmpls	p5.b, p3/z, z2.b, #122
	WORD $0x25054c84 // ?                                    // and	p4.b, p3/z, p4.b, p5.b
	WORD $0x04191022 // ?                                    // eor	z2.b, p4/m, z2.b, z1.b
	WORD $0x0520cc42 // ?                                    // sel	z2.b, p3, z2.b, z0.b
	WORD $0x04190c62 // ?                                    // eor	z2.b, p3/m, z2.b, z3.b
	WORD $0x25008c53 // ?                                    // cmpne	p3.b, p3/z, z2.b, #0
	BNE  LBB0_24     // <--                                  // b.ne	.LBB0_24
	JMP  LBB0_43     // <--                                  // b	.LBB0_43

LBB0_42:
	MOVD $-1, R8 // <--                                  // mov	x8, #-1

LBB0_43:
	NOP                 // (skipped)                            // ldp	x20, x19, [sp, #64]
	NOP                 // (skipped)                            // ldp	x22, x21, [sp, #48]
	NOP                 // (skipped)                            // ldp	x24, x23, [sp, #32]
	NOP                 // (skipped)                            // ldr	x25, [sp, #16]
	NOP                 // (skipped)                            // ldp	x29, x30, [sp], #80
	MOVD R8, R0         // <--                                  // mov	x0, x8
	MOVD R0, ret+64(FP) // <--
	RET                 // <--                                  // ret

LBB0_44:
	MOVD ZR, R4      // <--                                  // mov	x4, xzr
	SUB  $1, R0, R1  // <--                                  // sub	x1, x0, #1
	MOVD R0, R2      // <--                                  // mov	x2, x0
	MOVD R11, R8     // <--                                  // mov	x8, x11
	WORD $0x2538c002 // ?                                    // mov	z2.b, #0
	WORD $0x2538c403 // ?                                    // mov	z3.b, #32
	JMP  LBB0_46     // <--                                  // b	.LBB0_46

LBB0_45:
	ADD  R11, R15, R8 // <--                                  // add	x8, x15, x11
	ADD  R11, R2, R2  // <--                                  // add	x2, x2, x11
	MOVD R15, R4      // <--                                  // mov	x4, x15
	CMP  R16, R8      // <--                                  // cmp	x8, x16
	BGT  LBB0_9       // <--                                  // b.gt	.LBB0_9

LBB0_46:
	ADD  R4, R0, R15 // <--                                  // add	x15, x0, x4
	WORD $0xa40341e4 // ?                                    // ld1b	{ z4.b }, p0/z, [x15, x3]
	WORD $0xa40541e5 // ?                                    // ld1b	{ z5.b }, p0/z, [x15, x5]
	MOVD R8, R15     // <--                                  // mov	x15, x8
	WORD $0x45208081 // ?                                    // match	p1.b, p0/z, z4.b, z0.b
	WORD $0x452180a2 // ?                                    // match	p2.b, p0/z, z5.b, z1.b
	WORD $0x25424021 // ?                                    // ands	p1.b, p0/z, p1.b, p2.b
	BEQ  LBB0_45     // <--                                  // b.eq	.LBB0_45
	JMP  LBB0_50     // <--                                  // b	.LBB0_50

LBB0_47:
	WORD $0x25271fe2 // ?                                    // whilelo	p2.b, xzr, x7
	WORD $0xa400aa64 // ?                                    // ld1b	{ z4.b }, p2/z, [x19]
	WORD $0xa400a8c5 // ?                                    // ld1b	{ z5.b }, p2/z, [x6]

LBB0_48:
	WORD $0x24384883 // ?                                    // cmphs	p3.b, p2/z, z4.b, #97
	WORD $0x243ea894 // ?                                    // cmpls	p4.b, p2/z, z4.b, #122
	WORD $0x25044863 // ?                                    // and	p3.b, p2/z, p3.b, p4.b
	WORD $0x04190c64 // ?                                    // eor	z4.b, p3/m, z4.b, z3.b
	WORD $0x0522c884 // ?                                    // sel	z4.b, p2, z4.b, z2.b
	WORD $0x041908a4 // ?                                    // eor	z4.b, p2/m, z4.b, z5.b
	WORD $0x25008892 // ?                                    // cmpne	p2.b, p2/z, z4.b, #0
	BEQ  LBB0_43     // <--                                  // b.eq	.LBB0_43

LBB0_49:
	WORD $0x25104022 // ?                                    // brka	p2.b, p0/z, p1.b
	WORD $0x25424031 // ?                                    // bics	p1.b, p0/z, p1.b, p2.b
	BEQ  LBB0_45     // <--                                  // b.eq	.LBB0_45

LBB0_50:
	WORD  $0x25904022           // ?                                    // brkb	p2.b, p0/z, p1.b
	WORD  $0x25208055           // ?                                    // cntp	x21, p0, p2.b
	ADD   R4, R21, R8           // <--                                  // add	x8, x21, x4
	ADD   R8, R0, R19           // <--                                  // add	x19, x0, x8
	ADD   R8, R7, R20           // <--                                  // add	x20, x7, x8
	WORD  $0x39400276           // MOVBU (R19), R22                     // ldrb	w22, [x19]
	WORD  $0x38746834           // MOVBU (R1)(R20), R20                 // ldrb	w20, [x1, x20]
	ANDW  $4294967263, R22, R23 // <--                                  // and	w23, w22, #0xffffffdf
	SUBW  $65, R23, R24         // <--                                  // sub	w24, w23, #65
	ANDW  $4294967263, R20, R25 // <--                                  // and	w25, w20, #0xffffffdf
	CMPW  $26, R24              // <--                                  // cmp	w24, #26
	SUBW  $65, R25, R24         // <--                                  // sub	w24, w25, #65
	CSELW LO, R23, R22, R22     // <--                                  // csel	w22, w23, w22, lo
	CMPW  $26, R24              // <--                                  // cmp	w24, #26
	CSELW LO, R25, R20, R20     // <--                                  // csel	w20, w25, w20, lo
	CMPW  R13, R22              // <--                                  // cmp	w22, w13
	CCMPW EQ, R20, R14, $0      // <--                                  // ccmp	w20, w14, #0, eq
	BNE   LBB0_49               // <--                                  // b.ne	.LBB0_49
	ADD   R17, R8, R20          // <--                                  // add	x20, x8, x17
	WORD  $0x38746814           // MOVBU (R0)(R20), R20                 // ldrb	w20, [x0, x20]
	ANDW  $4294967263, R20, R22 // <--                                  // and	w22, w20, #0xffffffdf
	SUBW  $65, R22, R23         // <--                                  // sub	w23, w22, #65
	CMPW  $26, R23              // <--                                  // cmp	w23, #26
	CSELW LO, R22, R20, R20     // <--                                  // csel	w20, w22, w20, lo
	CMPW  R20, R12              // <--                                  // cmp	w12, w20
	BNE   LBB0_49               // <--                                  // b.ne	.LBB0_49
	CMP   $65, R7               // <--                                  // cmp	x7, #65
	BCC   LBB0_47               // <--                                  // b.lo	.LBB0_47
	MOVD  ZR, R20               // <--                                  // mov	x20, xzr
	ADD   R21, R2, R21          // <--                                  // add	x21, x2, x21
	MOVD  R7, R23               // <--                                  // mov	x23, x7

LBB0_54:
	SUBS R11, R23, R22 // <--                                  // subs	x22, x23, x11
	BLT  LBB0_56       // <--                                  // b.lt	.LBB0_56
	WORD $0xa41442a4   // ?                                    // ld1b	{ z4.b }, p0/z, [x21, x20]
	WORD $0xa41440c5   // ?                                    // ld1b	{ z5.b }, p0/z, [x6, x20]
	ADD  R11, R20, R20 // <--                                  // add	x20, x20, x11
	MOVD R22, R23      // <--                                  // mov	x23, x22
	WORD $0x24384082   // ?                                    // cmphs	p2.b, p0/z, z4.b, #97
	WORD $0x243ea093   // ?                                    // cmpls	p3.b, p0/z, z4.b, #122
	WORD $0x25034042   // ?                                    // and	p2.b, p0/z, p2.b, p3.b
	WORD $0x04190864   // ?                                    // eor	z4.b, p2/m, z4.b, z3.b
	WORD $0x04190085   // ?                                    // eor	z5.b, p0/m, z5.b, z4.b
	WORD $0x250080b2   // ?                                    // cmpne	p2.b, p0/z, z5.b, #0
	BEQ  LBB0_54       // <--                                  // b.eq	.LBB0_54
	JMP  LBB0_49       // <--                                  // b	.LBB0_49

LBB0_56:
	CMP  $1, R23     // <--                                  // cmp	x23, #1
	BLT  LBB0_43     // <--                                  // b.lt	.LBB0_43
	WORD $0x25371fe2 // ?                                    // whilelo	p2.b, xzr, x23
	WORD $0xa4144a64 // ?                                    // ld1b	{ z4.b }, p2/z, [x19, x20]
	WORD $0xa41448c5 // ?                                    // ld1b	{ z5.b }, p2/z, [x6, x20]
	JMP  LBB0_48     // <--                                  // b	.LBB0_48

LBB0_58:
	CMP   $8, R7     // <--                                  // cmp	x7, #8
	MOVD  ZR, R4     // <--                                  // mov	x4, xzr
	SUB   $1, R0, R1 // <--                                  // sub	x1, x0, #1
	CSETW NE, R2     // <--                                  // cset	w2, ne
	MOVW  $7, R19    // <--                                  // mov	w19, #7
	MOVD  R11, R8    // <--                                  // mov	x8, x11
	JMP   LBB0_60    // <--                                  // b	.LBB0_60

LBB0_59:
	ADD  R11, R15, R8 // <--                                  // add	x8, x15, x11
	MOVD R15, R4      // <--                                  // mov	x4, x15
	CMP  R16, R8      // <--                                  // cmp	x8, x16
	BGT  LBB0_9       // <--                                  // b.gt	.LBB0_9

LBB0_60:
	ADD  R4, R0, R15 // <--                                  // add	x15, x0, x4
	WORD $0xa40341e2 // ?                                    // ld1b	{ z2.b }, p0/z, [x15, x3]
	WORD $0xa40541e3 // ?                                    // ld1b	{ z3.b }, p0/z, [x15, x5]
	MOVD R8, R15     // <--                                  // mov	x15, x8
	WORD $0x45208041 // ?                                    // match	p1.b, p0/z, z2.b, z0.b
	WORD $0x45218062 // ?                                    // match	p2.b, p0/z, z3.b, z1.b
	WORD $0x25424021 // ?                                    // ands	p1.b, p0/z, p1.b, p2.b
	BNE  LBB0_64     // <--                                  // b.ne	.LBB0_64
	JMP  LBB0_59     // <--                                  // b	.LBB0_59

LBB0_61:
	MOVW $1, R20 // <--                                  // mov	w20, #1

LBB0_62:
	CMP R7, R20 // <--                                  // cmp	x20, x7
	BGE LBB0_43 // <--                                  // b.ge	.LBB0_43

LBB0_63:
	WORD $0x25104022 // ?                                    // brka	p2.b, p0/z, p1.b
	WORD $0x25424031 // ?                                    // bics	p1.b, p0/z, p1.b, p2.b
	BEQ  LBB0_59     // <--                                  // b.eq	.LBB0_59

LBB0_64:
	WORD   $0x25904022           // ?                                    // brkb	p2.b, p0/z, p1.b
	WORD   $0x25208048           // ?                                    // cntp	x8, p0, p2.b
	ADD    R4, R8, R8            // <--                                  // add	x8, x8, x4
	ADD    R8, R0, R20           // <--                                  // add	x20, x0, x8
	ADD    R8, R7, R21           // <--                                  // add	x21, x7, x8
	WORD   $0x39400296           // MOVBU (R20), R22                     // ldrb	w22, [x20]
	WORD   $0x38756835           // MOVBU (R1)(R21), R21                 // ldrb	w21, [x1, x21]
	ANDW   $4294967263, R22, R23 // <--                                  // and	w23, w22, #0xffffffdf
	SUBW   $65, R23, R24         // <--                                  // sub	w24, w23, #65
	ANDW   $4294967263, R21, R25 // <--                                  // and	w25, w21, #0xffffffdf
	CMPW   $26, R24              // <--                                  // cmp	w24, #26
	SUBW   $65, R25, R24         // <--                                  // sub	w24, w25, #65
	CSELW  LO, R23, R22, R22     // <--                                  // csel	w22, w23, w22, lo
	CMPW   $26, R24              // <--                                  // cmp	w24, #26
	CSELW  LO, R25, R21, R21     // <--                                  // csel	w21, w25, w21, lo
	CMPW   R13, R22              // <--                                  // cmp	w22, w13
	CCMPW  EQ, R21, R14, $0      // <--                                  // ccmp	w21, w14, #0, eq
	BNE    LBB0_63               // <--                                  // b.ne	.LBB0_63
	ADD    R17, R8, R21          // <--                                  // add	x21, x8, x17
	WORD   $0x38756815           // MOVBU (R0)(R21), R21                 // ldrb	w21, [x0, x21]
	ANDW   $4294967263, R21, R22 // <--                                  // and	w22, w21, #0xffffffdf
	SUBW   $65, R22, R23         // <--                                  // sub	w23, w22, #65
	CMPW   $26, R23              // <--                                  // cmp	w23, #26
	CSELW  LO, R22, R21, R21     // <--                                  // csel	w21, w22, w21, lo
	CMPW   R21, R12              // <--                                  // cmp	w12, w21
	BNE    LBB0_63               // <--                                  // b.ne	.LBB0_63
	WORD   $0x39400695           // MOVBU 1(R20), R21                    // ldrb	w21, [x20, #1]
	WORD   $0x394004d8           // MOVBU 1(R6), R24                     // ldrb	w24, [x6, #1]
	ANDW   $4294967263, R21, R22 // <--                                  // and	w22, w21, #0xffffffdf
	SUBW   $65, R22, R23         // <--                                  // sub	w23, w22, #65
	CMPW   $26, R23              // <--                                  // cmp	w23, #26
	CSELW  LO, R22, R21, R21     // <--                                  // csel	w21, w22, w21, lo
	CMPW   R24, R21              // <--                                  // cmp	w21, w24
	BNE    LBB0_61               // <--                                  // b.ne	.LBB0_61
	WORD   $0x39400a95           // MOVBU 2(R20), R21                    // ldrb	w21, [x20, #2]
	WORD   $0x394008d8           // MOVBU 2(R6), R24                     // ldrb	w24, [x6, #2]
	ANDW   $4294967263, R21, R22 // <--                                  // and	w22, w21, #0xffffffdf
	SUBW   $65, R22, R23         // <--                                  // sub	w23, w22, #65
	CMPW   $26, R23              // <--                                  // cmp	w23, #26
	CSELW  LO, R22, R21, R21     // <--                                  // csel	w21, w22, w21, lo
	CMPW   R24, R21              // <--                                  // cmp	w21, w24
	BNE    LBB0_77               // <--                                  // b.ne	.LBB0_77
	WORD   $0x39400e95           // MOVBU 3(R20), R21                    // ldrb	w21, [x20, #3]
	WORD   $0x39400cd8           // MOVBU 3(R6), R24                     // ldrb	w24, [x6, #3]
	ANDW   $4294967263, R21, R22 // <--                                  // and	w22, w21, #0xffffffdf
	SUBW   $65, R22, R23         // <--                                  // sub	w23, w22, #65
	CMPW   $26, R23              // <--                                  // cmp	w23, #26
	CSELW  LO, R22, R21, R21     // <--                                  // csel	w21, w22, w21, lo
	CMPW   R24, R21              // <--                                  // cmp	w21, w24
	BNE    LBB0_78               // <--                                  // b.ne	.LBB0_78
	CMP    $4, R7                // <--                                  // cmp	x7, #4
	BEQ    LBB0_43               // <--                                  // b.eq	.LBB0_43
	WORD   $0x39401295           // MOVBU 4(R20), R21                    // ldrb	w21, [x20, #4]
	WORD   $0x394010d8           // MOVBU 4(R6), R24                     // ldrb	w24, [x6, #4]
	ANDW   $4294967263, R21, R22 // <--                                  // and	w22, w21, #0xffffffdf
	SUBW   $65, R22, R23         // <--                                  // sub	w23, w22, #65
	CMPW   $26, R23              // <--                                  // cmp	w23, #26
	CSELW  LO, R22, R21, R21     // <--                                  // csel	w21, w22, w21, lo
	CMPW   R24, R21              // <--                                  // cmp	w21, w24
	BNE    LBB0_79               // <--                                  // b.ne	.LBB0_79
	CMP    $5, R7                // <--                                  // cmp	x7, #5
	BEQ    LBB0_43               // <--                                  // b.eq	.LBB0_43
	WORD   $0x39401695           // MOVBU 5(R20), R21                    // ldrb	w21, [x20, #5]
	WORD   $0x394014d8           // MOVBU 5(R6), R24                     // ldrb	w24, [x6, #5]
	ANDW   $4294967263, R21, R22 // <--                                  // and	w22, w21, #0xffffffdf
	SUBW   $65, R22, R23         // <--                                  // sub	w23, w22, #65
	CMPW   $26, R23              // <--                                  // cmp	w23, #26
	CSELW  LO, R22, R21, R21     // <--                                  // csel	w21, w22, w21, lo
	CMPW   R24, R21              // <--                                  // cmp	w21, w24
	BNE    LBB0_80               // <--                                  // b.ne	.LBB0_80
	CMP    $6, R7                // <--                                  // cmp	x7, #6
	BEQ    LBB0_43               // <--                                  // b.eq	.LBB0_43
	WORD   $0x39401a95           // MOVBU 6(R20), R21                    // ldrb	w21, [x20, #6]
	WORD   $0x394018d8           // MOVBU 6(R6), R24                     // ldrb	w24, [x6, #6]
	ANDW   $4294967263, R21, R22 // <--                                  // and	w22, w21, #0xffffffdf
	SUBW   $65, R22, R23         // <--                                  // sub	w23, w22, #65
	CMPW   $26, R23              // <--                                  // cmp	w23, #26
	CSELW  LO, R22, R21, R21     // <--                                  // csel	w21, w22, w21, lo
	CMPW   R24, R21              // <--                                  // cmp	w21, w24
	BNE    LBB0_81               // <--                                  // b.ne	.LBB0_81
	CMP    $7, R7                // <--                                  // cmp	x7, #7
	BEQ    LBB0_43               // <--                                  // b.eq	.LBB0_43
	WORD   $0x39401e94           // MOVBU 7(R20), R20                    // ldrb	w20, [x20, #7]
	WORD   $0x39401cd7           // MOVBU 7(R6), R23                     // ldrb	w23, [x6, #7]
	ANDW   $4294967263, R20, R21 // <--                                  // and	w21, w20, #0xffffffdf
	SUBW   $65, R21, R22         // <--                                  // sub	w22, w21, #65
	CMPW   $26, R22              // <--                                  // cmp	w22, #26
	CSELW  LO, R21, R20, R20     // <--                                  // csel	w20, w21, w20, lo
	CMPW   R23, R20              // <--                                  // cmp	w20, w23
	CSINCW EQ, R2, ZR, R21       // <--                                  // csinc	w21, w2, wzr, eq
	CINC   EQ, R19, R20          // <--                                  // cinc	x20, x19, eq
	TBNZ   $0, R21, LBB0_62      // <--                                  // tbnz	w21, #0, .LBB0_62
	JMP    LBB0_43               // <--                                  // b	.LBB0_43

LBB0_77:
	MOVW $2, R20 // <--                                  // mov	w20, #2
	JMP  LBB0_62 // <--                                  // b	.LBB0_62

LBB0_78:
	MOVW $3, R20 // <--                                  // mov	w20, #3
	JMP  LBB0_62 // <--                                  // b	.LBB0_62

LBB0_79:
	MOVW $4, R20 // <--                                  // mov	w20, #4
	JMP  LBB0_62 // <--                                  // b	.LBB0_62

LBB0_80:
	MOVW $5, R20 // <--                                  // mov	w20, #5
	JMP  LBB0_62 // <--                                  // b	.LBB0_62

LBB0_81:
	MOVW $6, R20 // <--                                  // mov	w20, #6
	JMP  LBB0_62 // <--                                  // b	.LBB0_62

TEXT ·indexAnySve2(SB), NOSPLIT, $0-40
	MOVD data+0(FP), R0
	MOVD data_len+8(FP), R1
	MOVD chars+16(FP), R2
	MOVD chars_len+24(FP), R3
	MOVD $-1, R8              // <--                                  // mov	x8, #-1
	CBZ  R1, LBB1_16          // <--                                  // cbz	x1, .LBB1_16
	CBZ  R3, LBB1_16          // <--                                  // cbz	x3, .LBB1_16
	NOP                       // (skipped)                            // stp	x29, x30, [sp, #-16]!
	SUBS $16, R3, R9          // <--                                  // subs	x9, x3, #16
	MOVW $16, R8              // <--                                  // mov	w8, #16
	CSEL LO, R3, R8, R8       // <--                                  // csel	x8, x3, x8, lo
	WORD $0x2518e3e0          // ?                                    // ptrue	p0.b
	NOP                       // (skipped)                            // mov	x29, sp
	WORD $0x25281fe1          // ?                                    // whilelo	p1.b, xzr, x8
	WORD $0x04bf5028          // ?                                    // rdvl	x8, #1
	WORD $0xa400a440          // ?                                    // ld1b	{ z0.b }, p1/z, [x2]
	WORD $0x84408041          // ?                                    // ld1rb	{ z1.b }, p0/z, [x2]
	CMP  $17, R3              // <--                                  // cmp	x3, #17
	WORD $0x0521c400          // ?                                    // sel	z0.b, p1, z0.b, z1.b
	WORD $0x04603002          // ?                                    // mov	z2.d, z0.d
	WORD $0x04603001          // ?                                    // mov	z1.d, z0.d
	WORD $0x04603003          // ?                                    // mov	z3.d, z0.d
	BCC  LBB1_7               // <--                                  // b.lo	.LBB1_7
	CMP  $16, R9              // <--                                  // cmp	x9, #16
	MOVW $16, R10             // <--                                  // mov	w10, #16
	CSEL LO, R9, R10, R9      // <--                                  // csel	x9, x9, x10, lo
	WORD $0x84508042          // ?                                    // ld1rb	{ z2.b }, p0/z, [x2, #16]
	WORD $0x25291fe1          // ?                                    // whilelo	p1.b, xzr, x9
	WORD $0xa40a4441          // ?                                    // ld1b	{ z1.b }, p1/z, [x2, x10]
	CMP  $33, R3              // <--                                  // cmp	x3, #33
	WORD $0x0522c421          // ?                                    // sel	z1.b, p1, z1.b, z2.b
	BCC  LBB1_6               // <--                                  // b.lo	.LBB1_6
	SUB  $32, R3, R9          // <--                                  // sub	x9, x3, #32
	MOVW $16, R10             // <--                                  // mov	w10, #16
	CMP  $16, R9              // <--                                  // cmp	x9, #16
	WORD $0x84608043          // ?                                    // ld1rb	{ z3.b }, p0/z, [x2, #32]
	CSEL LO, R9, R10, R9      // <--                                  // csel	x9, x9, x10, lo
	MOVW $32, R10             // <--                                  // mov	w10, #32
	WORD $0x25291fe1          // ?                                    // whilelo	p1.b, xzr, x9
	WORD $0xa40a4442          // ?                                    // ld1b	{ z2.b }, p1/z, [x2, x10]
	CMP  $49, R3              // <--                                  // cmp	x3, #49
	WORD $0x0523c442          // ?                                    // sel	z2.b, p1, z2.b, z3.b
	BCC  LBB1_11              // <--                                  // b.lo	.LBB1_11
	SUB  $48, R3, R9          // <--                                  // sub	x9, x3, #48
	MOVW $16, R10             // <--                                  // mov	w10, #16
	CMP  $16, R9              // <--                                  // cmp	x9, #16
	WORD $0x84708044          // ?                                    // ld1rb	{ z4.b }, p0/z, [x2, #48]
	CSEL LO, R9, R10, R9      // <--                                  // csel	x9, x9, x10, lo
	MOVW $48, R10             // <--                                  // mov	w10, #48
	WORD $0x25291fe1          // ?                                    // whilelo	p1.b, xzr, x9
	WORD $0xa40a4443          // ?                                    // ld1b	{ z3.b }, p1/z, [x2, x10]
	WORD $0x0524c463          // ?                                    // sel	z3.b, p1, z3.b, z4.b
	MOVD R0, R9               // <--                                  // mov	x9, x0
	CMP  R1, R8               // <--                                  // cmp	x8, x1
	BLS  LBB1_8               // <--                                  // b.ls	.LBB1_8
	JMP  LBB1_12              // <--                                  // b	.LBB1_12

LBB1_6:
	WORD $0x04603002 // ?                                    // mov	z2.d, z0.d
	WORD $0x04603003 // ?                                    // mov	z3.d, z0.d

LBB1_7:
	MOVD R0, R9  // <--                                  // mov	x9, x0
	CMP  R1, R8  // <--                                  // cmp	x8, x1
	BHI  LBB1_12 // <--                                  // b.hi	.LBB1_12

LBB1_8:
	WORD $0xa400a124 // ?                                    // ld1b	{ z4.b }, p0/z, [x9]
	WORD $0x45208081 // ?                                    // match	p1.b, p0/z, z4.b, z0.b
	WORD $0x45218082 // ?                                    // match	p2.b, p0/z, z4.b, z1.b
	WORD $0x45228083 // ?                                    // match	p3.b, p0/z, z4.b, z2.b
	WORD $0x45238084 // ?                                    // match	p4.b, p0/z, z4.b, z3.b
	WORD $0x25824021 // ?                                    // orr	p1.b, p0/z, p1.b, p2.b
	WORD $0x25844062 // ?                                    // orr	p2.b, p0/z, p3.b, p4.b
	WORD $0x25c24021 // ?                                    // orrs	p1.b, p0/z, p1.b, p2.b
	BNE  LBB1_13     // <--                                  // b.ne	.LBB1_13
	ADD  R8, R9, R9  // <--                                  // add	x9, x9, x8
	SUB  R8, R1, R1  // <--                                  // sub	x1, x1, x8
	CMP  R8, R1      // <--                                  // cmp	x1, x8
	BCS  LBB1_8      // <--                                  // b.hs	.LBB1_8
	CBNZ R1, LBB1_12 // <--                                  // cbnz	x1, .LBB1_12
	JMP  LBB1_14     // <--                                  // b	.LBB1_14

LBB1_11:
	WORD $0x04603003 // ?                                    // mov	z3.d, z0.d
	MOVD R0, R9      // <--                                  // mov	x9, x0
	CMP  R1, R8      // <--                                  // cmp	x8, x1
	BLS  LBB1_8      // <--                                  // b.ls	.LBB1_8

LBB1_12:
	WORD $0x25211fe0 // ?                                    // whilelo	p0.b, xzr, x1
	WORD $0xa400a124 // ?                                    // ld1b	{ z4.b }, p0/z, [x9]
	WORD $0x45208081 // ?                                    // match	p1.b, p0/z, z4.b, z0.b
	WORD $0x45218082 // ?                                    // match	p2.b, p0/z, z4.b, z1.b
	WORD $0x45228083 // ?                                    // match	p3.b, p0/z, z4.b, z2.b
	WORD $0x45238084 // ?                                    // match	p4.b, p0/z, z4.b, z3.b
	WORD $0x25824021 // ?                                    // orr	p1.b, p0/z, p1.b, p2.b
	WORD $0x25844062 // ?                                    // orr	p2.b, p0/z, p3.b, p4.b
	WORD $0x25c24021 // ?                                    // orrs	p1.b, p0/z, p1.b, p2.b
	BEQ  LBB1_14     // <--                                  // b.eq	.LBB1_14

LBB1_13:
	WORD $0x25904021 // ?                                    // brkb	p1.b, p0/z, p1.b
	SUB  R0, R9, R9  // <--                                  // sub	x9, x9, x0
	WORD $0x25208028 // ?                                    // cntp	x8, p0, p1.b
	ADD  R8, R9, R8  // <--                                  // add	x8, x9, x8
	JMP  LBB1_15     // <--                                  // b	.LBB1_15

LBB1_14:
	MOVD $-1, R8 // <--                                  // mov	x8, #-1

LBB1_15:
	NOP // (skipped)                            // ldp	x29, x30, [sp], #16

LBB1_16:
	MOVD R8, R0         // <--                                  // mov	x0, x8
	MOVD R0, ret+32(FP) // <--
	RET                 // <--                                  // ret
