//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package ascii


//go:noescape
func indexFoldNeedleSve2(haystack string, rare1 byte, off1 int, rare2 byte, off2 int, normNeedle string) int

//go:noescape
func indexAnySve2(data string, chars string) int
