//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package ascii


//go:noescape
func IndexFoldMemchr(haystack string, rare1 byte, off1 int, rare2 byte, off2 int, needle string) int

//go:noescape
func SearcherIndexFoldMemchr(haystack string, rare1 byte, off1 int, rare2 byte, off2 int, normNeedle string) int
